//! End-to-end tests for the FLAC handler, over the fixtures in `corpus/flac`.
//!
//! Each fixture is generated by `corpus/tools/make_flac_fixtures.py` and documented in
//! `corpus/MANIFEST.md`. The synthetic marker strings — `SYNTHETIC-…-000N` — exist so a test can
//! assert on the *bytes of the output* rather than on strypt's own report: a handler that forgot
//! to remove something would still report having removed it.
//!
//! # Why this file carries its own block walker
//!
//! The claims that matter — that the audio crossed byte for byte, and that exactly the block types
//! ADR-0038 names reached the output — are claims about structure, and checking them with the
//! handler's own walker would assert only that the parser agrees with itself. [`blocks`] walks the
//! file independently, as `tests/jxl.rs` walks a box tree.

// Test code is not reachable from untrusted bytes, which is the boundary the panic-freedom
// lints police (ADR-0006).
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing,
    clippy::arithmetic_side_effects
)]

use strypt_core::formats::StripOptions;
use strypt_core::report::{InspectOptions, MetadataKind, Note, RetentionReason};
use strypt_core::{Format, detect, inspect_bytes, strip_bytes};

fn fixture(name: &str) -> Vec<u8> {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../corpus/flac")
        .join(name);
    std::fs::read(&path).unwrap_or_else(|e| panic!("reading fixture {}: {e}", path.display()))
}

fn strip(name: &str) -> Vec<u8> {
    let input = fixture(name);
    strip_bytes(&input, &StripOptions::default())
        .unwrap_or_else(|e| panic!("stripping {name}: {e}"))
        .bytes
}

fn contains(haystack: &[u8], needle: &str) -> bool {
    haystack
        .windows(needle.len())
        .any(|w| w == needle.as_bytes())
}

const FIXTURES: &[&str] = &[
    "clean.flac",
    "vorbis-comment.flac",
    "cover-art.flac",
    "cuesheet.flac",
    "seektable.flac",
    "application.flac",
    "padding-with-data.flac",
    "reserved-block.flac",
    "no-audio-md5.flac",
    "kitchen-sink.flac",
];

const MALFORMED: &[&str] = &[
    "malformed/id3-prefixed.flac",
    "malformed/wrong-marker.flac",
    "malformed/no-streaminfo.flac",
    "malformed/streaminfo-wrong-length.flac",
    "malformed/second-streaminfo.flac",
    "malformed/forbidden-block-type.flac",
    "malformed/block-overruns-file.flac",
    "malformed/no-frame-sync.flac",
];

/// Every metadata block in `data` as `(type, payload)`, plus the audio frames, found by an
/// independent walk.
///
/// Deliberately written here rather than borrowed from `strypt_core`: see this file's header.
fn blocks(data: &[u8]) -> (Vec<(u8, Vec<u8>)>, Vec<u8>) {
    assert_eq!(&data[..4], b"fLaC", "not a FLAC stream");
    let mut at = 4;
    let mut out = Vec::new();
    loop {
        let header = &data[at..at + 4];
        let last = header[0] & 0x80 != 0;
        let kind = header[0] & 0x7F;
        let length =
            usize::try_from(u32::from_be_bytes([0, header[1], header[2], header[3]])).unwrap();
        at += 4;
        out.push((kind, data[at..at + length].to_vec()));
        at += length;
        if last {
            break;
        }
    }
    // §9.1.1's 14-bit sync, which is what says the block list really ended here.
    assert_eq!(data[at], 0xFF, "no frame sync after the last block");
    assert_eq!(
        data[at + 1] & 0xFE,
        0xF8,
        "no frame sync after the last block"
    );
    (out, data[at..].to_vec())
}

fn kinds(data: &[u8]) -> Vec<u8> {
    blocks(data).0.into_iter().map(|(kind, _)| kind).collect()
}

#[test]
fn every_fixture_is_detected_as_flac() {
    for name in FIXTURES {
        assert_eq!(
            detect(&fixture(name)).unwrap(),
            Format::Flac,
            "{name} was not detected as FLAC"
        );
    }
    // The malformed ones too — a file has to be routed here before it can be refused here. The
    // two exceptions no longer *are* FLAC at the detection layer: one has a corrupted marker, and
    // the other opens with an ID3v2 tag, which is refused by name rather than routed (ADR-0037).
    for name in MALFORMED {
        if name.contains("wrong-marker") || name.contains("id3-prefixed") {
            continue;
        }
        assert_eq!(
            detect(&fixture(name)).unwrap(),
            Format::Flac,
            "{name} was not detected as FLAC"
        );
    }
}

#[test]
fn no_synthetic_marker_survives_any_fixture() {
    // The sweep: every identifying value in the corpus is a `SYNTHETIC-` marker, so one assertion
    // covers every block at once, including the ones no test below names individually.
    for name in FIXTURES {
        let output = strip(name);
        assert!(
            !contains(&output, "SYNTHETIC"),
            "a synthetic marker survived stripping {name}"
        );
    }
}

#[test]
fn a_clean_file_strips_to_a_byte_identical_copy() {
    // What block surgery buys and a rebuild cannot promise (ADR-0038, against ADR-0033's TIFF).
    // The fixture's padding is already the zero bits §8.2 calls for, so nothing moves.
    let input = fixture("clean.flac");
    let stripped = strip_bytes(&input, &StripOptions::default()).unwrap();
    assert!(stripped.report.removed.is_empty());
    assert_eq!(stripped.bytes, input);
}

#[test]
fn the_audio_crosses_byte_for_byte() {
    // Nothing here decodes or re-encodes audio, so the frames must appear in the output exactly
    // as they appeared in the input, on every fixture.
    for name in FIXTURES {
        assert_eq!(
            blocks(&fixture(name)).1,
            blocks(&strip(name)).1,
            "{name}: the audio did not cross the strip intact"
        );
    }
}

#[test]
fn only_the_allow_listed_blocks_reach_the_output() {
    // STREAMINFO, SEEKTABLE, PADDING. Everything else in §8.2 either is metadata or cannot be
    // shown not to be, and goes.
    for name in FIXTURES {
        for kind in kinds(&strip(name)) {
            assert!(
                matches!(kind, 0 | 1 | 3),
                "{name}: block type {kind} survived stripping"
            );
        }
    }
}

#[test]
fn the_kitchen_sink_loses_every_metadata_block_and_keeps_the_rest() {
    assert_eq!(kinds(&strip("kitchen-sink.flac")), vec![0, 3, 1]);
}

#[test]
fn a_seek_table_survives_because_removal_moves_no_offset() {
    // RFC 9639 §8.5 measures a seek point from the first byte of the first frame header, not from
    // the start of the file, so deleting metadata cannot invalidate one. This is the sentence that
    // makes FLAC cheap and MP4 expensive (ADR-0037).
    let before = blocks(&fixture("seektable.flac")).0;
    let after = blocks(&strip("seektable.flac")).0;
    let table = |bs: &[(u8, Vec<u8>)]| bs.iter().find(|(k, _)| *k == 3).unwrap().1.clone();
    assert_eq!(table(&before), table(&after));
}

#[test]
fn padding_keeps_its_length_and_loses_whatever_was_in_it() {
    // §8.2 says padding is zero bits. Keeping the block at its size leaves a later tagger the room
    // it was written for; zeroing it removes what a tagger left behind.
    let before = blocks(&fixture("padding-with-data.flac")).0;
    let after = blocks(&strip("padding-with-data.flac")).0;
    let padding = |bs: &[(u8, Vec<u8>)]| bs.iter().find(|(k, _)| *k == 1).unwrap().1.clone();
    assert_eq!(padding(&before).len(), padding(&after).len());
    assert!(padding(&after).iter().all(|b| *b == 0));
}

#[test]
fn a_vorbis_comment_is_itemised_field_by_field() {
    let report = inspect_bytes(
        &fixture("vorbis-comment.flac"),
        &InspectOptions::names_only(),
    )
    .unwrap();
    let fields: Vec<_> = report
        .findings
        .iter()
        .filter_map(|f| f.field.clone())
        .collect();
    for expected in ["vendor", "ARTIST", "DATE", "ENCODER_SETTINGS", "LOCATION"] {
        assert!(
            fields.iter().any(|f| f == expected),
            "{expected} not itemised: {fields:?}"
        );
    }
    let kinds: Vec<_> = report.findings.iter().map(|f| f.kind).collect();
    assert!(kinds.contains(&MetadataKind::PersonalIdentity), "{kinds:?}");
    assert!(kinds.contains(&MetadataKind::Timestamp), "{kinds:?}");
    assert!(kinds.contains(&MetadataKind::Location), "{kinds:?}");
    assert!(
        kinds.contains(&MetadataKind::SoftwareFingerprint),
        "{kinds:?}"
    );
}

#[test]
fn cover_art_goes_whole_and_its_own_metadata_with_it() {
    // ADR-0029's one-level descent into embedded images does not extend to this group (ADR-0037):
    // the picture is removed with its block, so the `tEXt` inside the fixture's PNG never has to
    // be reached. Asserting on the marker proves the outcome without assuming the mechanism.
    let output = strip("cover-art.flac");
    assert!(!contains(&output, "SYNTHETIC-COVER-AUTHOR-0010"));
    assert!(!output.windows(4).any(|w| w == b"\x89PNG"));
    let report = inspect_bytes(&fixture("cover-art.flac"), &InspectOptions::names_only()).unwrap();
    assert!(
        report
            .findings
            .iter()
            .any(|f| f.kind == MetadataKind::Thumbnail)
    );
}

#[test]
fn removing_a_cuesheet_is_declared_because_it_costs_the_user_something() {
    // It carries the disc's catalogue number and each track's ISRC, so it goes; but it is also
    // what lets the file be split back into tracks, and losing that is worth saying (ADR-0038).
    let report = inspect_bytes(&fixture("cuesheet.flac"), &InspectOptions::names_only()).unwrap();
    assert!(
        report
            .notes
            .iter()
            .any(|n| matches!(n, Note::CapabilityRemoved { location, .. } if location.contains("CUESHEET"))),
        "no note about what removing the cuesheet costs"
    );
    assert!(!contains(&strip("cuesheet.flac"), "SYNISRC"));
}

#[test]
fn the_audio_md5_is_kept_and_declared_rather_than_quietly_left() {
    // It is a fingerprint, and it stays: it is computed from the samples the file still carries,
    // so anyone holding the file can recompute it (ADR-0038). Declared, not passed over.
    let report = strip_bytes(&fixture("vorbis-comment.flac"), &StripOptions::default())
        .unwrap()
        .report;
    assert!(
        report
            .retained
            .iter()
            .any(|r| r.reason == RetentionReason::DerivedFromPayload),
        "the STREAMINFO MD5 was not declared: {:?}",
        report.retained
    );
    // And where the encoder never wrote one, there is nothing to declare.
    let absent = strip_bytes(&fixture("no-audio-md5.flac"), &StripOptions::default())
        .unwrap()
        .report;
    assert!(absent.retained.is_empty(), "{:?}", absent.retained);
}

#[test]
fn every_report_says_the_audio_was_not_decoded() {
    // Declared on every file, clean ones included. A verdict that covers the block list and says
    // so is honest; the same verdict unqualified would not be.
    for name in FIXTURES {
        let report = inspect_bytes(&fixture(name), &InspectOptions::names_only()).unwrap();
        assert!(
            report.notes.iter().any(|n| matches!(
                n,
                Note::OutOfScopeContent { location } if location.contains("audio frames")
            )),
            "{name}: no note about the audio"
        );
    }
}

#[test]
fn every_malformed_fixture_is_refused() {
    // Fail-closed: none of these produces output. A partly-cleaned FLAC is worse than a refusal,
    // because the user acts on the success message by publishing.
    for name in MALFORMED {
        let input = fixture(name);
        let result = detect(&input).and_then(|_| strip_bytes(&input, &StripOptions::default()));
        assert!(result.is_err(), "{name} was not refused");
    }
}

#[test]
fn the_output_of_every_fixture_re_inspects_clean() {
    // What the pipeline's verification pass does, asserted directly over the corpus.
    for name in FIXTURES {
        let output = strip(name);
        let report = inspect_bytes(&output, &InspectOptions::names_only())
            .unwrap_or_else(|e| panic!("stripped {name} no longer inspects: {e}"));
        assert!(
            report.findings.is_empty(),
            "metadata survived stripping {name}: {:?}",
            report.findings
        );
    }
}

#[test]
fn stripping_is_idempotent_over_the_whole_corpus() {
    for name in FIXTURES {
        let once = strip(name);
        let twice = strip_bytes(&once, &StripOptions::default())
            .unwrap_or_else(|e| panic!("re-stripping {name}: {e}"))
            .bytes;
        assert_eq!(once, twice, "stripping {name} is not idempotent");
    }
}

#[test]
fn inspect_and_strip_agree_about_what_is_in_the_file() {
    for name in FIXTURES {
        let input = fixture(name);
        let seen = inspect_bytes(&input, &InspectOptions::names_only()).unwrap();
        let removed = strip_bytes(&input, &StripOptions::default())
            .unwrap()
            .report;
        assert_eq!(
            seen.findings.len(),
            removed.removed.len(),
            "{name}: inspect and strip disagree"
        );
    }
}

#[test]
fn truncating_any_fixture_anywhere_never_panics() {
    for name in FIXTURES {
        let input = fixture(name);
        for cut in 0..input.len() {
            let _ = strip_bytes(&input[..cut], &StripOptions::default());
        }
    }
}

#[test]
fn flipping_any_single_byte_never_panics() {
    for name in FIXTURES {
        let input = fixture(name);
        for at in 0..input.len() {
            let mut mutated = input.clone();
            mutated[at] ^= 0xFF;
            let _ = strip_bytes(&mutated, &StripOptions::default());
        }
    }
}
