//! End-to-end tests for the GIF handler, over the fixtures in `corpus/gif`.
//!
//! Each fixture is generated by `corpus/tools/make_gif_fixtures.py` and documented in
//! `corpus/MANIFEST.md`. The synthetic marker strings — `SYNTHETIC-…-000N` — exist so that a test
//! can assert on the *bytes of the output* rather than on strypt's own report. That distinction
//! is the point: a handler that forgot to remove something would still happily report having
//! removed it.
//!
//! # Why this file carries its own GIF walker
//!
//! The claim that matters most here is that the compressed image data crossed untouched, and GIF
//! cannot make that claim the way TIFF does — its pixels are LZW-compressed, so no `PRESERVED-`
//! marker can be planted in them. Instead [`image_blocks`] walks the file independently, the way
//! `tests/common/mod.rs` walks a ZIP for the package formats, and the tests compare the blocks it
//! finds before and after. A test that located the image data using the handler's own parser
//! would be asserting that the parser agrees with itself.

// Test code is not reachable from untrusted bytes, which is the boundary the panic-freedom
// lints police (ADR-0006).
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing,
    clippy::arithmetic_side_effects
)]

use strypt_core::formats::StripOptions;
use strypt_core::report::{InspectOptions, MetadataKind};
use strypt_core::{Format, detect, inspect_bytes, strip_bytes};

fn fixture(name: &str) -> Vec<u8> {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../corpus/gif")
        .join(name);
    std::fs::read(&path).unwrap_or_else(|e| panic!("reading fixture {}: {e}", path.display()))
}

fn strip(name: &str) -> Vec<u8> {
    let input = fixture(name);
    strip_bytes(&input, &StripOptions::default())
        .unwrap_or_else(|e| panic!("stripping {name}: {e}"))
        .bytes
}

fn contains(haystack: &[u8], needle: &str) -> bool {
    haystack
        .windows(needle.len())
        .any(|w| w == needle.as_bytes())
}

/// Every fixture that is a well-formed GIF the handler is expected to accept.
const FIXTURES: &[&str] = &[
    "clean.gif",
    "comment.gif",
    "long-comment.gif",
    "xmp.gif",
    "application-blocks.gif",
    "unknown-application.gif",
    "animated-loop.gif",
    "animated-no-loop.gif",
    "transparency.gif",
    "plain-text.gif",
    "interlaced-local-table.gif",
    "unknown-extension.gif",
    "trailing-data.gif",
    "gif87a.gif",
];

const MALFORMED: &[&str] = &[
    "malformed/truncated-header.gif",
    "malformed/no-trailer.gif",
    "malformed/sub-block-past-end.gif",
    "malformed/unterminated-sub-blocks.gif",
    "malformed/bad-introducer.gif",
    "malformed/colour-table-past-end.gif",
];

/// Every image block in `data`, as raw bytes, found by an independent walk.
///
/// Deliberately written here rather than borrowed from `strypt_core`: see this file's header.
fn image_blocks(data: &[u8]) -> Vec<Vec<u8>> {
    let mut at = 6;
    let packed = data[10];
    at += 7;
    if packed & 0x80 != 0 {
        at += 3 * (1 << ((packed & 7) + 1));
    }

    let mut out = Vec::new();
    loop {
        let start = at;
        match data[at] {
            0x3B => return out,
            0x21 => {
                at += 2;
                at = skip_sub_blocks(data, at);
            }
            0x2C => {
                let packed = data[at + 9];
                at += 10;
                if packed & 0x80 != 0 {
                    at += 3 * (1 << ((packed & 7) + 1));
                }
                at += 1; // LZW minimum code size
                at = skip_sub_blocks(data, at);
                out.push(data[start..at].to_vec());
            }
            other => panic!("unexpected block introducer 0x{other:02X} at {at}"),
        }
    }
}

fn skip_sub_blocks(data: &[u8], mut at: usize) -> usize {
    loop {
        let length = data[at] as usize;
        at += 1 + length;
        if length == 0 {
            return at;
        }
    }
}

#[test]
fn every_fixture_is_detected_as_gif() {
    for name in FIXTURES {
        assert_eq!(
            detect(&fixture(name)).unwrap(),
            Format::Gif,
            "{name} was not detected as GIF"
        );
    }
}

#[test]
fn no_synthetic_marker_survives_any_fixture() {
    // The sweep. Every identifying value in the corpus is a `SYNTHETIC-` marker, so one
    // assertion covers every comment, packet, and application block at once — including the ones
    // no test below names individually.
    for name in FIXTURES {
        let output = strip(name);
        assert!(
            !contains(&output, "SYNTHETIC"),
            "a synthetic marker survived stripping {name}"
        );
    }
}

#[test]
fn the_picture_crosses_byte_for_byte() {
    // The claim that separates strypt's approach from mat2's, which re-renders a GIF through
    // GdkPixbuf. The LZW data is never decoded here, so every image block must appear in the
    // output exactly as it appeared in the input — same count, same bytes, same order.
    for name in FIXTURES {
        let before = image_blocks(&fixture(name));
        let after = image_blocks(&strip(name));
        assert_eq!(
            before, after,
            "{name}: the compressed image data did not cross the strip intact"
        );
    }
}

#[test]
fn a_clean_file_strips_to_a_byte_identical_copy() {
    // A block-list format can promise this and TIFF cannot (ADR-0033): kept blocks are copied
    // raw, so a file that had nothing wrong with it comes back unchanged.
    let input = fixture("clean.gif");
    let stripped = strip_bytes(&input, &StripOptions::default()).unwrap();
    assert!(stripped.report.removed.is_empty());
    assert_eq!(stripped.bytes, input);
}

#[test]
fn the_output_of_every_fixture_re_inspects_clean() {
    // What the pipeline's verification pass does, asserted directly over the corpus.
    for name in FIXTURES {
        let output = strip(name);
        let report = inspect_bytes(&output, &InspectOptions::names_only())
            .unwrap_or_else(|e| panic!("stripped {name} no longer inspects: {e}"));
        assert!(
            report.findings.is_empty(),
            "metadata survived stripping {name}: {:?}",
            report.findings
        );
    }
}

#[test]
fn stripping_is_idempotent_over_the_whole_corpus() {
    for name in FIXTURES {
        let once = strip(name);
        let twice = strip_bytes(&once, &StripOptions::default())
            .unwrap_or_else(|e| panic!("re-stripping {name}: {e}"))
            .bytes;
        assert_eq!(once, twice, "stripping {name} is not idempotent");
    }
}

#[test]
fn a_comment_is_reported_as_a_comment_and_removed() {
    let report = inspect_bytes(&fixture("comment.gif"), &InspectOptions::names_only()).unwrap();
    assert_eq!(report.findings.len(), 1);
    assert_eq!(report.findings[0].kind, MetadataKind::Comment);
    assert_eq!(report.findings[0].location, "Comment Extension");
    assert!(!contains(&strip("comment.gif"), "SYNTHETIC-COMMENT-0001"));
}

#[test]
fn a_comment_spanning_several_sub_blocks_is_removed_whole() {
    // 600 bytes of comment is three sub-blocks. A walk that mishandled the chain would leave a
    // tail of it in the output, which the marker sweep would catch but this names.
    let output = strip("long-comment.gif");
    assert!(!contains(&output, "SYNTHETIC-LONG-COMMENT-0002"));
    assert!(!contains(&output, "SYNTHETIC-SECOND-COMMENT-0003"));
    assert!(!contains(&output, "...."));
}

#[test]
fn an_xmp_packet_is_itemised_by_property_and_removed() {
    let report = inspect_bytes(&fixture("xmp.gif"), &InspectOptions::names_only()).unwrap();
    let named: Vec<&str> = report
        .findings
        .iter()
        .filter_map(|f| f.field.as_deref())
        .collect();
    for expected in ["dc:creator", "xmp:CreatorTool", "xmpMM:DocumentID"] {
        assert!(
            named.contains(&expected),
            "{expected} was not reported; got {named:?}"
        );
    }
    let output = strip("xmp.gif");
    assert!(!contains(&output, "SYNTHETIC-XMP-CREATOR-0004"));
    assert!(!contains(&output, "XMP DataXMP"));
}

#[test]
fn the_blocks_imagemagick_writes_are_reported_by_what_they_carry() {
    let report = inspect_bytes(
        &fixture("application-blocks.gif"),
        &InspectOptions::names_only(),
    )
    .unwrap();
    let kinds: Vec<MetadataKind> = report.findings.iter().map(|f| f.kind).collect();
    assert!(
        kinds.contains(&MetadataKind::ColourProfile),
        "the ICC profile was not ranked as one: {report:?}"
    );
    assert!(
        kinds.contains(&MetadataKind::PersonalIdentity),
        "the IPTC by-line was not ranked as naming a person: {report:?}"
    );
    assert!(!contains(
        &strip("application-blocks.gif"),
        "SYNTHETIC-IPTC-BYLINE-0009"
    ));
}

#[test]
fn an_unknown_application_block_does_not_survive_by_being_unknown() {
    // The fixture that justifies the allow-list running in the direction it does: under a
    // deny-list this block survives precisely because nothing recognises it.
    let report = inspect_bytes(
        &fixture("unknown-application.gif"),
        &InspectOptions::names_only(),
    )
    .unwrap();
    assert_eq!(report.findings.len(), 1);
    let output = strip("unknown-application.gif");
    assert!(!contains(&output, "SYNTHETIC-VENDOR-SERIAL-0010"));
    assert!(!contains(&output, "VENDORX1.0"));
}

#[test]
fn an_animation_still_loops_after_stripping() {
    // The decision this handler turns on. The loop count is a rendering instruction, not
    // identity — removing it would silently turn a looping animation into a one-shot.
    let stripped = strip_bytes(&fixture("animated-loop.gif"), &StripOptions::default()).unwrap();
    assert!(
        contains(&stripped.bytes, "NETSCAPE2.0"),
        "the loop extension did not survive"
    );
    assert_eq!(
        stripped.report.retained[0].location, "Application Extension (loop count)",
        "the loop block was kept without being declared"
    );
    assert!(!contains(
        &stripped.bytes,
        "SYNTHETIC-ANIMATION-COMMENT-0011"
    ));
    assert_eq!(
        image_blocks(&stripped.bytes).len(),
        3,
        "a frame was lost from the animation"
    );
}

#[test]
fn an_animation_without_a_loop_block_does_not_acquire_one() {
    // The other half of the previous test: the handler keeps what was there, it does not decide
    // that an animation ought to loop.
    let output = strip("animated-no-loop.gif");
    assert!(!contains(&output, "NETSCAPE2.0"));
    assert_eq!(image_blocks(&output).len(), 2);
}

#[test]
fn transparency_and_frame_delay_survive() {
    // Graphic control blocks are rendering instructions. Dropping them would change how the
    // image looks in front of the user, which is a payload change (`docs/PRD.md` §8.1).
    let input = fixture("transparency.gif");
    let output = strip("transparency.gif");
    // 0x21 0xF9 0x04, packed with the transparency flag, a 50-tick delay, index 3.
    let control = [0x21u8, 0xF9, 0x04, 0x09, 0x32, 0x00, 0x03, 0x00];
    assert!(input.windows(control.len()).any(|w| w == control));
    assert!(
        output.windows(control.len()).any(|w| w == control),
        "the graphic control block did not survive"
    );
}

#[test]
fn a_plain_text_block_takes_its_graphic_control_block_with_it() {
    // §23: a graphic control block applies to the next graphic-rendering block. Leaving one in
    // front of an image it was never meant for would hand that image somebody else's delay.
    let input = fixture("plain-text.gif");
    let output = strip("plain-text.gif");
    assert!(!contains(&output, "SYNTHETIC-PLAINTEXT-0013"));

    let count = |data: &[u8]| {
        data.windows(3)
            .filter(|w| w[0] == 0x21 && w[1] == 0xF9 && w[2] == 0x04)
            .count()
    };
    assert_eq!(count(&input), 2);
    assert_eq!(
        count(&output),
        1,
        "the graphic control block that belonged to the plain-text block was left behind"
    );
}

#[test]
fn an_interlaced_image_and_its_local_colour_table_survive() {
    let output = strip("interlaced-local-table.gif");
    let blocks = image_blocks(&output);
    assert_eq!(blocks.len(), 1);
    // Bit 6 is interlace, bit 7 a local colour table; both are in the descriptor's packed field.
    let packed = blocks[0][9];
    assert_eq!(packed & 0x40, 0x40, "the interlace flag was lost");
    assert_eq!(packed & 0x80, 0x80, "the local colour table was lost");
}

#[test]
fn an_extension_under_an_undefined_label_is_removed() {
    let report = inspect_bytes(
        &fixture("unknown-extension.gif"),
        &InspectOptions::names_only(),
    )
    .unwrap();
    assert_eq!(report.findings[0].location, "Extension 0x42");
    assert!(!contains(
        &strip("unknown-extension.gif"),
        "SYNTHETIC-UNKNOWN-EXTENSION-0015"
    ));
}

#[test]
fn data_hidden_after_the_trailer_is_removed() {
    let stripped = strip_bytes(&fixture("trailing-data.gif"), &StripOptions::default()).unwrap();
    assert!(!contains(&stripped.bytes, "SYNTHETIC-APPENDED-0016"));
    assert_eq!(
        stripped.report.removed[0].location,
        "trailing data after the trailer"
    );
    assert_eq!(stripped.bytes, fixture("clean.gif"));
}

#[test]
fn a_gif87a_file_is_handled_rather_than_refused_on_its_version_string() {
    let output = strip("gif87a.gif");
    assert_eq!(&output[0..6], b"GIF87a", "the version string was rewritten");
    assert!(!contains(&output, "SYNTHETIC-87A-COMMENT-0017"));
}

#[test]
fn every_malformed_fixture_is_refused_rather_than_half_processed() {
    // Fail closed (`CLAUDE.md` §3, constraint 6). None of these may produce output, and none may
    // panic.
    for name in MALFORMED {
        let input = fixture(name);
        assert!(
            strip_bytes(&input, &StripOptions::default()).is_err(),
            "{name} produced output instead of a refusal"
        );
    }
}

#[test]
fn truncating_any_fixture_anywhere_never_panics() {
    // Malformed input is expected input (ADR-0006). Every prefix of every fixture is a file
    // somebody's damaged upload could be.
    for name in FIXTURES {
        let input = fixture(name);
        for cut in 0..input.len() {
            let _ = inspect_bytes(&input[..cut], &InspectOptions::names_only());
            let _ = strip_bytes(&input[..cut], &StripOptions::default());
        }
    }
}

#[test]
fn flipping_any_single_byte_never_panics() {
    // A cheap fuzz-shaped sweep that runs in CI on every push, where the real fuzz runs do not.
    for name in FIXTURES {
        let input = fixture(name);
        for at in 0..input.len() {
            let mut damaged = input.clone();
            damaged[at] ^= 0xFF;
            let _ = inspect_bytes(&damaged, &InspectOptions::names_only());
            let _ = strip_bytes(&damaged, &StripOptions::default());
        }
    }
}
