//! End-to-end tests for the HEIF and AVIF handler, over the fixtures in `corpus/heif`.
//!
//! Each fixture is generated by `corpus/tools/make_heif_fixtures.py`. The `SYNTHETIC-…-000N`
//! markers exist so a test can assert on the *bytes of the output* rather than on strypt's own
//! report — a handler that forgot to remove something would still happily report having removed
//! it.
//!
//! # Why this file carries its own box walker
//!
//! The claim that matters most is that the coded picture crossed the rebuild untouched, and it
//! cannot be checked with a marker: the payload is a real AV1 or HEVC codestream. [`boxes`] walks
//! the file independently, as `tests/common/mod.rs` does for the ZIP formats, so the comparison
//! does not rest on strypt's parser agreeing with itself.

// Test code is not reachable from untrusted bytes (ADR-0006).
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing,
    clippy::arithmetic_side_effects
)]

use strypt_core::error::{MalformedDetail, StryptError, UnsupportedKind};
use strypt_core::formats::StripOptions;
use strypt_core::report::{InspectOptions, MetadataKind};
use strypt_core::{Format, detect, inspect_bytes, strip_bytes};

fn fixture(name: &str) -> Vec<u8> {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../corpus/heif")
        .join(name);
    std::fs::read(&path).unwrap_or_else(|e| panic!("reading fixture {}: {e}", path.display()))
}

fn strip(name: &str) -> Vec<u8> {
    let input = fixture(name);
    strip_bytes(&input, &StripOptions::default())
        .unwrap_or_else(|e| panic!("stripping {name}: {e}"))
        .bytes
}

fn contains(haystack: &[u8], needle: &str) -> bool {
    haystack
        .windows(needle.len())
        .any(|w| w == needle.as_bytes())
}

/// Every well-formed fixture the handler is expected to accept.
const FIXTURES: &[&str] = &[
    "clean.avif",
    "clean.heic",
    "exif.avif",
    "exif.heic",
    "xmp.heic",
    "exif-and-xmp.avif",
    "thumbnail.heic",
    "icc-profile.avif",
    "nclx-colour.avif",
    "uuid-xmp.heic",
    "free-space.avif",
    "unknown-item.avif",
    "unknown-property.heic",
    "named-item.avif",
    "idat-item.heic",
    "meta-xml.avif",
    "trailing-data.heic",
];

const MALFORMED: &[&str] = &[
    "truncated.avif",
    "box-size-below-header.avif",
    "iloc-out-of-range.avif",
    "primary-is-metadata.avif",
    "construction-method-2.heic",
    "live-photo.heic",
    "infe-version-1.avif",
    "external-data-reference.avif",
];

// -------------------------------------------------------------------------------------------
// An independent box walker. Nothing below uses `strypt_core` to find anything.
// -------------------------------------------------------------------------------------------

mod boxes {
    /// One box: its type, its payload, and its children if it is a container.
    pub struct Node {
        pub kind: [u8; 4],
        pub payload: Vec<u8>,
    }

    /// Read the boxes directly inside `data`, stopping at anything that does not tile.
    pub fn walk(data: &[u8]) -> Vec<Node> {
        let mut out = Vec::new();
        let mut at = 0usize;
        while at + 8 <= data.len() {
            let size = u32::from_be_bytes(data[at..at + 4].try_into().unwrap()) as usize;
            let kind: [u8; 4] = data[at + 4..at + 8].try_into().unwrap();
            if size < 8 || at + size > data.len() {
                break;
            }
            out.push(Node {
                kind,
                payload: data[at + 8..at + size].to_vec(),
            });
            at += size;
        }
        out
    }

    /// The first box of `kind` at this level.
    pub fn find(nodes: &[Node], kind: [u8; 4]) -> Option<&Node> {
        nodes.iter().find(|n| n.kind == kind)
    }

    /// The children of a full box, skipping its version and flags.
    pub fn full_children(node: &Node) -> Vec<Node> {
        walk(&node.payload[4..])
    }

    /// The `mdat` payload — the coded picture and nothing else, in a stripped file.
    pub fn mdat(data: &[u8]) -> Vec<u8> {
        find(&walk(data), *b"mdat")
            .map(|n| n.payload.clone())
            .unwrap_or_default()
    }

    /// The item types `iinf` declares, in order.
    pub fn item_types(data: &[u8]) -> Vec<[u8; 4]> {
        let top = walk(data);
        let Some(meta) = find(&top, *b"meta") else {
            return Vec::new();
        };
        let children = full_children(meta);
        let Some(iinf) = find(&children, *b"iinf") else {
            return Vec::new();
        };
        // entry_count is two bytes after the version and flags, then the `infe` boxes.
        full_children(&Node {
            kind: *b"iinf",
            payload: [vec![0u8; 4], iinf.payload[6..].to_vec()].concat(),
        })
        .iter()
        .filter(|n| &n.kind == b"infe")
        .map(|n| {
            // infe v2: version+flags(4), item_ID(2), protection(2), then the type.
            let mut kind = [0u8; 4];
            kind.copy_from_slice(&n.payload[8..12]);
            kind
        })
        .collect()
    }

    /// The property types `ipco` holds, in order.
    pub fn property_types(data: &[u8]) -> Vec<[u8; 4]> {
        let top = walk(data);
        let Some(meta) = find(&top, *b"meta") else {
            return Vec::new();
        };
        let children = full_children(meta);
        let Some(iprp) = find(&children, *b"iprp") else {
            return Vec::new();
        };
        let inner = walk(&iprp.payload);
        let Some(ipco) = find(&inner, *b"ipco") else {
            return Vec::new();
        };
        walk(&ipco.payload).iter().map(|n| n.kind).collect()
    }
}

// -------------------------------------------------------------------------------------------

#[test]
fn both_formats_route_to_this_handler() {
    assert_eq!(detect(&fixture("clean.avif")).unwrap(), Format::Avif);
    assert_eq!(detect(&fixture("clean.heic")).unwrap(), Format::Heif);
}

#[test]
fn an_mp4_is_not_claimed_by_the_still_handler() {
    // The mis-dispatch guard: MP4 shares this container, and routing it here would mean a video
    // reported as a stripped photograph.
    let mut mp4 = vec![0, 0, 0, 0x18];
    mp4.extend_from_slice(b"ftypisom\x00\x00\x02\x00isomiso2");
    assert!(matches!(
        detect(&mp4),
        Err(StryptError::UnsupportedFormat {
            format: UnsupportedKind::IsoBaseMedia
        })
    ));
}

#[test]
fn no_synthetic_marker_survives_any_fixture() {
    // The sweep that does not trust the report. Every identifying value in the corpus is a
    // marker, so a marker in the output is metadata that was announced as removed and was not.
    for name in FIXTURES {
        let out = strip(name);
        assert!(
            !contains(&out, "SYNTHETIC"),
            "a synthetic marker survived {name}"
        );
    }
}

#[test]
fn the_picture_crosses_the_rebuild_byte_for_byte() {
    // Found with this file's own walker, never with the handler's.
    for name in FIXTURES {
        let input = fixture(name);
        let before = boxes::mdat(&input);
        let after = boxes::mdat(&strip(name));
        assert!(
            !after.is_empty(),
            "{name} stripped to a file with no picture in it"
        );
        assert!(
            before.windows(after.len().max(1)).any(|w| w == after)
                || after.windows(before.len().max(1)).any(|w| w == before),
            "{name}: the coded data in the output is not the data that went in"
        );
    }
}

#[test]
fn every_fixture_reinspects_clean() {
    for name in FIXTURES {
        let out = strip(name);
        let report = inspect_bytes(&out, &InspectOptions::names_only())
            .unwrap_or_else(|e| panic!("re-inspecting stripped {name}: {e}"));
        assert!(
            report.findings.is_empty(),
            "{name} still reports {:?} after stripping",
            report.findings
        );
    }
}

#[test]
fn stripping_twice_changes_nothing() {
    for name in FIXTURES {
        let once = strip(name);
        let twice = strip_bytes(&once, &StripOptions::default()).unwrap().bytes;
        assert!(once == twice, "{name}: strip is not idempotent");
    }
}

#[test]
fn gps_and_artist_are_reported_by_name() {
    let report = inspect_bytes(&fixture("exif.avif"), &InspectOptions::names_only()).unwrap();
    let fields: Vec<String> = report
        .findings
        .iter()
        .filter_map(|f| f.field.clone())
        .collect();
    assert!(
        fields.iter().any(|f| f.contains("GPSLatitude")),
        "GPS was not named: {fields:?}"
    );
    assert!(
        fields.iter().any(|f| f.contains("Artist")),
        "the artist was not named: {fields:?}"
    );
    assert!(
        report
            .findings
            .iter()
            .any(|f| f.kind == MetadataKind::Location)
    );
}

#[test]
fn xmp_is_itemised_by_property() {
    let report = inspect_bytes(&fixture("xmp.heic"), &InspectOptions::names_only()).unwrap();
    assert!(
        report
            .findings
            .iter()
            .any(|f| f.field.as_deref() == Some("dc:creator")),
        "XMP was reported as one lump: {:?}",
        report.findings
    );
}

#[test]
fn an_xmp_packet_in_a_uuid_box_is_found() {
    // The blessed extension point. A rule about known box types would walk straight past this.
    let report = inspect_bytes(&fixture("uuid-xmp.heic"), &InspectOptions::names_only()).unwrap();
    assert!(
        report
            .findings
            .iter()
            .any(|f| f.field.as_deref() == Some("dc:creator")),
        "XMP in a uuid box was not found: {:?}",
        report.findings
    );
}

#[test]
fn a_thumbnail_goes_and_the_picture_stays() {
    // The direction of `thmb` matters: it runs from the thumbnail to the master, so reading it
    // backwards deletes the photograph and keeps the thumbnail.
    let input = fixture("thumbnail.heic");
    assert_eq!(boxes::item_types(&input).len(), 2);

    let report = inspect_bytes(&input, &InspectOptions::names_only()).unwrap();
    assert!(
        report
            .findings
            .iter()
            .any(|f| f.kind == MetadataKind::Thumbnail),
        "the thumbnail was not reported: {:?}",
        report.findings
    );

    let out = strip("thumbnail.heic");
    let items = boxes::item_types(&out);
    assert_eq!(items.len(), 1, "one item should survive, got {items:?}");
    assert_eq!(&items[0], b"hvc1");
}

#[test]
fn an_unknown_item_does_not_survive_by_being_unknown() {
    let out = strip("unknown-item.avif");
    let items = boxes::item_types(&out);
    assert!(
        !items.contains(b"XPRV"),
        "a vendor item type reached the output: {items:?}"
    );
    assert_eq!(items.len(), 1);
}

#[test]
fn an_unknown_property_does_not_survive_by_being_unknown() {
    let out = strip("unknown-property.heic");
    let properties = boxes::property_types(&out);
    assert!(!properties.contains(b"XPRP"), "{properties:?}");
    assert!(
        !properties.contains(b"udes"),
        "a free-text description survived: {properties:?}"
    );
    assert!(properties.contains(b"hvcC"), "the decoder config went too");
}

#[test]
fn an_icc_profile_goes_and_nclx_signalling_stays() {
    let stripped_icc = strip("icc-profile.avif");
    assert!(!boxes::property_types(&stripped_icc).contains(b"colr"));

    let stripped_nclx = strip("nclx-colour.avif");
    assert!(
        boxes::property_types(&stripped_nclx).contains(b"colr"),
        "numeric colour signalling was removed with the ICC profiles"
    );

    let report =
        inspect_bytes(&fixture("icc-profile.avif"), &InspectOptions::names_only()).unwrap();
    assert!(
        report
            .findings
            .iter()
            .any(|f| f.kind == MetadataKind::ColourProfile
                || f.location.contains("colr")
                || f.location.contains("ipco")),
        "the profile was not reported: {:?}",
        report.findings
    );
}

#[test]
fn the_nclx_property_is_declared_as_retained() {
    // Kept on purpose, so the report says so rather than leaving the user to discover it.
    let report = strip_bytes(&fixture("nclx-colour.avif"), &StripOptions::default())
        .unwrap()
        .report;
    assert!(
        report.retained.iter().any(|r| r.location.contains("colr")),
        "kept but not declared: {:?}",
        report.retained
    );
}

#[test]
fn the_two_free_text_fields_are_emptied() {
    let report = inspect_bytes(&fixture("named-item.avif"), &InspectOptions::names_only()).unwrap();
    assert!(
        report
            .findings
            .iter()
            .any(|f| f.kind == MetadataKind::SoftwareFingerprint),
        "the handler name was not reported: {:?}",
        report.findings
    );
    let out = strip("named-item.avif");
    assert!(!contains(&out, "SYNTHETIC-HANDLER"));
    assert!(!contains(&out, "SYNTHETIC-ITEM-NAME"));
}

#[test]
fn an_item_stored_in_idat_is_still_reached() {
    // Construction method 1 puts the payload in `meta`'s own `idat`, not in `mdat`. An
    // implementation that only ever looked in `mdat` would report this file clean.
    let report = inspect_bytes(&fixture("idat-item.heic"), &InspectOptions::names_only()).unwrap();
    assert!(
        report.findings.iter().any(|f| f.location.contains("Exif")),
        "Exif in idat was not found: {:?}",
        report.findings
    );
    let out = strip("idat-item.heic");
    assert!(!contains(&out, "SYNTHETIC"));
    // The output stores everything in `mdat`, so no `idat` should remain.
    let top = boxes::walk(&out);
    let meta = boxes::find(&top, *b"meta").unwrap();
    assert!(boxes::find(&boxes::full_children(meta), *b"idat").is_none());
}

#[test]
fn a_metadata_box_inside_meta_is_found() {
    // §8.11.2 puts `xml ` inside `meta`, where a top-level rule would never look.
    let report = inspect_bytes(&fixture("meta-xml.avif"), &InspectOptions::names_only()).unwrap();
    assert!(
        report.findings.iter().any(|f| f.location.contains("meta")),
        "a metadata box inside meta was missed: {:?}",
        report.findings
    );
    assert!(!contains(&strip("meta-xml.avif"), "SYNTHETIC"));
}

#[test]
fn appended_data_is_removed_rather_than_the_file_refused() {
    let report = inspect_bytes(
        &fixture("trailing-data.heic"),
        &InspectOptions::names_only(),
    )
    .unwrap();
    assert!(
        report
            .findings
            .iter()
            .any(|f| f.location.contains("trailing")),
        "{:?}",
        report.findings
    );
    assert!(!contains(&strip("trailing-data.heic"), "SYNTHETIC"));
}

#[test]
fn a_clean_file_keeps_its_picture_and_its_decoder_configuration() {
    for (name, config) in [("clean.avif", b"av1C"), ("clean.heic", b"hvcC")] {
        let properties = boxes::property_types(&strip(name));
        assert!(
            properties.contains(config),
            "{name}: the decoder configuration did not survive: {properties:?}"
        );
        assert!(properties.contains(b"ispe"), "{name}: dimensions went");
    }
}

#[test]
fn a_live_photo_is_refused_by_name() {
    // Not "malformed": the user's file is a photograph as far as they are concerned, and video
    // containers are a later group (ADR-0034).
    let e = strip_bytes(
        &std::fs::read(
            std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
                .join("../../corpus/heif/malformed/live-photo.heic"),
        )
        .unwrap(),
        &StripOptions::default(),
    )
    .unwrap_err();
    assert!(
        matches!(
            e,
            StryptError::UnsupportedFormat {
                format: UnsupportedKind::MotionHeif
            }
        ),
        "got {e:?}"
    );
}

#[test]
fn every_malformed_fixture_is_refused() {
    for name in MALFORMED {
        let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../corpus/heif/malformed")
            .join(name);
        let data = std::fs::read(&path).unwrap();
        assert!(
            strip_bytes(&data, &StripOptions::default()).is_err(),
            "{name} was accepted; a file strypt cannot rebuild must not be written"
        );
    }
}

#[test]
fn a_file_whose_primary_item_is_metadata_is_refused() {
    // Otherwise the output would be a valid container with no picture in it, reported as success.
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../corpus/heif/malformed/primary-is-metadata.avif");
    let e = strip_bytes(&std::fs::read(path).unwrap(), &StripOptions::default()).unwrap_err();
    assert!(
        matches!(
            e,
            StryptError::Malformed {
                detail: MalformedDetail::MissingMarker,
                ..
            }
        ),
        "got {e:?}"
    );
}

#[test]
fn every_prefix_of_every_fixture_is_handled_without_panicking() {
    // Truncation at every possible point. The handler may refuse; it may not panic.
    for name in FIXTURES {
        let data = fixture(name);
        for n in 0..data.len() {
            let _ = inspect_bytes(&data[..n], &InspectOptions::names_only());
            let _ = strip_bytes(&data[..n], &StripOptions::default());
        }
    }
}

#[test]
fn a_single_flipped_byte_never_panics() {
    for name in FIXTURES {
        let data = fixture(name);
        for i in 0..data.len() {
            let mut damaged = data.clone();
            damaged[i] ^= 0xFF;
            let _ = inspect_bytes(&damaged, &InspectOptions::names_only());
            if let Ok(stripped) = strip_bytes(&damaged, &StripOptions::default()) {
                // Anything that survives must still hold the invariants.
                let again = strip_bytes(&stripped.bytes, &StripOptions::default());
                assert!(again.is_ok(), "{name}[{i}]: output does not re-strip");
            }
        }
    }
}
