//! End-to-end tests for the JPEG handler, over the fixtures in `corpus/jpeg`.
//!
//! Each fixture is generated by `corpus/tools/make_jpeg_fixtures.py` and documented in
//! `corpus/MANIFEST.md`. Every one is a real, decodable JPEG built from the same 16×16 base
//! image, which is what makes the pixel-identity test below possible: if two fixtures'
//! entropy-coded data differ after stripping, something re-encoded an image.
//!
//! The synthetic marker strings — `SYNTHETIC-…-000N` — exist so that a test can assert on the
//! *bytes of the output* rather than on strypt's own report. That distinction is the point: a
//! handler that forgot to remove something would still happily report having removed it.

// Test code is not reachable from untrusted bytes, which is the boundary the panic-freedom
// lints police (ADR-0006).
#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use strypt_core::formats::StripOptions;
use strypt_core::report::{InspectOptions, MetadataKind, RetentionReason};
use strypt_core::{Format, detect, inspect_bytes, strip_bytes};

fn fixture(name: &str) -> Vec<u8> {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../corpus/jpeg")
        .join(name);
    std::fs::read(&path).unwrap_or_else(|e| panic!("reading fixture {}: {e}", path.display()))
}

fn strip(name: &str) -> Vec<u8> {
    let input = fixture(name);
    strip_bytes(&input, &StripOptions::default())
        .unwrap_or_else(|e| panic!("stripping {name}: {e}"))
        .bytes
}

/// True when `haystack` contains `needle` anywhere in its bytes.
fn contains(haystack: &[u8], needle: &str) -> bool {
    haystack
        .windows(needle.len())
        .any(|w| w == needle.as_bytes())
}

/// The entropy-coded data: everything from the start-of-scan marker to the end-of-image one.
///
/// This is the photograph. Nothing strypt does may change a byte of it.
fn entropy(data: &[u8]) -> &[u8] {
    let start = data
        .windows(2)
        .position(|w| w == [0xFF, 0xDA])
        .expect("no start-of-scan marker");
    // The *first* end marker after the scan, not the last: a file can carry a whole second
    // image after its end marker, and the picture under test is the first one.
    let end = data
        .get(start..)
        .expect("scan starts inside the file")
        .windows(2)
        .position(|w| w == [0xFF, 0xD9])
        .and_then(|offset| offset.checked_add(start))
        .expect("no end-of-image marker");
    data.get(start..end)
        .expect("scan ends after the image does")
}

const ALL_FIXTURES: &[&str] = &[
    "exif-gps.jpg",
    "exif-thumbnail.jpg",
    "xmp-packet.jpg",
    "comment.jpg",
    "photoshop-iptc.jpg",
    "icc-profile.jpg",
    "jfif-thumbnail.jpg",
    "adobe-marker.jpg",
    "trailing-data.jpg",
    "clean.jpg",
];

/// Every synthetic marker any fixture carries. None may appear in any output.
const ALL_MARKERS: &[&str] = &[
    "SYNTHETIC-CAMERA-MAKE-0001",
    "SYNTHETIC-CAMERA-MODEL-0002",
    "SYNTHETIC-SOFTWARE-0003",
    "SYNTHETIC-ARTIST-0004",
    "SYNTHETIC-BODY-SERIAL-0005",
    "SYNTHETIC-USER-COMMENT-0006",
    "SYNTHETIC-THUMBNAIL-0007",
    "SYNTHETIC-XMP-CREATOR-0008",
    "SYNTHETIC-XMP-TOOL-0009",
    "SYNTHETIC-DOCUMENT-ID-0010",
    "SYNTHETIC-COMMENT-0011",
    "SYNTHETIC-BYLINE-0012",
    "SYNTHETIC-CITY-0013",
    "SYNTHETIC-ICC-VENDOR-0014",
    "SYNTHETIC-DEVICE-0015",
    "SYNTHETIC-JFIF-THUMB-0016",
    "SYNTHETIC-SECOND-IMAGE-0017",
];

/// Deliberately broken files. Each is a shape a real parser bug would hide behind.
const MALFORMED_FIXTURES: &[&str] = &[
    "malformed/length-past-end.jpg",
    "malformed/length-below-minimum.jpg",
    "malformed/exif-cycle.jpg",
    "malformed/exif-huge-count.jpg",
    "malformed/no-eoi.jpg",
    "malformed/fill-byte-run.jpg",
    "malformed/exif-not-tiff.jpg",
];

#[test]
fn a_malformed_file_is_refused_or_cleaned_but_never_mishandled() {
    // Malformed input is expected input (ADR-0006). The requirement is not that every one of
    // these is refused — a file with a legal-but-unusual run of fill bytes should succeed —
    // but that nothing panics, and that anything reported as a success really is clean.
    for name in MALFORMED_FIXTURES {
        let input = fixture(name);
        let _ = inspect_bytes(&input, &InspectOptions::names_only());
        if let Ok(stripped) = strip_bytes(&input, &StripOptions::default()) {
            let report = inspect_bytes(&stripped.bytes, &InspectOptions::names_only())
                .unwrap_or_else(|e| panic!("{name} stripped to something unparseable: {e}"));
            assert!(
                report.findings.is_empty(),
                "{name} was reported clean but is not"
            );
            let again = strip_bytes(&stripped.bytes, &StripOptions::default()).unwrap();
            assert_eq!(stripped.bytes, again.bytes, "{name} is not idempotent");
        }
    }
}

#[test]
fn every_fixture_is_recognised_as_a_jpeg_by_its_content() {
    for name in ALL_FIXTURES {
        assert_eq!(detect(&fixture(name)).unwrap(), Format::Jpeg, "{name}");
    }
}

#[test]
fn no_synthetic_marker_survives_any_strip() {
    // The assertion that matters, and the one that does not trust strypt's own report: the
    // bytes are simply not there afterwards.
    for name in ALL_FIXTURES {
        let output = strip(name);
        for marker in ALL_MARKERS {
            assert!(
                !contains(&output, marker),
                "{marker} survived stripping {name}"
            );
        }
    }
}

#[test]
fn the_photograph_is_never_re_encoded() {
    // Every fixture is the same base image with different metadata around it, so after
    // stripping, every one must have byte-identical entropy-coded data. This is a stronger
    // check than comparing decoded pixels: identical bytes cannot decode differently, and a
    // re-encode would change them even at a quality setting that looked the same.
    let reference = strip("clean.jpg");
    let expected = entropy(&reference);
    for name in ALL_FIXTURES {
        let output = strip(name);
        assert_eq!(entropy(&output), expected, "{name} re-encoded the image");
    }
}

#[test]
fn stripped_output_inspects_clean() {
    for name in ALL_FIXTURES {
        let output = strip(name);
        let report = inspect_bytes(&output, &InspectOptions::names_only()).unwrap();
        assert!(
            report.findings.is_empty(),
            "{name} still reports {:?} after stripping",
            report.findings
        );
    }
}

#[test]
fn stripping_is_idempotent_byte_for_byte() {
    for name in ALL_FIXTURES {
        let once = strip(name);
        let twice = strip_bytes(&once, &StripOptions::default()).unwrap().bytes;
        assert_eq!(once, twice, "{name} is not idempotent");
    }
}

#[test]
fn a_photograph_reports_its_location_device_and_serial_number_by_name() {
    // "an Exif block was removed" is not useful to someone deciding whether a file they
    // already published is a problem. The field names are.
    let report = inspect_bytes(&fixture("exif-gps.jpg"), &InspectOptions::names_only()).unwrap();
    let fields: Vec<&str> = report
        .findings
        .iter()
        .filter_map(|f| f.field.as_deref())
        .collect();
    for expected in [
        "GPSLatitude",
        "GPSLongitude",
        "Make",
        "Model",
        "BodySerialNumber",
        "DateTimeOriginal",
        "Artist",
    ] {
        assert!(fields.contains(&expected), "{expected} was not reported");
    }
    assert!(
        report
            .findings
            .iter()
            .any(|f| f.kind == MetadataKind::Location)
    );
}

#[test]
fn values_are_withheld_by_default_and_shown_on_request() {
    // A report is easy to redirect into a file, which would recreate the secret the user just
    // asked to have destroyed (docs/THREAT_MODEL.md §5.5).
    let input = fixture("exif-gps.jpg");
    let quiet = inspect_bytes(&input, &InspectOptions::names_only()).unwrap();
    assert!(quiet.findings.iter().all(|f| f.value.is_none()));

    let loud = inspect_bytes(&input, &InspectOptions::with_values()).unwrap();
    assert!(loud.findings.iter().any(|f| f.value.is_some()));
}

#[test]
fn an_embedded_thumbnail_is_removed_whole() {
    // The thumbnail predates any cropping and survives visual redaction of the main image.
    let report = inspect_bytes(
        &fixture("exif-thumbnail.jpg"),
        &InspectOptions::names_only(),
    )
    .unwrap();
    assert!(
        report
            .findings
            .iter()
            .any(|f| f.kind == MetadataKind::Thumbnail)
    );
    assert!(!contains(
        &strip("exif-thumbnail.jpg"),
        "SYNTHETIC-THUMBNAIL"
    ));
}

#[test]
fn a_second_image_hidden_after_the_end_marker_is_removed() {
    let report =
        inspect_bytes(&fixture("trailing-data.jpg"), &InspectOptions::names_only()).unwrap();
    assert!(
        report
            .findings
            .iter()
            .any(|f| f.location == "trailing data after EOI"),
        "data past the end of the image was not reported"
    );
}

#[test]
fn the_jfif_header_survives_and_its_thumbnail_does_not() {
    let stripped = strip_bytes(&fixture("jfif-thumbnail.jpg"), &StripOptions::default()).unwrap();
    assert!(
        stripped
            .report
            .retained
            .iter()
            .any(|r| r.location == "APP0 (JFIF)"),
        "the JFIF header was not kept, or was kept without saying so"
    );
    assert!(
        stripped.bytes.windows(2).any(|w| w == [0xFF, 0xE0]),
        "the APP0 segment is gone entirely"
    );
    assert!(!contains(&stripped.bytes, "SYNTHETIC-JFIF-THUMB"));
}

#[test]
fn the_adobe_colour_marker_is_kept_and_the_report_says_why() {
    // Removing it renders CMYK and YCCK files with wrong colours. Keeping it silently would
    // be the wrong half of the trade.
    let stripped = strip_bytes(&fixture("adobe-marker.jpg"), &StripOptions::default()).unwrap();
    let retained = stripped
        .report
        .retained
        .iter()
        .find(|r| r.location == "APP14 (Adobe)")
        .expect("the Adobe marker was not declared as retained");
    assert_eq!(retained.reason, RetentionReason::RemovalWouldAlterPayload);
    assert!(stripped.bytes.windows(2).any(|w| w == [0xFF, 0xEE]));
}

#[test]
fn a_clean_file_is_reported_clean_and_left_alone() {
    // A tool that invents findings teaches users to ignore it, and a tool that rewrites a file
    // it had nothing to remove from has changed a file for no reason.
    let input = fixture("clean.jpg");
    let report = inspect_bytes(&input, &InspectOptions::names_only()).unwrap();
    assert!(report.findings.is_empty());
    assert_eq!(strip("clean.jpg"), input);
}

#[test]
fn a_truncated_fixture_is_refused_at_every_length() {
    // Fail closed: a damaged file is refused, never completed and handed back as a clean copy.
    for name in ALL_FIXTURES {
        let input = fixture(name);
        for cut in 1..input.len() {
            let prefix = input.get(0..cut).unwrap();
            if let Ok(stripped) = strip_bytes(prefix, &StripOptions::default()) {
                // A prefix that still parses must still be clean, and must still be a JPEG.
                assert_eq!(detect(&stripped.bytes).unwrap(), Format::Jpeg);
                let report = inspect_bytes(&stripped.bytes, &InspectOptions::names_only()).unwrap();
                assert!(report.findings.is_empty(), "{name} truncated at {cut}");
            }
        }
    }
}
