//! End-to-end tests for the JPEG XL handler, over the fixtures in `corpus/jxl`.
//!
//! Each fixture is generated by `corpus/tools/make_jxl_fixtures.py` and documented in
//! `corpus/MANIFEST.md`. The synthetic marker strings — `SYNTHETIC-…-000N` — exist so a test can
//! assert on the *bytes of the output* rather than on strypt's own report: a handler that forgot
//! to remove something would still report having removed it.
//!
//! # Why this file carries its own box walker
//!
//! The claims that matter — that the codestream crossed byte for byte, and that exactly the boxes
//! ADR-0036 names reached the output — are claims about structure, and checking them with the
//! handler's own walker would assert only that the parser agrees with itself. [`boxes`] walks the
//! file independently, as `tests/gif.rs` walks a block sequence.

// Test code is not reachable from untrusted bytes, which is the boundary the panic-freedom
// lints police (ADR-0006).
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing,
    clippy::arithmetic_side_effects
)]

use strypt_core::formats::StripOptions;
use strypt_core::report::{InspectOptions, MetadataKind, Note};
use strypt_core::{Format, detect, inspect_bytes, strip_bytes};

fn fixture(name: &str) -> Vec<u8> {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../corpus/jxl")
        .join(name);
    std::fs::read(&path).unwrap_or_else(|e| panic!("reading fixture {}: {e}", path.display()))
}

fn strip(name: &str) -> Vec<u8> {
    let input = fixture(name);
    strip_bytes(&input, &StripOptions::default())
        .unwrap_or_else(|e| panic!("stripping {name}: {e}"))
        .bytes
}

fn contains(haystack: &[u8], needle: &str) -> bool {
    haystack
        .windows(needle.len())
        .any(|w| w == needle.as_bytes())
}

const FIXTURES: &[&str] = &[
    "clean.jxl",
    "bare-codestream.jxl",
    "exif.jxl",
    "xmp.jxl",
    "jumbf.jxl",
    "brotli-compressed.jxl",
    "jpeg-reconstruction.jxl",
    "frame-index.jxl",
    "padding.jxl",
    "level-and-partial-codestream.jxl",
    "size-zero-final.jxl",
    "metadata-after-codestream.jxl",
    "kitchen-sink.jxl",
];

const MALFORMED: &[&str] = &[
    "malformed/unknown-box.jxl",
    "malformed/no-signature.jxl",
    "malformed/wrong-brand.jxl",
    "malformed/signature-wrong-length.jxl",
    "malformed/box-overruns-file.jxl",
    "malformed/box-size-below-header.jxl",
    "malformed/trailing-data.jxl",
    "malformed/no-codestream.jxl",
];

/// Every top-level box in `data` as `(type, whole bytes)`, found by an independent walk.
///
/// Deliberately written here rather than borrowed from `strypt_core`: see this file's header.
fn boxes(data: &[u8]) -> Vec<([u8; 4], Vec<u8>)> {
    let mut at = 0;
    let mut out = Vec::new();
    while at + 8 <= data.len() {
        let declared =
            usize::try_from(u32::from_be_bytes(data[at..at + 4].try_into().unwrap())).unwrap();
        let kind: [u8; 4] = data[at + 4..at + 8].try_into().unwrap();
        // §4.2: 0 runs to the end of the file, 1 escapes to a 64-bit size.
        let size = match declared {
            0 => data.len() - at,
            1 => usize::try_from(u64::from_be_bytes(
                data[at + 8..at + 16].try_into().unwrap(),
            ))
            .unwrap(),
            n => n,
        };
        assert!(
            size >= 8 && at + size <= data.len(),
            "box {kind:?} overruns"
        );
        out.push((kind, data[at..at + size].to_vec()));
        at += size;
    }
    assert_eq!(at, data.len(), "trailing bytes after the last box");
    out
}

fn types(data: &[u8]) -> Vec<[u8; 4]> {
    boxes(data).into_iter().map(|(kind, _)| kind).collect()
}

#[test]
fn every_fixture_is_detected_as_jpeg_xl() {
    // Both spellings, and the malformed ones too: a file has to be routed here before it can be
    // refused here. Two of the malformed fixtures are excluded because they no longer *are* JPEG
    // XL at the detection layer — one has no signature box and reads as a bare ISO base-media
    // file, the other's signature is the wrong length and matches nothing.
    for name in FIXTURES {
        assert_eq!(
            detect(&fixture(name)).unwrap(),
            Format::Jxl,
            "{name} was not detected as JPEG XL"
        );
    }
    for name in MALFORMED {
        if name.contains("no-signature") || name.contains("signature-wrong-length") {
            continue;
        }
        assert_eq!(
            detect(&fixture(name)).unwrap(),
            Format::Jxl,
            "{name} was not detected as JPEG XL"
        );
    }
}

#[test]
fn no_synthetic_marker_survives_any_fixture() {
    // The sweep: every identifying value in the corpus is a `SYNTHETIC-` marker, so one assertion
    // covers every box at once, including the ones no test below names individually.
    for name in FIXTURES {
        let output = strip(name);
        assert!(
            !contains(&output, "SYNTHETIC"),
            "a synthetic marker survived stripping {name}"
        );
    }
}

#[test]
fn a_clean_file_strips_to_a_byte_identical_copy() {
    // What deletion buys and a rebuild cannot promise (ADR-0036 §3, against ADR-0033's TIFF).
    let input = fixture("clean.jxl");
    let stripped = strip_bytes(&input, &StripOptions::default()).unwrap();
    assert!(stripped.report.removed.is_empty());
    assert_eq!(stripped.bytes, input);
}

#[test]
fn a_bare_codestream_is_accepted_and_returned_unchanged() {
    // ADR-0036 §2: there is no box layer in this spelling, so there is nothing to remove — and
    // the file is not refused either, because the metadata it is being cleared of cannot exist.
    let input = fixture("bare-codestream.jxl");
    let stripped = strip_bytes(&input, &StripOptions::default()).unwrap();
    assert!(stripped.report.removed.is_empty());
    assert_eq!(stripped.bytes, input);
}

#[test]
fn every_report_says_the_codestream_was_not_entered() {
    // The limitation is declared on every file, clean ones included. A verdict that covers the
    // box layer and says so is honest; the same verdict unqualified would not be.
    for name in FIXTURES {
        let report = inspect_bytes(&fixture(name), &InspectOptions::names_only()).unwrap();
        assert!(
            report.notes.iter().any(|note| matches!(
                note,
                Note::OutOfScopeContent { location } if location.contains("codestream")
            )),
            "{name}: no note about the codestream"
        );
    }
}

#[test]
fn the_codestream_crosses_byte_for_byte() {
    // The pixels are never decoded, so every `jxlc` and `jxlp` box must appear in the output
    // exactly as it appeared in the input — same count, same bytes, same order.
    let codestreams = |data: &[u8]| -> Vec<Vec<u8>> {
        boxes(data)
            .into_iter()
            .filter(|(kind, _)| kind == b"jxlc" || kind == b"jxlp")
            .map(|(_, raw)| raw)
            .collect()
    };
    for name in FIXTURES {
        if *name == "bare-codestream.jxl" {
            continue; // No box layer to walk; covered by the byte-identity test above.
        }
        assert_eq!(
            codestreams(&fixture(name)),
            codestreams(&strip(name)),
            "{name}: the codestream did not cross the strip intact"
        );
    }
}

#[test]
fn only_the_allow_listed_boxes_reach_the_output() {
    const KEPT: [[u8; 4]; 5] = [*b"JXL ", *b"ftyp", *b"jxll", *b"jxlc", *b"jxlp"];
    for name in FIXTURES {
        if *name == "bare-codestream.jxl" {
            continue;
        }
        for kind in types(&strip(name)) {
            assert!(
                KEPT.contains(&kind),
                "{name}: {} survived stripping",
                String::from_utf8_lossy(&kind)
            );
        }
    }
}

#[test]
fn the_kitchen_sink_loses_every_metadata_box_and_keeps_the_rest() {
    let after = types(&strip("kitchen-sink.jxl"));
    assert_eq!(after, vec![*b"JXL ", *b"ftyp", *b"jxll", *b"jxlc"]);
}

#[test]
fn a_size_zero_final_box_keeps_its_meaning() {
    // §4.2's "runs to the end of the file". Deletion preserves it because nothing is ever
    // inserted after it — a rewrite would have had to recompute the size.
    let output = strip("size-zero-final.jxl");
    assert_eq!(
        &output[output.len() - 20..output.len() - 16 + 4][..4],
        b"\x00\x00\x00\x00"
    );
    assert_eq!(types(&output), vec![*b"JXL ", *b"ftyp", *b"jxlc"]);
    assert!(!contains(&output, "SYNTHETIC"));
}

#[test]
fn a_brotli_box_is_reported_by_the_type_it_wraps_and_never_inflated() {
    // ADR-0036 §4: the first four bytes name the wrapped box, and that is the whole of what is
    // read. No Brotli decompressor is in this tree, and the fixture's payload is not valid
    // Brotli — which is exactly the point.
    let report = inspect_bytes(
        &fixture("brotli-compressed.jxl"),
        &InspectOptions::names_only(),
    )
    .unwrap();
    let finding = report
        .findings
        .iter()
        .find(|f| f.location.contains("brob"))
        .expect("no finding for the brob box");
    assert_eq!(finding.field.as_deref(), Some("Exif"));
    assert!(!contains(&strip("brotli-compressed.jxl"), "SYNTHETIC"));
}

#[test]
fn removing_the_jpeg_reconstruction_box_is_declared() {
    // Deleting `jbrd` changes what the file can be used for, so the report says so rather than
    // letting the user discover it when a reconstruction fails (ADR-0036 §5).
    let report = inspect_bytes(
        &fixture("jpeg-reconstruction.jxl"),
        &InspectOptions::names_only(),
    )
    .unwrap();
    assert!(
        report
            .notes
            .iter()
            .any(|note| matches!(note, Note::CapabilityRemoved { location, .. } if location.contains("jbrd"))),
        "no note about what removing jbrd costs"
    );
}

#[test]
fn exif_inside_a_box_is_broken_down_by_tag() {
    // The Exif box's payload starts with a four-byte offset to the TIFF header; a scan that
    // missed it would parse the wrong bytes and still look plausible.
    let report = inspect_bytes(&fixture("exif.jxl"), &InspectOptions::names_only()).unwrap();
    let kinds: Vec<_> = report.findings.iter().map(|f| f.kind).collect();
    assert!(kinds.contains(&MetadataKind::PersonalIdentity), "{kinds:?}");
    assert!(kinds.contains(&MetadataKind::DeviceIdentity), "{kinds:?}");
    assert!(kinds.contains(&MetadataKind::Timestamp), "{kinds:?}");
}

#[test]
fn every_malformed_fixture_is_refused() {
    // Fail-closed: none of these produces output. A partly-cleaned JPEG XL is worse than a
    // refusal, because the user acts on the success message by publishing.
    for name in MALFORMED {
        let input = fixture(name);
        let result = detect(&input).and_then(|_| strip_bytes(&input, &StripOptions::default()));
        assert!(result.is_err(), "{name} was not refused");
    }
}

#[test]
fn an_exif_box_that_does_not_parse_is_still_removed() {
    // The one fixture under `malformed/` that is not refused. A block strypt cannot read is still
    // a block it can delete, and deleting it is the safe direction.
    let input = fixture("malformed/exif-offset-past-end.jxl");
    let stripped = strip_bytes(&input, &StripOptions::default()).unwrap();
    assert_eq!(stripped.report.removed.len(), 1);
    assert!(!contains(&stripped.bytes, "SYNTHETIC"));
    assert_eq!(types(&stripped.bytes), vec![*b"JXL ", *b"ftyp", *b"jxlc"]);
}

#[test]
fn the_output_of_every_fixture_re_inspects_clean() {
    // What the pipeline's verification pass does, asserted directly over the corpus.
    for name in FIXTURES {
        let output = strip(name);
        let report = inspect_bytes(&output, &InspectOptions::names_only())
            .unwrap_or_else(|e| panic!("stripped {name} no longer inspects: {e}"));
        assert!(
            report.findings.is_empty(),
            "metadata survived stripping {name}: {:?}",
            report.findings
        );
    }
}

#[test]
fn stripping_is_idempotent_over_the_whole_corpus() {
    for name in FIXTURES {
        let once = strip(name);
        let twice = strip_bytes(&once, &StripOptions::default())
            .unwrap_or_else(|e| panic!("re-stripping {name}: {e}"))
            .bytes;
        assert_eq!(once, twice, "stripping {name} is not idempotent");
    }
}

#[test]
fn inspect_and_strip_agree_about_what_is_in_the_file() {
    // The two entry points share one pass, and this is what that buys: anything `strip` removes
    // is something `inspect` can see, which is the premise the verification pass rests on.
    for name in FIXTURES {
        let input = fixture(name);
        let seen = inspect_bytes(&input, &InspectOptions::names_only()).unwrap();
        let removed = strip_bytes(&input, &StripOptions::default())
            .unwrap()
            .report;
        assert_eq!(
            seen.findings.len(),
            removed.removed.len(),
            "{name}: inspect and strip disagree"
        );
    }
}
