//! End-to-end tests for the MP3 handler, over the fixtures in `corpus/mp3`.
//!
//! Each fixture is generated by `corpus/tools/make_mp3_fixtures.py` and documented in
//! `corpus/MANIFEST.md`. The synthetic marker strings — `SYNTHETIC-…-000N` — exist so a test can
//! assert on the *bytes of the output* rather than on strypt's own report: a handler that forgot
//! to remove something would still report having removed it.
//!
//! # Why this file carries its own frame walker
//!
//! The claims that matter — that the frames crossed byte for byte, and that no tag reached the
//! output — are claims about structure, and checking them with the handler's own reader would
//! assert only that the parser agrees with itself. [`frames`] and [`tag_at_either_end`] walk the
//! file independently, as `tests/wav.rs` walks a chunk list.

// Test code is not reachable from untrusted bytes, which is the boundary the panic-freedom
// lints police (ADR-0006).
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing,
    clippy::arithmetic_side_effects
)]

use strypt_core::error::UnsupportedKind;
use strypt_core::formats::StripOptions;
use strypt_core::report::{InspectOptions, Note, RetentionReason};
use strypt_core::{Format, StryptError, detect, inspect_bytes, strip_bytes};

fn fixture(name: &str) -> Vec<u8> {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../corpus/mp3")
        .join(name);
    std::fs::read(&path).unwrap_or_else(|e| panic!("reading fixture {}: {e}", path.display()))
}

fn malformed(name: &str) -> Vec<u8> {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../corpus/mp3/malformed")
        .join(name);
    std::fs::read(&path).unwrap_or_else(|e| panic!("reading fixture {}: {e}", path.display()))
}

fn strip(name: &str) -> Vec<u8> {
    let input = fixture(name);
    strip_bytes(&input, &StripOptions::default())
        .unwrap_or_else(|e| panic!("stripping {name}: {e}"))
        .bytes
}

fn contains(haystack: &[u8], needle: &str) -> bool {
    haystack
        .windows(needle.len())
        .any(|w| w == needle.as_bytes())
}

const FIXTURES: &[&str] = &[
    "clean.mp3",
    "id3v2-4.mp3",
    "id3v2-3.mp3",
    "id3v2-2.mp3",
    "unsynchronised.mp3",
    "extended-header.mp3",
    "footer.mp3",
    "stacked-tags.mp3",
    "id3v1.mp3",
    "id3v1-extended.mp3",
    "ape.mp3",
    "ape-no-header.mp3",
    "lyrics3v2.mp3",
    "lyrics3v1.mp3",
    "cover-art.mp3",
    "embedded-object.mp3",
    "private-frame.mp3",
    "unknown-frame.mp3",
    "vbr-xing.mp3",
    "vbr-info.mp3",
    "vbr-vbri.mp3",
    "leading-padding.mp3",
    "kitchen-sink.mp3",
];

const MALFORMED: &[&str] = &[
    "truncated.mp3",
    "tag-size-past-end.mp3",
    "non-syncsafe-size.mp3",
    "unknown-major-version.mp3",
    "ape-header-missing.mp3",
    "tail-tag-below-floor.mp3",
    "no-audio.mp3",
    "hidden-before-audio.mp3",
    "layer-two.mp3",
    "reserved-version.mp3",
    "forbidden-bitrate.mp3",
];

/// Refused before dispatch rather than by the handler: both corrupt a frame header field, so no
/// header validates and nothing identifies the file as an MP3. Still fail-closed — nothing is
/// written — but the refusal carries no format name.
const REFUSED_AT_DETECTION: &[&str] = &["reserved-version.mp3", "forbidden-bitrate.mp3"];

/// Every MPEG frame in `data`, as raw byte spans. Written here rather than borrowed from the
/// handler: a check that used the code under test to read its own output would prove nothing.
///
/// The corpus is a single frame geometry — MPEG-1 Layer III, 128 kbps, 44.1 kHz, 417 bytes — so
/// this walks by that stride rather than re-deriving the bitrate table.
fn frames(data: &[u8]) -> Vec<&[u8]> {
    const FRAME_BYTES: usize = 417;
    let mut out = Vec::new();
    let mut at = 0;
    while at + FRAME_BYTES <= data.len() {
        if data[at] != 0xFF || data[at + 1] & 0xE0 != 0xE0 {
            break;
        }
        out.push(&data[at..at + FRAME_BYTES]);
        at += FRAME_BYTES;
    }
    out
}

/// The name of a tag at either end of `data`, if there is one. Independently spelled, and
/// deliberately generous: it only has to notice a marker, not measure a span.
fn tag_at_either_end(data: &[u8]) -> Option<&'static str> {
    if data.starts_with(b"ID3") {
        return Some("ID3v2");
    }
    if data.len() >= 128 && &data[data.len() - 128..data.len() - 125] == b"TAG" {
        return Some("ID3v1");
    }
    if data.len() >= 32 && &data[data.len() - 32..data.len() - 24] == b"APETAGEX" {
        return Some("APE");
    }
    if data.len() >= 9 && matches!(&data[data.len() - 9..], b"LYRICS200" | b"LYRICSEND") {
        return Some("Lyrics3");
    }
    None
}

#[test]
fn every_fixture_is_detected_as_mp3() {
    for name in FIXTURES {
        assert_eq!(detect(&fixture(name)).unwrap(), Format::Mp3, "{name}");
    }
}

#[test]
fn no_synthetic_marker_survives_any_fixture() {
    // The absolute check, independent of what the report claims: every identifying value in the
    // corpus is a marker, so this reads the output bytes rather than strypt's account of them.
    for name in FIXTURES {
        let output = strip(name);
        assert!(
            !contains(&output, "SYNTHETIC-"),
            "a synthetic marker survived {name}"
        );
        assert!(!frames(&output).is_empty(), "{name} lost its audio");
    }
}

#[test]
fn no_tag_reaches_the_output() {
    for name in FIXTURES {
        let output = strip(name);
        assert_eq!(
            tag_at_either_end(&output),
            None,
            "a tag survived {name} at one end"
        );
    }
}

#[test]
fn a_file_with_no_tags_comes_back_byte_identical() {
    // Deletion at both ends, never a rewrite: nothing to remove means nothing to change
    // (ADR-0040). TIFF and HEIF cannot promise this.
    for name in ["clean.mp3", "vbr-xing.mp3", "vbr-info.mp3", "vbr-vbri.mp3"] {
        assert_eq!(strip(name), fixture(name), "{name} was rewritten");
    }
}

#[test]
fn the_frames_cross_byte_for_byte() {
    // The property this handler trades a rebuild for. It is why a re-encoding tool and strypt are
    // different offers rather than the same one twice.
    for name in FIXTURES {
        let input = fixture(name);
        let before = frames(&input);
        let output = strip(name);
        let after = frames(&output);
        assert!(!before.is_empty() || !after.is_empty(), "{name}");
        if !before.is_empty() {
            assert_eq!(before, after, "{name}: the frames were rewritten");
        }
    }
}

#[test]
fn the_encoder_fingerprint_in_a_vbr_frame_is_kept_and_declared() {
    // It is a real frame inside the encoded stream, which Phase 2's audio group never enters
    // (ADR-0037), and the LAME extension behind it names the encoder and its settings. Kept, and
    // said out loud — a keep nobody is told about is a leak with a clean report.
    for (name, marker) in [
        ("vbr-xing.mp3", "Xing"),
        ("vbr-info.mp3", "Info"),
        ("vbr-vbri.mp3", "VBRI"),
    ] {
        let input = fixture(name);
        let report = strip_bytes(&input, &StripOptions::default())
            .unwrap()
            .report;
        let kept = report
            .retained
            .iter()
            .find(|r| r.location.starts_with(marker))
            .unwrap_or_else(|| panic!("{name}: the {marker} header was not declared"));
        assert_eq!(kept.reason, RetentionReason::RemovalWouldAlterPayload);
    }
    assert!(
        contains(&strip("vbr-xing.mp3"), "LAME3.100"),
        "the VBR frame was not copied through"
    );
}

#[test]
fn leading_padding_is_dropped_and_the_size_change_is_accounted_for() {
    let report = strip_bytes(&fixture("leading-padding.mp3"), &StripOptions::default())
        .unwrap()
        .report;
    assert!(
        report
            .removed
            .iter()
            .any(|f| f.location.starts_with("zero padding")),
        "the file shrank without the report saying why"
    );
}

#[test]
fn the_uninspected_frames_are_declared_on_every_fixture() {
    // Said on clean files too: the frames are copied without being decoded, so anything inside one
    // is out of reach rather than absent.
    for name in FIXTURES {
        let notes = inspect_bytes(&fixture(name), &InspectOptions::names_only())
            .unwrap()
            .notes;
        assert!(
            notes.iter().any(|n| matches!(
                n,
                Note::OutOfScopeContent { location } if location.starts_with("audio frames")
            )),
            "{name} said nothing about its frames"
        );
    }
}

#[test]
fn every_malformed_fixture_is_refused() {
    // Fail closed: a file strypt cannot fully account for is refused, never partly cleaned.
    for name in MALFORMED {
        let data = malformed(name);
        let refused = match detect(&data) {
            Ok(_) => strip_bytes(&data, &StripOptions::default()).is_err(),
            // Refused at detection is still refused — but only for the fixtures named above. For
            // any other, `UnrecognisedFormat` means it stopped being an MP3 and never reached the
            // handler, which is a silent hole rather than a pass.
            Err(StryptError::UnrecognisedFormat) => {
                assert!(
                    REFUSED_AT_DETECTION.contains(name),
                    "{name} is no longer recognised as an MP3 — the fixture is broken"
                );
                true
            }
            Err(_) => true,
        };
        assert!(refused, "{name} was accepted");
    }
}

#[test]
fn the_fixtures_refused_at_detection_are_exactly_the_ones_named() {
    // Pins the exception both ways: one drifting into detection's reach, or a new one drifting out
    // of it, is a change to what strypt claims to recognise and should not pass quietly.
    for name in MALFORMED {
        let nameless = matches!(
            detect(&malformed(name)),
            Err(StryptError::UnrecognisedFormat)
        );
        assert_eq!(
            nameless,
            REFUSED_AT_DETECTION.contains(name),
            "{name} changed which stage refuses it"
        );
    }
}

#[test]
fn mpeg_audio_that_is_not_layer_three_is_refused_by_name() {
    // "Unrecognised" would be untrue and unhelpful for a file most tools would call an MP3.
    match strip_bytes(&malformed("layer-two.mp3"), &StripOptions::default()) {
        Err(StryptError::UnsupportedFormat { format }) => {
            assert_eq!(format, UnsupportedKind::MpegAudioNotLayerThree);
        }
        other => panic!("layer-two.mp3 was not named: {other:?}"),
    }
}

#[test]
fn output_re_inspects_clean() {
    // The verification pass's own claim, asserted directly: nothing `strip` removed is something
    // `inspect` can still find.
    for name in FIXTURES {
        let report = inspect_bytes(&strip(name), &InspectOptions::names_only()).unwrap();
        assert!(
            report.findings.is_empty(),
            "metadata survived {name}: {:?}",
            report.findings
        );
    }
}

#[test]
fn stripping_is_idempotent_over_the_corpus() {
    for name in FIXTURES {
        let once = strip(name);
        let twice = strip_bytes(&once, &StripOptions::default()).unwrap().bytes;
        assert_eq!(once, twice, "strip is not idempotent for {name}");
    }
}

#[test]
fn inspect_and_strip_agree_on_what_is_there() {
    for name in FIXTURES {
        let input = fixture(name);
        let seen = inspect_bytes(&input, &InspectOptions::names_only())
            .unwrap()
            .findings;
        let removed = strip_bytes(&input, &StripOptions::default())
            .unwrap()
            .report
            .removed;
        assert_eq!(
            seen.len(),
            removed.len(),
            "{name}: show and strip disagree about what is in the file"
        );
    }
}

#[test]
fn stripping_never_grows_a_fixture() {
    // Deletion only: output larger than input would mean bytes were synthesised.
    for name in FIXTURES {
        assert!(strip(name).len() <= fixture(name).len(), "{name} grew");
    }
}

#[test]
fn truncating_any_fixture_anywhere_never_panics() {
    for name in FIXTURES {
        let input = fixture(name);
        for n in 0..=input.len() {
            let prefix = &input[0..n];
            let _ = inspect_bytes(prefix, &InspectOptions::names_only());
            let _ = strip_bytes(prefix, &StripOptions::default());
        }
    }
}

#[test]
fn flipping_any_single_byte_never_panics() {
    // Cheap structural mutation, over the whole corpus. The fuzz target explores much further;
    // this keeps the property under `cargo test` where it cannot be forgotten.
    for name in FIXTURES {
        let input = fixture(name);
        for at in 0..input.len() {
            let mut mutated = input.clone();
            mutated[at] ^= 0xFF;
            let _ = inspect_bytes(&mutated, &InspectOptions::names_only());
            let _ = strip_bytes(&mutated, &StripOptions::default());
        }
    }
}
