//! End-to-end tests for the MP4 / M4A handler, over the fixtures in `corpus/mp4`.
//!
//! Each fixture is generated by `corpus/tools/make_mp4_fixtures.py` and documented in
//! `corpus/MANIFEST.md`. The synthetic marker strings — `SYNTHETIC-…-000N` — exist so a test can
//! assert on the *bytes of the output* rather than on strypt's own report: a handler that forgot
//! to remove something would still report having removed it.
//!
//! # Why this file carries its own box walker
//!
//! An MP4 is edited by deletion, and the whole safety argument is the chunk offset table: every
//! entry must still point at the same media byte after boxes in front of `mdat` are gone
//! (ADR-0042 decision 2). Checking that with the handler's own walker would assert only that the
//! parser agrees with itself, so [`walk`] reads the tree from scratch, as `tests/ogg.rs` reads a
//! page sequence.

// Test code is not reachable from untrusted bytes, which is the boundary the panic-freedom lints
// police (ADR-0006).
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing,
    clippy::arithmetic_side_effects
)]

use strypt_core::error::{MalformedDetail, UnsupportedKind};
use strypt_core::formats::StripOptions;
use strypt_core::report::{InspectOptions, Note, RetentionReason};
use strypt_core::{Format, StryptError, detect, inspect_bytes, strip_bytes};

fn fixture(name: &str) -> Vec<u8> {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../corpus/mp4")
        .join(name);
    std::fs::read(&path).unwrap_or_else(|e| panic!("reading fixture {}: {e}", path.display()))
}

fn malformed(name: &str) -> Vec<u8> {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../corpus/mp4/malformed")
        .join(name);
    std::fs::read(&path).unwrap_or_else(|e| panic!("reading fixture {}: {e}", path.display()))
}

fn strip(name: &str) -> Vec<u8> {
    let input = fixture(name);
    strip_bytes(&input, &StripOptions::default())
        .unwrap_or_else(|e| panic!("stripping {name}: {e}"))
        .bytes
}

fn contains(haystack: &[u8], needle: &str) -> bool {
    haystack
        .windows(needle.len())
        .any(|w| w == needle.as_bytes())
}

const FIXTURES: &[(&str, Format)] = &[
    ("clean.mp4", Format::Mp4),
    ("clean.m4a", Format::M4a),
    ("video-tags.mp4", Format::Mp4),
    ("itunes-tags.m4a", Format::M4a),
    ("xmp-uuid.mp4", Format::Mp4),
    ("free-space.mp4", Format::Mp4),
    ("faststart.mp4", Format::Mp4),
    ("sixty-four-bit-mdat.mp4", Format::Mp4),
    ("timestamps.mp4", Format::Mp4),
    ("unknown-boxes.mp4", Format::Mp4),
];

const MALFORMED: &[&str] = &[
    "fragmented.mp4",
    "fragmented-brand.mp4",
    "movie-extends.mp4",
    "encrypted-sample-entry.mp4",
    "protection-system.mp4",
    "protected.m4a",
    "chunk-offset-into-free.mp4",
    "chunk-offset-past-end.mp4",
    "external-data-reference.mp4",
    "no-movie-box.mp4",
    "two-movie-boxes.mp4",
    "no-track.mp4",
    "truncated.mp4",
    "quicktime.mov",
    "three-gpp.mp4",
];

/// One box, as this file reads it.
#[derive(Debug, Clone)]
struct Atom {
    /// Slash-separated types from the root, this box included.
    path: String,
    typ: [u8; 4],
    /// Where the box starts in the file.
    start: usize,
    /// 8, or 16 for §4.2's 64-bit size escape.
    header: usize,
    payload: Vec<u8>,
}

/// Boxes this walker descends into. `meta` is a full box, so its children start four bytes late.
const CONTAINERS: &[&[u8; 4]] = &[
    b"moov", b"trak", b"mdia", b"minf", b"stbl", b"udta", b"edts", b"dinf", b"ilst", b"meta",
];

/// Every box in `data`, depth first, refusing anything that is not exactly a run of boxes.
///
/// Written here rather than borrowed from the handler: a check that used the code under test to
/// read its own output would prove nothing.
fn walk(data: &[u8]) -> Vec<Atom> {
    let mut out = Vec::new();
    descend(data, 0, "", &mut out);
    assert!(!out.is_empty(), "no boxes");
    out
}

fn descend(data: &[u8], base: usize, prefix: &str, out: &mut Vec<Atom>) {
    let mut at = 0;
    while at < data.len() {
        assert!(
            at + 8 <= data.len(),
            "a box header runs off the end at {at}"
        );
        let declared = u32::from_be_bytes(data[at..at + 4].try_into().unwrap()) as usize;
        let typ: [u8; 4] = data[at + 4..at + 8].try_into().unwrap();
        let (size, header) = match declared {
            1 => {
                assert!(at + 16 <= data.len(), "a 64-bit size runs off the end");
                let wide = usize::try_from(u64::from_be_bytes(
                    data[at + 8..at + 16].try_into().unwrap(),
                ))
                .unwrap();
                (wide, 16)
            }
            0 => (data.len() - at, 8),
            n => {
                assert!(n >= 8, "a box declares {n} bytes at {at}");
                (n, 8)
            }
        };
        assert!(at + size <= data.len(), "a box overruns the file at {at}");
        let payload = data[at + header..at + size].to_vec();
        let path = format!("{prefix}/{}", String::from_utf8_lossy(&typ));
        out.push(Atom {
            path: path.clone(),
            typ,
            start: base + at,
            header,
            payload: payload.clone(),
        });
        if CONTAINERS.contains(&&typ) {
            let skip = usize::from(&typ == b"meta") * 4;
            descend(&payload[skip..], base + at + header + skip, &path, out);
        }
        at += size;
    }
}

/// Every `mdat` payload's file range, in file order.
fn mdat_extents(atoms: &[Atom]) -> Vec<(usize, usize)> {
    atoms
        .iter()
        .filter(|a| &a.typ == b"mdat")
        .map(|a| (a.start + a.header, a.start + a.header + a.payload.len()))
        .collect()
}

/// Every chunk offset in the file, resolved to `(which mdat, how far into it)`.
///
/// Panics if an offset lands outside every `mdat` — which is exactly what strypt refuses rather
/// than writes, so on the output side that panic *is* the assertion.
fn chunk_positions(data: &[u8]) -> Vec<(usize, usize)> {
    let atoms = walk(data);
    let extents = mdat_extents(&atoms);
    let mut out = Vec::new();
    for atom in atoms
        .iter()
        .filter(|a| &a.typ == b"stco" || &a.typ == b"co64")
    {
        let wide = &atom.typ == b"co64";
        let width = if wide { 8 } else { 4 };
        let count = u32::from_be_bytes(atom.payload[4..8].try_into().unwrap()) as usize;
        for i in 0..count {
            let at = 8 + i * width;
            let offset = if wide {
                usize::try_from(u64::from_be_bytes(
                    atom.payload[at..at + 8].try_into().unwrap(),
                ))
                .unwrap()
            } else {
                u32::from_be_bytes(atom.payload[at..at + 4].try_into().unwrap()) as usize
            };
            let which = extents
                .iter()
                .position(|(s, e)| offset >= *s && offset < *e)
                .unwrap_or_else(|| panic!("chunk offset {offset} lands in no mdat"));
            out.push((which, offset - extents[which].0));
        }
    }
    assert!(!out.is_empty(), "no chunk offsets");
    out
}

fn find(atoms: &[Atom], typ: [u8; 4]) -> Vec<&Atom> {
    atoms.iter().filter(|a| a.typ == typ).collect()
}

#[test]
fn every_fixture_is_detected_as_the_brand_family_it_declares() {
    for (name, format) in FIXTURES {
        assert_eq!(detect(&fixture(name)).unwrap(), *format, "{name}");
    }
}

#[test]
fn no_synthetic_marker_survives_any_fixture() {
    // The absolute check, independent of what the report claims: every identifying value in the
    // corpus is a marker, so this reads the output bytes rather than strypt's account of them.
    for (name, _) in FIXTURES {
        assert!(
            !contains(&strip(name), "SYNTHETIC-"),
            "a synthetic marker survived {name}"
        );
    }
}

#[test]
fn the_media_crosses_byte_for_byte() {
    // The property edit-by-deletion is chosen for (ADR-0042 decision 1): the samples are copied,
    // never re-encoded, so a stripped file and its original decode to the same audio and video.
    for (name, _) in FIXTURES {
        let before: Vec<Vec<u8>> = walk(&fixture(name))
            .iter()
            .filter(|a| &a.typ == b"mdat")
            .map(|a| a.payload.clone())
            .collect();
        let after: Vec<Vec<u8>> = walk(&strip(name))
            .iter()
            .filter(|a| &a.typ == b"mdat")
            .map(|a| a.payload.clone())
            .collect();
        assert_eq!(before, after, "{name}: the media was rewritten");
    }
}

#[test]
fn every_chunk_offset_still_points_at_the_same_media_byte() {
    // The whole safety argument. Removing a box in front of `mdat` moves the media, so each entry
    // is remapped through the extent table; an entry that resolved to byte N of the first `mdat`
    // before must resolve to byte N of the first `mdat` after.
    for (name, _) in FIXTURES {
        let before = chunk_positions(&fixture(name));
        let after = chunk_positions(&strip(name));
        assert_eq!(before, after, "{name}: a chunk offset moved");
    }
}

#[test]
fn the_removal_actually_moved_something_in_at_least_one_fixture() {
    // Guards the test above from passing vacuously: if no fixture ever shifted its `mdat`, the
    // relocation path would be untested and the assertion would be about nothing.
    let shifted = FIXTURES.iter().any(|(name, _)| {
        let before = mdat_extents(&walk(&fixture(name)));
        let after = mdat_extents(&walk(&strip(name)));
        before != after
    });
    assert!(shifted, "no fixture exercises the relocation table");
}

#[test]
fn nothing_outside_the_allow_lists_reaches_the_output() {
    // `udta`, `meta`, `uuid` and free space are where every producer parks identifying material.
    for (name, _) in FIXTURES {
        for atom in walk(&strip(name)) {
            let banned: &[&[u8; 4]] = &[
                b"udta", b"meta", b"ilst", b"uuid", b"free", b"skip", b"wide", b"iods", b"Xtra",
            ];
            assert!(
                !banned.contains(&&atom.typ),
                "{name}: {} survived",
                atom.path
            );
        }
    }
}

#[test]
fn the_header_boxes_come_back_dateless_and_language_free() {
    // These three cannot be dropped — a file without them is not playable — so they are edited in
    // place instead (ADR-0042 decision 9).
    for (name, _) in FIXTURES {
        let out = strip(name);
        for atom in walk(&out) {
            let version = atom.payload[0];
            match &atom.typ {
                b"mvhd" | b"tkhd" | b"mdhd" => {
                    let width = if version == 1 { 8 } else { 4 };
                    assert!(
                        atom.payload[4..4 + width * 2].iter().all(|b| *b == 0),
                        "{name}: {} kept a timestamp",
                        atom.path
                    );
                }
                _ => {}
            }
            if &atom.typ == b"mdhd" {
                let at = if version == 1 { 32 } else { 20 };
                assert_eq!(
                    &atom.payload[at..at + 2],
                    // ISO 639-2/T `und`, packed five bits per letter (§8.4.2.3).
                    &[0x55, 0xC4],
                    "{name}: the media language survived"
                );
            }
            if &atom.typ == b"mvhd" {
                let at = if version == 1 { 84 } else { 72 };
                assert!(
                    atom.payload[at..at + 24].iter().all(|b| *b == 0),
                    "{name}: mvhd's pre_defined block survived"
                );
            }
            if &atom.typ == b"hdlr" {
                // §8.4.3's trailing name: a producer's own string, and the one place `hdlr` says
                // anything about who wrote the file.
                assert!(
                    atom.payload.len() <= 25 && atom.payload[24..].iter().all(|b| *b == 0),
                    "{name}: a handler name survived"
                );
            }
        }
    }
}

#[test]
fn the_encoder_name_in_a_video_sample_entry_does_not_survive() {
    // §12.1.3's `compressorname`: the one field strypt reads inside a sample entry, because it is
    // at a fixed offset, names the encoding software, and nothing decodes it.
    let carrier = "video-tags.mp4";
    let entry = |data: &[u8]| -> Vec<u8> {
        let atoms = walk(data);
        let stsd = find(&atoms, *b"stsd")[0];
        stsd.payload[8 + 8 + 42..8 + 8 + 74].to_vec()
    };
    assert!(
        entry(&fixture(carrier)).iter().any(|b| *b != 0),
        "the fixture cannot show this"
    );
    assert!(
        entry(&strip(carrier)).iter().all(|b| *b == 0),
        "the encoder name survived"
    );
    // An audio track has no such field, and reading one out of an `mp4a` entry would be reading
    // whatever happens to sit at that offset.
    assert_eq!(strip("itunes-tags.m4a"), fixture("clean.m4a"));
}

#[test]
fn a_sixty_four_bit_mdat_keeps_the_header_form_it_arrived_in() {
    // Rewriting it short would move the payload without moving the offsets that point into it.
    let name = "sixty-four-bit-mdat.mp4";
    assert_eq!(
        find(&walk(&fixture(name)), *b"mdat")[0].header,
        16,
        "the fixture cannot show this"
    );
    assert_eq!(find(&walk(&strip(name)), *b"mdat")[0].header, 16);
}

#[test]
fn a_faststart_file_keeps_its_layout() {
    // `moov` in front of `mdat` is the layout a file gets before it is streamed, and it is the one
    // where dropping a box really does move the media.
    let out = strip("faststart.mp4");
    let atoms = walk(&out);
    let moov = atoms.iter().position(|a| &a.typ == b"moov").unwrap();
    let mdat = atoms.iter().position(|a| &a.typ == b"mdat").unwrap();
    assert!(moov < mdat, "the faststart layout was reordered");
}

#[test]
fn a_clean_file_comes_back_byte_identical() {
    // Edit-by-deletion's other consequence: with nothing to remove there is nothing to write, and
    // a user re-running strypt over an already-clean file gets their own bytes back.
    for name in ["clean.mp4", "clean.m4a"] {
        assert_eq!(strip(name), fixture(name), "{name} was rewritten");
    }
}

#[test]
fn stripping_is_idempotent() {
    for (name, _) in FIXTURES {
        let once = strip(name);
        let twice = strip_bytes(&once, &StripOptions::default()).unwrap().bytes;
        assert_eq!(once, twice, "{name}");
    }
}

#[test]
fn the_codec_configuration_is_declared_as_kept() {
    // `stsd` stays because the samples cannot be decoded without it; saying so is the difference
    // between "we removed everything" and an honest account (ADR-0042 decision 8).
    for (name, _) in FIXTURES {
        let retained = strip_bytes(&fixture(name), &StripOptions::default())
            .unwrap()
            .report
            .retained;
        assert!(
            retained
                .iter()
                .any(|r| r.reason == RetentionReason::StructurallyRequired
                    && r.location.contains("stsd")),
            "{name} kept its sample descriptions without declaring them"
        );
    }
}

#[test]
fn the_uninspected_samples_are_declared_on_every_fixture() {
    // Said on clean files too: the samples are copied without being decoded, so an encoder string
    // in H.264 SEI user data is out of reach rather than absent.
    for (name, _) in FIXTURES {
        let notes = inspect_bytes(&fixture(name), &InspectOptions::names_only())
            .unwrap()
            .notes;
        assert!(
            notes.iter().any(|n| matches!(
                n,
                Note::OutOfScopeContent { location } if location.starts_with("coded samples")
            )),
            "{name} said nothing about its samples"
        );
    }
}

#[test]
fn every_malformed_fixture_is_refused() {
    // Fail closed: a file strypt cannot fully account for is refused, never partly cleaned.
    for name in MALFORMED {
        let data = malformed(name);
        let refused = match detect(&data) {
            Ok(_) => strip_bytes(&data, &StripOptions::default()).is_err(),
            // A refusal *by name* is the outcome this asserts. `UnrecognisedFormat` is not: it means
            // the fixture stopped being an MP4 and never reached the handler at all, which is a
            // silent hole rather than a pass — three fixtures went undetected that way on
            // 2026-09-04 with the whole suite still green.
            Err(StryptError::UnrecognisedFormat) => {
                panic!("{name} is no longer recognised as an MP4 — the fixture is broken")
            }
            Err(_) => true,
        };
        assert!(refused, "{name} was accepted");
    }
}

#[test]
fn the_files_that_do_not_land_here_are_refused_by_name() {
    // "Unrecognised" would be untrue and unhelpful for a file every player calls an MP4.
    for (name, expected) in [
        ("fragmented.mp4", UnsupportedKind::FragmentedMp4),
        ("fragmented-brand.mp4", UnsupportedKind::FragmentedMp4),
        ("movie-extends.mp4", UnsupportedKind::FragmentedMp4),
        (
            "encrypted-sample-entry.mp4",
            UnsupportedKind::ProtectedMedia,
        ),
        ("protection-system.mp4", UnsupportedKind::ProtectedMedia),
        ("protected.m4a", UnsupportedKind::ProtectedMedia),
        ("quicktime.mov", UnsupportedKind::QuickTimeMovie),
        ("three-gpp.mp4", UnsupportedKind::ThirdGenerationPartnership),
    ] {
        match strip_bytes(&malformed(name), &StripOptions::default()) {
            Err(StryptError::UnsupportedFormat { format }) => {
                assert_eq!(format, expected, "{name}");
            }
            other => panic!("{name} was not named: {other:?}"),
        }
    }
}

#[test]
fn an_unresolvable_chunk_offset_refuses_the_file_rather_than_guessing() {
    // The alternative — shifting every offset by the number of bytes removed — silently produces a
    // playable-looking file whose chunks are wrong, which is the failure mode fail-closed exists
    // for (ADR-0042 decision 2).
    for name in ["chunk-offset-into-free.mp4", "chunk-offset-past-end.mp4"] {
        match strip_bytes(&malformed(name), &StripOptions::default()) {
            Err(StryptError::Malformed { detail, .. }) => {
                assert_eq!(detail, MalformedDetail::BrokenIndex, "{name}");
            }
            other => panic!("{name} was not refused as a broken index: {other:?}"),
        }
    }
}

#[test]
fn output_re_inspects_clean() {
    // The verification pass's own claim, asserted directly: nothing `strip` removed is something
    // `inspect` can still find.
    for (name, _) in FIXTURES {
        let report = inspect_bytes(&strip(name), &InspectOptions::names_only()).unwrap();
        assert!(
            report.findings.is_empty(),
            "metadata survived {name}: {:?}",
            report.findings
        );
    }
}
