//! End-to-end tests for the `OpenDocument` handler, over the fixtures in `corpus/odf`.
//!
//! Each fixture is generated by `corpus/tools/make_odf_fixtures.py` and documented in
//! `corpus/MANIFEST.md`. The synthetic marker strings — `SYNTHETIC-…-000N` — exist so that a
//! test can assert on the *bytes of the output* rather than on strypt's own report. That
//! distinction is the point: a handler that forgot to remove something would still happily
//! report having removed it.
//!
//! The `PRESERVED-…` markers are the mirror image. They are the document's own words — the text
//! of a tracked insertion, the body of a comment — and a test that only checked for absence
//! would pass just as well if the handler had deleted the document's contents (ADR-0031).
//!
//! The archive is read back by an independent reader in [`common`], never by strypt's own.

// Test code is not reachable from untrusted bytes, which is the boundary the panic-freedom
// lints police (ADR-0006).
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing,
    clippy::arithmetic_side_effects
)]

mod common;

use common::{between_all, contains, read_archive, unzip};

use strypt_core::error::UnsupportedKind;
use strypt_core::formats::StripOptions;
use strypt_core::report::{InspectOptions, MetadataKind, Note};
use strypt_core::{Format, StryptError, detect, inspect_bytes, strip_bytes};

fn fixture(name: &str) -> Vec<u8> {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../corpus/odf")
        .join(name);
    std::fs::read(&path).unwrap_or_else(|e| panic!("reading fixture {}: {e}", path.display()))
}

fn malformed(name: &str) -> Vec<u8> {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../corpus/odf/malformed")
        .join(name);
    std::fs::read(&path).unwrap_or_else(|e| panic!("reading fixture {}: {e}", path.display()))
}

fn strip(name: &str) -> Vec<u8> {
    let input = fixture(name);
    strip_bytes(&input, &StripOptions::default())
        .unwrap_or_else(|e| panic!("stripping {name}: {e}"))
        .bytes
}

fn text_of(data: &[u8], part: &str) -> String {
    let entries = unzip(data);
    let bytes = entries
        .get(part)
        .unwrap_or_else(|| panic!("{part} is not in the package"));
    String::from_utf8_lossy(bytes).into_owned()
}

/// Every valid fixture, which is every file directly in `corpus/odf`.
fn all_fixtures() -> Vec<String> {
    let dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../corpus/odf");
    let mut names: Vec<String> = std::fs::read_dir(&dir)
        .unwrap()
        .filter_map(|entry| {
            let entry = entry.ok()?;
            entry.file_type().ok()?.is_file().then_some(())?;
            Some(entry.file_name().to_string_lossy().into_owned())
        })
        .collect();
    names.sort();
    assert!(!names.is_empty(), "the fixture directory is empty");
    names
}

/// The malformed fixtures, every one of which must be refused.
fn malformed_fixtures() -> Vec<std::path::PathBuf> {
    let dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../corpus/odf/malformed");
    let mut paths: Vec<_> = std::fs::read_dir(&dir)
        .unwrap()
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.is_file())
        .collect();
    paths.sort();
    paths
}

// ---------------------------------------------------------------------------------------------
// Detection
// ---------------------------------------------------------------------------------------------

#[test]
fn each_package_is_detected_by_the_media_type_it_declares() {
    // Not by extension, and not by searching the raw bytes: `content.xml` appears in every ODF
    // package and in every archive that merely contains one.
    assert_eq!(detect(&fixture("clean.odt")).unwrap(), Format::Odt);
    assert_eq!(detect(&fixture("spreadsheet.ods")).unwrap(), Format::Ods);
    assert_eq!(detect(&fixture("presentation.odp")).unwrap(), Format::Odp);
}

#[test]
fn an_opendocument_type_outside_this_group_is_named_in_its_refusal() {
    // A drawing is understood and declined, which is a different message from "this file was not
    // recognised". `docs/ROADMAP.md` Phase 2 group 2 is the three document types (ADR-0027).
    assert!(matches!(
        detect(&malformed("drawing.odg")),
        Err(StryptError::UnsupportedFormat {
            format: UnsupportedKind::OtherOpenDocument
        })
    ));
}

#[test]
fn a_package_whose_mimetype_entry_is_neither_first_nor_stored_is_still_recognised() {
    // ODF 1.3 Part 2 §3.3 requires both, and a producer that got it wrong has still handed the
    // user an ordinary document. Detection reads the manifest when the mimetype entry is not
    // where it should be.
    assert_eq!(
        detect(&fixture("nonconforming-mimetype.odt")).unwrap(),
        Format::Odt
    );
}

// ---------------------------------------------------------------------------------------------
// The invariants that apply to every fixture
// ---------------------------------------------------------------------------------------------

#[test]
fn no_synthetic_marker_survives_any_fixture() {
    // The assertion that matters most, and the one that does not trust strypt's own report.
    for name in all_fixtures() {
        let stripped = strip(&name);
        assert!(
            !contains(&stripped, "SYNTHETIC-"),
            "a synthetic marker survived stripping {name}"
        );
    }
}

#[test]
fn stripping_is_byte_identically_idempotent() {
    // docs/TESTING_STRATEGY.md §1, invariant 3. For this format it is also what proves the
    // `mimetype` reordering settles: an entry that moved on the first pass must not move again.
    for name in all_fixtures() {
        let once = strip(&name);
        let twice = strip_bytes(&once, &StripOptions::default()).unwrap().bytes;
        assert_eq!(once, twice, "stripping {name} is not idempotent");
    }
}

#[test]
fn stripping_is_deterministic_for_every_fixture() {
    for name in all_fixtures() {
        assert_eq!(
            strip(&name),
            strip(&name),
            "{name} strips differently twice"
        );
    }
}

#[test]
fn stripped_output_inspects_clean() {
    // Phase 1 exit criterion 5, applied to this format.
    for name in all_fixtures() {
        let stripped = strip(&name);
        let report = inspect_bytes(&stripped, &InspectOptions::names_only()).unwrap();
        assert!(
            report.findings.is_empty(),
            "{name} still reports findings after stripping: {:?}",
            report.findings
        );
    }
}

#[test]
fn every_output_is_a_conforming_package() {
    // ODF 1.3 Part 2 §3.3: the `mimetype` entry shall be first, shall not be compressed, and
    // shall carry no extra field. A reader that identifies the format from the first entry
    // depends on all three, so an output that got them wrong would be a document some
    // applications no longer recognise.
    for name in all_fixtures() {
        let entries = read_archive(&strip(&name));
        let mimetype = entries
            .get("mimetype")
            .unwrap_or_else(|| panic!("{name} lost its mimetype entry"));
        assert_eq!(mimetype.index, 0, "{name}: mimetype is not the first entry");
        assert_eq!(mimetype.method, 0, "{name}: mimetype is compressed");
        assert_eq!(
            mimetype.local_extra_len, 0,
            "{name}: mimetype carries an extra field"
        );
        assert!(
            entries.contains_key("META-INF/manifest.xml"),
            "{name} lost the part that makes it a package"
        );
    }
}

#[test]
fn a_nonconforming_mimetype_entry_is_made_conforming() {
    // The input's is deflated and written last. Both are repaired, which is the one place this
    // handler reorders anything — and the narrowest change available, since the alternative is
    // emitting a package that violates the clause every ODF reader identifies the format with.
    let input = read_archive(&fixture("nonconforming-mimetype.odt"));
    assert_ne!(
        input["mimetype"].index, 0,
        "the fixture must be the bad case"
    );
    assert_eq!(input["mimetype"].method, 8, "the fixture must be deflated");

    let out = read_archive(&strip("nonconforming-mimetype.odt"));
    assert_eq!(out["mimetype"].index, 0);
    assert_eq!(out["mimetype"].method, 0);
    assert_eq!(
        out["mimetype"].contents, b"application/vnd.oasis.opendocument.text",
        "the declaration itself must not change"
    );
}

#[test]
fn nothing_in_the_manifest_refers_to_a_part_that_is_no_longer_there() {
    // A manifest listing parts that are not in the package is not a valid package, and an
    // application asked to open one may offer to repair it — for a user trying not to draw
    // attention to a document, a worse outcome than a slightly larger file (ADR-0031).
    for name in all_fixtures() {
        let entries = unzip(&strip(&name));
        let manifest = String::from_utf8_lossy(&entries["META-INF/manifest.xml"]).into_owned();
        for declared in between_all(&manifest, "manifest:full-path=\"", "\"") {
            if declared == "/" {
                continue;
            }
            assert!(
                entries.contains_key(&declared)
                    // A directory entry may be declared without a ZIP directory marker.
                    || declared.ends_with('/')
                        && entries.keys().any(|k| k.starts_with(&declared)),
                "{name}: the manifest declares {declared}, which is not in the package"
            );
        }
    }
}

// ---------------------------------------------------------------------------------------------
// What must be removed
// ---------------------------------------------------------------------------------------------

#[test]
fn the_metadata_part_is_removed_whole() {
    let entries = unzip(&strip("meta.odt"));
    assert!(!entries.contains_key("meta.xml"), "meta.xml survived");
}

#[test]
fn the_editing_statistics_odf_records_are_found_and_named() {
    // `meta:editing-duration` is the field with no Office counterpart worth calling equivalent:
    // `TotalTime` is cumulative minutes, and this is an ISO 8601 duration written to the second.
    // With `meta:creation-date` and `dc:date` beside it, that reconstructs a working session.
    let report = inspect_bytes(&fixture("meta.odt"), &InspectOptions::names_only()).unwrap();
    let fields: Vec<&str> = report
        .findings
        .iter()
        .filter_map(|f| f.field.as_deref())
        .collect();
    for expected in [
        "meta:editing-cycles",
        "meta:editing-duration",
        "meta:initial-creator",
        "meta:generator",
        // Attributes rather than element text, which is exactly where the Office reporting path
        // does not transfer.
        "meta:page-count",
        "meta:word-count",
        "meta:template xlink:href",
    ] {
        assert!(
            fields.contains(&expected),
            "{expected} was not reported; got {fields:?}"
        );
    }
    assert!(
        fields.iter().any(|f| f.starts_with("meta:user-defined (")),
        "a user-defined property must be named, not counted"
    );
}

#[test]
fn the_settings_part_is_removed_and_its_printer_is_named() {
    let entries = unzip(&strip("settings.odt"));
    assert!(
        !entries.contains_key("settings.xml"),
        "settings.xml survived"
    );

    let report = inspect_bytes(&fixture("settings.odt"), &InspectOptions::names_only()).unwrap();
    assert!(
        report
            .findings
            .iter()
            .any(|f| f.kind == MetadataKind::DeviceIdentity
                && f.field.as_deref() == Some("config:config-item (PrinterName)")),
        "the printer name is the reason this part is removed rather than scrubbed"
    );
}

#[test]
fn the_package_thumbnail_is_removed() {
    // It is a rendered preview of the first page (Part 2 §3.8), and it survives every kind of
    // redaction applied to the text — the same way an Exif thumbnail survives cropping.
    let entries = unzip(&strip("thumbnail.odt"));
    assert!(!entries.contains_key("Thumbnails/thumbnail.png"));

    let report = inspect_bytes(&fixture("thumbnail.odt"), &InspectOptions::names_only()).unwrap();
    assert!(
        report
            .findings
            .iter()
            .any(|f| f.kind == MetadataKind::Thumbnail),
        "the thumbnail must be reported as a thumbnail, not as an anonymous part"
    );
}

#[test]
fn the_producers_configuration_and_layout_cache_are_removed() {
    let entries = unzip(&strip("configurations.odt"));
    assert!(
        !entries
            .keys()
            .any(|name| name.starts_with("Configurations2/")),
        "the saved user-interface configuration survived"
    );
    assert!(!entries.contains_key("layout-cache"));
}

#[test]
fn a_comment_loses_its_author_and_keeps_its_words() {
    // The user is told the comment is there and left to decide, which is the same position
    // strypt takes on text under a redaction rectangle (docs/THREAT_MODEL.md §4.3).
    let report = inspect_bytes(&fixture("comments.odt"), &InspectOptions::names_only()).unwrap();
    assert!(
        report
            .notes
            .iter()
            .any(|n| matches!(n, Note::OutOfScopeContent { .. })),
        "a document with comments in it must say so"
    );

    let content = text_of(&strip("comments.odt"), "content.xml");
    assert!(!content.contains("SYNTHETIC-COMMENTER-0015"));
    assert!(!content.contains("2021-03-04T05:06:09"));
    assert!(content.contains("PRESERVED-COMMENT-TEXT"));
    assert!(
        content.contains("<office:annotation>"),
        "the comment itself stays; only its attribution goes"
    );
}

#[test]
fn a_tracked_change_loses_its_author_and_keeps_its_words() {
    // The hardest call in ADR-0030, inherited here. Removing a tracked insertion means deciding
    // whether the document accepts or rejects it, which changes what the document says.
    let content = text_of(&strip("tracked-changes.odt"), "content.xml");
    assert!(!content.contains("SYNTHETIC-INSERTER-0017"));
    assert!(!content.contains("SYNTHETIC-DELETER-0018"));
    assert!(content.contains("PRESERVED-INSERTED-TEXT"));
    assert!(content.contains("PRESERVED-DELETED-TEXT"));
    assert!(
        content.contains("<text:insertion>") && content.contains("<text:deletion>"),
        "the revisions themselves stay"
    );
}

#[test]
fn a_dc_creator_that_is_not_an_attribution_is_left_alone() {
    // ODF puts authorship in element text, and `dc:creator` is the element name for a comment's
    // author, a revision's author, *and* the document's own. A rule keyed on the name alone
    // would fire on markup it has no business touching, so the scanner tracks context.
    let content = text_of(&strip("comments.odt"), "content.xml");
    assert!(
        content.contains("PRESERVED-BODY-TEXT"),
        "the body outside the annotation must be untouched"
    );
}

#[test]
fn a_cached_author_field_loses_its_value_and_a_displayed_date_does_not() {
    // A `text:creator` field is not words the author typed: the application filled it in from
    // `meta.xml`, so leaving it would print the name strypt just reported removing. A date the
    // author chose to display is the other case, and it stays with a note.
    let stripped = strip("author-fields.odt");
    let content = text_of(&stripped, "content.xml");
    assert!(!content.contains("SYNTHETIC-FIELDCREATOR-0019"));
    assert!(!content.contains("SYNTHETIC-FIELDAUTHOR-0021"));
    assert!(
        content.contains("<text:creator></text:creator>"),
        "the field element stays so the document's structure is untouched"
    );
    assert!(
        content.contains("2021-03-04"),
        "a date the document displays is content, and stays"
    );

    // And a header in styles.xml is scrubbed as the body is.
    let styles = text_of(&stripped, "styles.xml");
    assert!(!styles.contains("SYNTHETIC-HEADERCREATOR-0025"));

    let report =
        inspect_bytes(&fixture("author-fields.odt"), &InspectOptions::names_only()).unwrap();
    assert!(
        report
            .notes
            .iter()
            .any(|n| matches!(n, Note::OutOfScopeContent { .. })),
        "the displayed date has to be declared rather than left silent"
    );
}

#[test]
fn entry_timestamps_are_normalised() {
    // Every entry header records when that part was last written. Across a document's parts that
    // is a record of an editing session's clock times, and no application shows it.
    let report = inspect_bytes(&fixture("clean.odt"), &InspectOptions::names_only()).unwrap();
    assert!(
        report
            .findings
            .iter()
            .any(|f| f.kind == MetadataKind::Timestamp && f.location == "ZIP entry headers"),
        "a package whose entries carry real modification times must say so"
    );
    // The fixture's entries are all stamped 2020-01-01; the output's must not be.
    assert!(
        !contains(&strip("clean.odt"), "\x21\x50"),
        "a DOS date survived"
    );
}

// ---------------------------------------------------------------------------------------------
// The one-level descent, and the embedded object that needs no descent at all (ADR-0029/0031)
// ---------------------------------------------------------------------------------------------

#[test]
fn a_photograph_inside_a_document_is_stripped_by_the_image_handler() {
    // The failure this exists to prevent: a user strips a report, publishes it, and has
    // published every geotag in every picture inside it while holding a success message.
    let report = inspect_bytes(
        &fixture("embedded-image.odt"),
        &InspectOptions::names_only(),
    )
    .unwrap();
    assert!(
        report
            .findings
            .iter()
            .any(|f| f.kind == MetadataKind::Location),
        "GPS coordinates inside an embedded picture must be found"
    );
    assert!(
        report
            .findings
            .iter()
            .any(|f| f.location.starts_with("Pictures/image1.jpg → ")),
        "a finding must be attributed to the picture, not to the document as a whole"
    );

    let entries = unzip(&strip("embedded-image.odt"));
    let image = &entries["Pictures/image1.jpg"];
    assert_eq!(&image[0..2], &[0xFF, 0xD8], "the picture is still a JPEG");
    assert!(!contains(image, "SYNTHETIC-"));
}

#[test]
fn the_embedded_picture_is_stripped_to_the_same_bytes_as_a_loose_one() {
    // Proof that there is no second, weaker implementation for the embedded case — and, since
    // the OOXML suite asserts the same thing about the same picture, that the two package
    // handlers share one descent rather than having one each (ADR-0029).
    let loose =
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../corpus/jpeg/exif-gps.jpg");
    let loose = strip_bytes(&std::fs::read(loose).unwrap(), &StripOptions::default())
        .unwrap()
        .bytes;
    let entries = unzip(&strip("embedded-image.odt"));
    assert_eq!(
        entries["Pictures/image1.jpg"], loose,
        "the same picture must strip to the same bytes inside a document as outside one"
    );
}

#[test]
fn an_embedded_objects_own_metadata_is_removed_rather_than_the_document_refused() {
    // The difference from Office that is worth knowing about. `.docx` stores an embedded chart's
    // cached workbook as a whole `.xlsx` inside the package, which is a nested container and is
    // refused (docs/THREAT_MODEL.md §7.6). ODF stores the same thing as ordinary entries in the
    // same archive, so the chart's own author metadata is reachable in the same pass, with no
    // recursion at all — and the document is cleaned rather than refused.
    let report = inspect_bytes(
        &fixture("embedded-object.ods"),
        &InspectOptions::names_only(),
    )
    .unwrap();
    assert!(
        report
            .findings
            .iter()
            .any(|f| f.location == "Object 1/meta.xml"),
        "the embedded object's own metadata must be found: {:?}",
        report.findings
    );

    let entries = unzip(&strip("embedded-object.ods"));
    assert!(!entries.contains_key("Object 1/meta.xml"));
    assert!(!entries.contains_key("Object 1/settings.xml"));
    assert!(
        entries.contains_key("Object 1/content.xml"),
        "the object's content is the document's payload and stays"
    );
    assert!(contains(
        &entries["Object 1/content.xml"],
        "PRESERVED-CHART-TEXT"
    ));
}

// ---------------------------------------------------------------------------------------------
// Fail-closed
// ---------------------------------------------------------------------------------------------

#[test]
fn every_malformed_fixture_is_refused() {
    // The most dangerous outcome this tool can produce is success on a file it did not really
    // process (docs/THREAT_MODEL.md §5.4). There is no Ok path for any of these.
    for path in malformed_fixtures() {
        let data = std::fs::read(&path).unwrap();
        let name = path.file_name().unwrap().to_string_lossy().into_owned();
        assert!(
            strip_bytes(&data, &StripOptions::default()).is_err(),
            "{name} was not refused"
        );
        assert!(
            inspect_bytes(&data, &InspectOptions::names_only()).is_err(),
            "{name} was not refused by show either"
        );
    }
}

#[test]
fn an_odf_encrypted_package_is_refused_even_though_zip_cannot_see_the_encryption() {
    // The most dangerous case in this handler. ODF does not set ZIP's encryption bit: it
    // encrypts the entry data itself and records the fact in the manifest (Part 2 §3.4). The
    // general-purpose-bit refusal that catches an encrypted Office document therefore passes an
    // encrypted OpenDocument straight through, whereupon `content.xml` is ciphertext, no rule
    // matches it, and the package would be reported clean having been read by nobody.
    assert!(matches!(
        strip_bytes(&malformed("encrypted.odt"), &StripOptions::default()),
        Err(StryptError::Malformed { .. })
    ));
}

#[test]
fn a_package_that_gives_two_answers_about_what_it_is_gets_refused() {
    // `mimetype` says text, the manifest's root entry says spreadsheet. Different readers would
    // disagree about what they are opening, and picking a winner would mean strypt deciding
    // which of two documents the user has.
    assert!(matches!(
        strip_bytes(
            &malformed("mimetype-mismatch.odt"),
            &StripOptions::default()
        ),
        Err(StryptError::Malformed { .. })
    ));
}

#[test]
fn a_package_with_no_manifest_is_refused() {
    // Part 2 §2.2.1 requires it. Without one there is no package, only a ZIP of loose XML.
    assert!(matches!(
        strip_bytes(&malformed("no-manifest.odt"), &StripOptions::default()),
        Err(StryptError::UnsupportedFormat { .. } | StryptError::Malformed { .. })
    ));
}

#[test]
fn a_document_containing_another_container_is_refused_rather_than_partly_cleaned() {
    // ADR-0029 fixes the descent at one level. A nested archive and an OLE object each carry
    // metadata this pass cannot reach, so the document is refused and the user learns the file
    // is there rather than publishing over it.
    for name in ["nested-archive.odt", "ole-object.odt"] {
        assert!(
            matches!(
                strip_bytes(&malformed(name), &StripOptions::default()),
                Err(StryptError::Malformed { .. })
            ),
            "{name} was not refused"
        );
    }
}

#[test]
fn truncating_a_package_anywhere_never_panics() {
    let data = fixture("everything.odt");
    for n in (0..data.len()).step_by(7) {
        let prefix = &data[0..n];
        let _ = inspect_bytes(prefix, &InspectOptions::names_only());
        let _ = strip_bytes(prefix, &StripOptions::default());
    }
}

#[test]
fn flipping_any_single_byte_never_panics() {
    // Cheap structured fuzzing in the test suite: it catches the parse paths that only a
    // corrupted length field reaches, without waiting for a fuzz run.
    let data = fixture("everything.odt");
    for index in (0..data.len()).step_by(3) {
        let mut mutated = data.clone();
        mutated[index] ^= 0xFF;
        let _ = inspect_bytes(&mutated, &InspectOptions::names_only());
        let _ = strip_bytes(&mutated, &StripOptions::default());
    }
}

// ---------------------------------------------------------------------------------------------
// Reporting
// ---------------------------------------------------------------------------------------------

#[test]
fn a_clean_document_produces_no_findings_beyond_its_container() {
    // A tool that invents findings teaches users to ignore it. The entry timestamps are the one
    // legitimate finding here, and they are real.
    let report = inspect_bytes(&fixture("clean.odt"), &InspectOptions::names_only()).unwrap();
    assert!(
        report
            .findings
            .iter()
            .all(|f| f.location == "ZIP entry headers"),
        "unexpected findings in a clean document: {:?}",
        report.findings
    );
}

#[test]
fn values_are_withheld_unless_the_caller_asks() {
    // A report is easy to redirect into a file, which recreates the secret the user asked to
    // have destroyed (docs/THREAT_MODEL.md §5.5).
    let names_only = inspect_bytes(&fixture("meta.odt"), &InspectOptions::names_only()).unwrap();
    assert!(names_only.findings.iter().all(|f| f.value.is_none()));

    let with_values = inspect_bytes(&fixture("meta.odt"), &InspectOptions::with_values()).unwrap();
    assert!(
        with_values.findings.iter().any(|f| f.value.is_some()),
        "a caller that opted in must actually get values"
    );
}

#[test]
fn inspect_never_modifies_its_input() {
    let original = fixture("everything.odt");
    let mut copy = original.clone();
    let _ = inspect_bytes(&copy, &InspectOptions::with_values()).unwrap();
    assert_eq!(original, copy);
    copy.clear();
}
