//! End-to-end tests for the Ogg handler, over the fixtures in `corpus/ogg`.
//!
//! Each fixture is generated by `corpus/tools/make_ogg_fixtures.py` and documented in
//! `corpus/MANIFEST.md`. The synthetic marker strings — `SYNTHETIC-…-000N` — exist so a test can
//! assert on the *bytes of the output* rather than on strypt's own report: a handler that forgot
//! to remove something would still report having removed it.
//!
//! # Why this file carries its own page walker
//!
//! An Ogg is rebuilt rather than edited (ADR-0041), so the claims that matter are claims about the
//! structure that came back: that the packets crossed byte for byte, that every granule position
//! stayed with its packet, that the serial number is gone, and that every page's CRC is one a
//! decoder will accept. Checking those with the handler's own reader would assert only that the
//! parser agrees with itself. [`pages`] and [`packets`] walk the file independently, as
//! `tests/mp3.rs` walks a frame sequence.

// Test code is not reachable from untrusted bytes, which is the boundary the panic-freedom lints
// police (ADR-0006).
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing,
    clippy::arithmetic_side_effects
)]

use strypt_core::error::UnsupportedKind;
use strypt_core::formats::StripOptions;
use strypt_core::report::{InspectOptions, Note, RetentionReason};
use strypt_core::{Format, StryptError, detect, inspect_bytes, strip_bytes};

fn fixture(name: &str) -> Vec<u8> {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../corpus/ogg")
        .join(name);
    std::fs::read(&path).unwrap_or_else(|e| panic!("reading fixture {}: {e}", path.display()))
}

fn malformed(name: &str) -> Vec<u8> {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../corpus/ogg/malformed")
        .join(name);
    std::fs::read(&path).unwrap_or_else(|e| panic!("reading fixture {}: {e}", path.display()))
}

fn strip(name: &str) -> Vec<u8> {
    let input = fixture(name);
    strip_bytes(&input, &StripOptions::default())
        .unwrap_or_else(|e| panic!("stripping {name}: {e}"))
        .bytes
}

fn contains(haystack: &[u8], needle: &str) -> bool {
    haystack
        .windows(needle.len())
        .any(|w| w == needle.as_bytes())
}

const FIXTURES: &[(&str, Format)] = &[
    ("clean-vorbis.ogg", Format::Ogg),
    ("vorbis.ogg", Format::Ogg),
    ("vorbis-cover-art.ogg", Format::Ogg),
    ("vorbis-many-comments.ogg", Format::Ogg),
    ("clean-opus.opus", Format::Opus),
    ("opus.opus", Format::Opus),
    ("opus-padding.opus", Format::Opus),
    ("clean-ogg-flac.oga", Format::OggFlac),
    ("ogg-flac.oga", Format::OggFlac),
    ("ogg-flac-blocks.oga", Format::OggFlac),
];

const MALFORMED: &[&str] = &[
    "truncated.ogg",
    "bad-crc.ogg",
    "unknown-page-version.ogg",
    "theora.ogv",
    "speex.spx",
    "skeleton.ogg",
    "multiplexed.ogg",
    "chained.ogg",
    "leading-bytes.ogg",
    "trailing-bytes.ogg",
    "no-comment-header.ogg",
    "headers-only.ogg",
    "granule-on-carrier-page.ogg",
    "flac-block-overrun.oga",
    "flac-header-count-mismatch.oga",
];

/// Refused before dispatch rather than by the handler: `OggS` is not at byte zero, so nothing
/// identifies the file as an Ogg. Still fail-closed — nothing is written — but the refusal carries
/// no format name.
const REFUSED_AT_DETECTION: &[&str] = &["leading-bytes.ogg"];

/// One page, as this file reads it.
#[derive(Debug, PartialEq, Eq)]
struct Page {
    flags: u8,
    granule: u64,
    serial: u32,
    sequence: u32,
    lacing: Vec<u8>,
    body: Vec<u8>,
}

/// RFC 3533 §6.2's CRC: polynomial `0x04c11db7`, unreflected, zero-initialised, no final xor.
/// Spelled out here rather than borrowed, because "the CRC is right" is one of the claims.
fn crc(data: &[u8]) -> u32 {
    let mut r: u32 = 0;
    for byte in data {
        r ^= u32::from(*byte) << 24;
        for _ in 0..8 {
            r = if r & 0x8000_0000 == 0 {
                r << 1
            } else {
                (r << 1) ^ 0x04c1_1db7
            };
        }
    }
    r
}

/// Every page in `data`, refusing anything that is not exactly a run of pages with valid CRCs.
///
/// Written here rather than borrowed from the handler: a check that used the code under test to
/// read its own output would prove nothing.
fn pages(data: &[u8]) -> Vec<Page> {
    let mut out = Vec::new();
    let mut at = 0;
    while at < data.len() {
        assert_eq!(&data[at..at + 4], b"OggS", "not a page at {at}");
        assert_eq!(data[at + 4], 0, "unknown page version at {at}");
        let segments = usize::from(data[at + 26]);
        let lacing = data[at + 27..at + 27 + segments].to_vec();
        let body_at = at + 27 + segments;
        let body =
            data[body_at..body_at + lacing.iter().map(|n| usize::from(*n)).sum::<usize>()].to_vec();
        let end = body_at + body.len();

        let declared = u32::from_le_bytes(data[at + 22..at + 26].try_into().unwrap());
        let mut zeroed = data[at..end].to_vec();
        zeroed[22..26].fill(0);
        assert_eq!(crc(&zeroed), declared, "page at {at} has a bad CRC");

        out.push(Page {
            flags: data[at + 5],
            granule: u64::from_le_bytes(data[at + 6..at + 14].try_into().unwrap()),
            serial: u32::from_le_bytes(data[at + 14..at + 18].try_into().unwrap()),
            sequence: u32::from_le_bytes(data[at + 18..at + 22].try_into().unwrap()),
            lacing,
            body,
        });
        at = end;
    }
    assert!(!out.is_empty(), "no pages");
    out
}

/// The complete packets in `data`, each with the granule of the page it finished on.
fn packets(data: &[u8]) -> Vec<(Vec<u8>, u64)> {
    let mut out = Vec::new();
    let mut open: Vec<u8> = Vec::new();
    let mut pending = false;
    for page in pages(data) {
        let mut at = 0;
        for value in &page.lacing {
            let n = usize::from(*value);
            open.extend_from_slice(&page.body[at..at + n]);
            at += n;
            if n < 255 {
                out.push((std::mem::take(&mut open), page.granule));
                pending = false;
            } else {
                pending = true;
            }
        }
    }
    assert!(!pending, "the stream ends mid-packet");
    out
}

#[test]
fn every_fixture_is_detected_as_the_mapping_it_carries() {
    for (name, format) in FIXTURES {
        assert_eq!(detect(&fixture(name)).unwrap(), *format, "{name}");
    }
}

#[test]
fn no_synthetic_marker_survives_any_fixture() {
    // The absolute check, independent of what the report claims: every identifying value in the
    // corpus is a marker, so this reads the output bytes rather than strypt's account of them.
    for (name, _) in FIXTURES {
        assert!(
            !contains(&strip(name), "SYNTHETIC-"),
            "a synthetic marker survived {name}"
        );
    }
}

#[test]
fn the_audio_packets_cross_byte_for_byte() {
    // The property the rebuild trades page structure for. It is why a re-encoding tool and strypt
    // are different offers rather than the same one twice.
    for (name, format) in FIXTURES {
        let before = packets(&fixture(name));
        let after = packets(&strip(name));
        // The comment header is the second packet in all three mappings, and the only one that
        // changes; for Ogg FLAC every metadata block after `STREAMINFO` is its own packet too.
        let headers = match format {
            Format::Opus => 2,
            Format::OggFlac => audio_start(name),
            _ => 3,
        };
        assert_eq!(before.len(), after.len(), "{name}: a packet was lost");
        for index in headers..before.len() {
            assert_eq!(
                before[index].0, after[index].0,
                "{name}: audio packet {index} was rewritten"
            );
        }
    }
}

/// Where the audio starts in an Ogg FLAC fixture: after the mapping packet and every metadata
/// block packet, which is one more than the mapping header declares.
fn audio_start(name: &str) -> usize {
    let mapping = &packets(&fixture(name))[0].0;
    usize::from(u16::from_be_bytes([mapping[7], mapping[8]])) + 1
}

#[test]
fn every_granule_position_stays_with_its_packet() {
    // They are codec sample counts, not file offsets (RFC 3533 §3), so removal moves nothing and
    // a rebuild that shifted one would silently change where the audio is in time.
    for (name, _) in FIXTURES {
        let before: Vec<u64> = packets(&fixture(name)).iter().map(|(_, g)| *g).collect();
        let after: Vec<u64> = packets(&strip(name)).iter().map(|(_, g)| *g).collect();
        assert_eq!(before, after, "{name}: a granule position moved");
    }
}

#[test]
fn the_serial_number_is_rewritten_and_the_pages_are_renumbered() {
    // The serial is a 32-bit identifier nobody can recompute, and libogg's own example seeds it
    // from the clock (ADR-0041 decision 5). The fixtures all carry a non-zero one.
    for (name, _) in FIXTURES {
        assert!(
            pages(&fixture(name)).iter().all(|p| p.serial != 0),
            "{name}: the fixture cannot show the rewrite"
        );
        for (index, page) in pages(&strip(name)).iter().enumerate() {
            assert_eq!(page.serial, 0, "{name}: the serial survived");
            assert_eq!(
                page.sequence,
                u32::try_from(index).unwrap(),
                "{name}: the pages are not numbered from zero"
            );
        }
    }
}

#[test]
fn the_stream_is_flagged_at_both_ends() {
    for (name, _) in FIXTURES {
        let out = pages(&strip(name));
        assert_eq!(out[0].flags & 0x02, 0x02, "{name}: no beginning-of-stream");
        assert_eq!(
            out[out.len() - 1].flags & 0x04,
            0x04,
            "{name}: no end-of-stream"
        );
        assert!(
            out[1..].iter().all(|p| p.flags & 0x02 == 0),
            "{name}: a second beginning-of-stream"
        );
        assert!(
            out[..out.len() - 1].iter().all(|p| p.flags & 0x04 == 0),
            "{name}: an end-of-stream in the middle"
        );
    }
}

#[test]
fn the_comment_header_is_emptied_rather_than_dropped() {
    // All three mappings require the packet in place, so unlike FLAC's metadata block it cannot go.
    for (name, format) in FIXTURES {
        let second = packets(&strip(name))[1].0.clone();
        let expected: &[u8] = match format {
            Format::Opus => b"OpusTags",
            Format::OggFlac => &[],
            _ => b"\x03vorbis",
        };
        if !expected.is_empty() {
            assert!(second.starts_with(expected), "{name}: the header went");
            assert_eq!(
                second.len(),
                expected.len() + 8 + usize::from(*format == Format::Ogg),
                "{name}: the emptied header is not empty"
            );
        }
    }
}

#[test]
fn an_ogg_flac_keeps_its_packet_count_and_its_declared_header_count() {
    // A removed block becomes a zero-length PADDING packet, so neither the count nor the
    // last-metadata-block flag has to be rewritten (ADR-0041 decision 9).
    for name in ["clean-ogg-flac.oga", "ogg-flac.oga", "ogg-flac-blocks.oga"] {
        let before = packets(&fixture(name));
        let after = packets(&strip(name));
        assert_eq!(before.len(), after.len(), "{name}");
        assert_eq!(
            before[0].0, after[0].0,
            "{name}: the mapping header was rewritten"
        );
        let last = &after[audio_start(name) - 1].0;
        assert_eq!(last[0] & 0x80, 0x80, "{name}: the last-block flag moved");
    }
}

#[test]
fn an_ogg_flac_seek_table_survives_and_its_audio_md5_is_declared() {
    let input = fixture("ogg-flac-blocks.oga");
    let stripped = strip_bytes(&input, &StripOptions::default()).unwrap();
    assert!(
        stripped
            .report
            .retained
            .iter()
            .any(|r| r.reason == RetentionReason::DerivedFromPayload),
        "the audio MD5 was kept without being declared"
    );
    assert!(
        stripped
            .bytes
            .windows(18)
            .any(|w| w == [0x11u8; 18].as_slice()),
        "the seek table did not survive"
    );
}

#[test]
fn the_uninspected_packets_are_declared_on_every_fixture() {
    // Said on clean files too: the packets are copied without being decoded, so anything inside
    // one is out of reach rather than absent.
    for (name, _) in FIXTURES {
        let notes = inspect_bytes(&fixture(name), &InspectOptions::names_only())
            .unwrap()
            .notes;
        assert!(
            notes.iter().any(|n| matches!(
                n,
                Note::OutOfScopeContent { location } if location.starts_with("audio packets")
            )),
            "{name} said nothing about its packets"
        );
    }
}

#[test]
fn every_malformed_fixture_is_refused() {
    // Fail closed: a file strypt cannot fully account for is refused, never partly cleaned.
    for name in MALFORMED {
        let data = malformed(name);
        let refused = match detect(&data) {
            Ok(_) => strip_bytes(&data, &StripOptions::default()).is_err(),
            // Refused at detection is still refused — but only for the fixtures named above. For
            // any other, `UnrecognisedFormat` means it stopped being an Ogg and never reached the
            // handler, which is a silent hole rather than a pass.
            Err(StryptError::UnrecognisedFormat) => {
                assert!(
                    REFUSED_AT_DETECTION.contains(name),
                    "{name} is no longer recognised as an Ogg — the fixture is broken"
                );
                true
            }
            Err(_) => true,
        };
        assert!(refused, "{name} was accepted");
    }
}

#[test]
fn the_fixtures_refused_at_detection_are_exactly_the_ones_named() {
    // Pins the exception both ways: one drifting into detection's reach, or a new one drifting out
    // of it, is a change to what strypt claims to recognise and should not pass quietly.
    for name in MALFORMED {
        let nameless = matches!(
            detect(&malformed(name)),
            Err(StryptError::UnrecognisedFormat)
        );
        assert_eq!(
            nameless,
            REFUSED_AT_DETECTION.contains(name),
            "{name} changed which stage refuses it"
        );
    }
}

#[test]
fn the_codecs_that_do_not_land_here_are_refused_by_name() {
    // "Unrecognised" would be untrue and unhelpful for a file every player calls an Ogg.
    for (name, expected) in [
        ("theora.ogv", UnsupportedKind::OggTheora),
        ("speex.spx", UnsupportedKind::OtherOggCodec),
        ("skeleton.ogg", UnsupportedKind::OtherOggCodec),
        ("multiplexed.ogg", UnsupportedKind::MultiplexedOgg),
        ("chained.ogg", UnsupportedKind::MultiplexedOgg),
    ] {
        match strip_bytes(&malformed(name), &StripOptions::default()) {
            Err(StryptError::UnsupportedFormat { format }) => {
                assert_eq!(format, expected, "{name}");
            }
            other => panic!("{name} was not named: {other:?}"),
        }
    }
}

#[test]
fn output_re_inspects_clean() {
    // The verification pass's own claim, asserted directly: nothing `strip` removed is something
    // `inspect` can still find.
    for (name, _) in FIXTURES {
        let report = inspect_bytes(&strip(name), &InspectOptions::names_only()).unwrap();
        assert!(
            report.findings.is_empty(),
            "metadata survived {name}: {:?}",
            report.findings
        );
    }
}

#[test]
fn stripping_is_idempotent_over_the_corpus() {
    // Byte-exact, which is what an Ogg promises in place of the byte-identical clean file the rest
    // of this group's handlers give (ADR-0041).
    for (name, _) in FIXTURES {
        let once = strip(name);
        let twice = strip_bytes(&once, &StripOptions::default()).unwrap().bytes;
        assert_eq!(once, twice, "strip is not idempotent for {name}");
    }
}

#[test]
fn inspect_and_strip_agree_on_what_is_there() {
    for (name, _) in FIXTURES {
        let input = fixture(name);
        let seen = inspect_bytes(&input, &InspectOptions::names_only())
            .unwrap()
            .findings;
        let removed = strip_bytes(&input, &StripOptions::default())
            .unwrap()
            .report
            .removed;
        assert_eq!(
            seen.len(),
            removed.len(),
            "{name}: show and strip disagree about what is in the file"
        );
    }
}

#[test]
fn truncating_any_fixture_anywhere_never_panics() {
    for (name, _) in FIXTURES {
        let input = fixture(name);
        // Every length for the small fixtures; a stride through the two large ones, which are a
        // cover-art comment and four hundred comments and would otherwise dominate the run.
        let stride = if input.len() > 8192 { 97 } else { 1 };
        for n in (0..=input.len()).step_by(stride) {
            let prefix = &input[0..n];
            let _ = inspect_bytes(prefix, &InspectOptions::names_only());
            let _ = strip_bytes(prefix, &StripOptions::default());
        }
    }
}

#[test]
fn flipping_any_single_byte_never_panics() {
    // Cheap structural mutation. The fuzz targets explore much further; this keeps the property
    // under `cargo test` where it cannot be forgotten.
    for (name, _) in FIXTURES {
        let input = fixture(name);
        let stride = if input.len() > 8192 { 97 } else { 1 };
        for at in (0..input.len()).step_by(stride) {
            let mut mutated = input.clone();
            mutated[at] ^= 0xFF;
            let _ = inspect_bytes(&mutated, &InspectOptions::names_only());
            let _ = strip_bytes(&mutated, &StripOptions::default());
        }
    }
}
