//! End-to-end tests for the Office Open XML handler, over the fixtures in `corpus/ooxml`.
//!
//! Each fixture is generated by `corpus/tools/make_ooxml_fixtures.py` and documented in
//! `corpus/MANIFEST.md`. The synthetic marker strings — `SYNTHETIC-…-000N` — exist so that a
//! test can assert on the *bytes of the output* rather than on strypt's own report. That
//! distinction is the point: a handler that forgot to remove something would still happily
//! report having removed it.
//!
//! The `PRESERVED-…` markers are the mirror image. They are the document's own words — the text
//! of a tracked insertion, the body of a comment — and a test that only checked for absence
//! would pass just as well if the handler had deleted the document's contents (ADR-0030).

// Test code is not reachable from untrusted bytes, which is the boundary the panic-freedom
// lints police (ADR-0006).
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing,
    clippy::arithmetic_side_effects
)]

use std::collections::BTreeMap;

use strypt_core::error::UnsupportedKind;
use strypt_core::formats::StripOptions;
use strypt_core::report::{InspectOptions, MetadataKind, Note};
use strypt_core::{Format, StryptError, detect, inspect_bytes, strip_bytes};

fn fixture(name: &str) -> Vec<u8> {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../corpus/ooxml")
        .join(name);
    std::fs::read(&path).unwrap_or_else(|e| panic!("reading fixture {}: {e}", path.display()))
}

fn strip(name: &str) -> Vec<u8> {
    let input = fixture(name);
    strip_bytes(&input, &StripOptions::default())
        .unwrap_or_else(|e| panic!("stripping {name}: {e}"))
        .bytes
}

/// Every valid fixture, which is every file directly in `corpus/ooxml`.
fn all_fixtures() -> Vec<String> {
    let dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../corpus/ooxml");
    let mut names: Vec<String> = std::fs::read_dir(&dir)
        .unwrap()
        .filter_map(|entry| {
            let entry = entry.ok()?;
            entry.file_type().ok()?.is_file().then_some(())?;
            Some(entry.file_name().to_string_lossy().into_owned())
        })
        .collect();
    names.sort();
    assert!(!names.is_empty(), "the fixture directory is empty");
    names
}

/// The malformed fixtures, every one of which must be refused.
fn malformed_fixtures() -> Vec<std::path::PathBuf> {
    let dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../corpus/ooxml/malformed");
    let mut paths: Vec<_> = std::fs::read_dir(&dir)
        .unwrap()
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.is_file())
        .collect();
    paths.sort();
    paths
}

/// Read a ZIP archive into an ordered map of entry name to uncompressed contents.
///
/// **Deliberately a second implementation**, written here rather than calling
/// [`strypt_core`]'s own reader. A test that parsed the output with the code under test would
/// be asserting that the parser agrees with itself, and would pass just as happily on an
/// archive no other tool can open. This one walks the central directory independently and
/// inflates with `flate2` directly.
///
/// It also asserts that no entry name appears twice — the check that caught the handler
/// writing `[Content_Types].xml` into the package a second time, which every real reader
/// tolerates by silently preferring one of the two.
fn unzip(data: &[u8]) -> BTreeMap<String, Vec<u8>> {
    let eocd = rfind(data, b"PK\x05\x06").expect("no end-of-central-directory record");
    let count = u16::from_le_bytes(data[eocd + 10..eocd + 12].try_into().unwrap()) as usize;
    let mut at = u32::from_le_bytes(data[eocd + 16..eocd + 20].try_into().unwrap()) as usize;

    let mut out = BTreeMap::new();
    for _ in 0..count {
        assert_eq!(
            &data[at..at + 4],
            b"PK\x01\x02",
            "central directory ended early"
        );
        let method = u16::from_le_bytes(data[at + 10..at + 12].try_into().unwrap());
        let crc = u32::from_le_bytes(data[at + 16..at + 20].try_into().unwrap());
        let compressed = u32::from_le_bytes(data[at + 20..at + 24].try_into().unwrap()) as usize;
        let uncompressed = u32::from_le_bytes(data[at + 24..at + 28].try_into().unwrap()) as usize;
        let name_len = u16::from_le_bytes(data[at + 28..at + 30].try_into().unwrap()) as usize;
        let extra_len = u16::from_le_bytes(data[at + 30..at + 32].try_into().unwrap()) as usize;
        let comment_len = u16::from_le_bytes(data[at + 32..at + 34].try_into().unwrap()) as usize;
        let local = u32::from_le_bytes(data[at + 42..at + 46].try_into().unwrap()) as usize;
        let name = String::from_utf8_lossy(&data[at + 46..at + 46 + name_len]).into_owned();
        at += 46 + name_len + extra_len + comment_len;

        assert_eq!(
            &data[local..local + 4],
            b"PK\x03\x04",
            "{name}: bad local header"
        );
        let local_name =
            u16::from_le_bytes(data[local + 26..local + 28].try_into().unwrap()) as usize;
        let local_extra =
            u16::from_le_bytes(data[local + 28..local + 30].try_into().unwrap()) as usize;
        let start = local + 30 + local_name + local_extra;
        let payload = &data[start..start + compressed];

        let contents = match method {
            0 => payload.to_vec(),
            8 => {
                use std::io::Read as _;
                let mut decoded = Vec::new();
                flate2::read::DeflateDecoder::new(payload)
                    .read_to_end(&mut decoded)
                    .unwrap_or_else(|e| panic!("{name}: inflate failed: {e}"));
                decoded
            }
            other => panic!("{name}: unexpected compression method {other}"),
        };
        assert_eq!(
            contents.len(),
            uncompressed,
            "{name}: declared size is wrong"
        );
        assert_eq!(crc32(&contents), crc, "{name}: CRC does not match the data");

        assert!(
            out.insert(name.clone(), contents).is_none(),
            "the archive contains {name} twice"
        );
    }
    out
}

/// The offset of the last occurrence of `needle`.
fn rfind(haystack: &[u8], needle: &[u8]) -> Option<usize> {
    haystack
        .windows(needle.len())
        .rposition(|window| window == needle)
}

/// CRC-32, computed here rather than borrowed from the crate strypt uses, so that a wrong
/// checksum in strypt's output cannot be validated by the same code that produced it.
fn crc32(data: &[u8]) -> u32 {
    let mut crc = 0xFFFF_FFFFu32;
    for byte in data {
        crc ^= u32::from(*byte);
        for _ in 0..8 {
            crc = if crc & 1 == 1 {
                (crc >> 1) ^ 0xEDB8_8320
            } else {
                crc >> 1
            };
        }
    }
    !crc
}

fn contains(haystack: &[u8], needle: &str) -> bool {
    haystack
        .windows(needle.len())
        .any(|w| w == needle.as_bytes())
}

// ---------------------------------------------------------------------------------------------
// Detection
// ---------------------------------------------------------------------------------------------

#[test]
fn each_package_is_detected_by_what_it_declares_about_itself() {
    // Not by extension, and not by searching the raw bytes for a part name — the string
    // `word/document.xml` appears verbatim in any archive that merely contains a Word document.
    assert_eq!(detect(&fixture("clean.docx")).unwrap(), Format::Docx);
    assert_eq!(detect(&fixture("workbook.xlsx")).unwrap(), Format::Xlsx);
    assert_eq!(detect(&fixture("presentation.pptx")).unwrap(), Format::Pptx);
}

#[test]
fn a_macro_enabled_document_is_named_in_its_refusal() {
    // Distinct from the generic ZIP refusal because the advice differs: this is not "a later
    // release will handle it", it is "the VBA project inside is a container strypt cannot read"
    // (ADR-0029).
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../corpus/ooxml/malformed/macro-enabled.docm");
    let data = std::fs::read(path).unwrap();
    assert!(matches!(
        detect(&data),
        Err(StryptError::UnsupportedFormat {
            format: UnsupportedKind::MacroEnabledOffice
        })
    ));
}

// ---------------------------------------------------------------------------------------------
// The invariants that apply to every fixture
// ---------------------------------------------------------------------------------------------

#[test]
fn no_synthetic_marker_survives_any_fixture() {
    // The assertion that matters most, and the one that does not trust strypt's own report.
    for name in all_fixtures() {
        let stripped = strip(&name);
        assert!(
            !contains(&stripped, "SYNTHETIC-"),
            "a synthetic marker survived stripping {name}"
        );
    }
}

#[test]
fn stripping_is_byte_identically_idempotent() {
    // docs/TESTING_STRATEGY.md §1, invariant 3. This is the assertion that caught the handler
    // writing `[Content_Types].xml` into the package twice: every reader tolerated the duplicate
    // and nothing else noticed.
    for name in all_fixtures() {
        let once = strip(&name);
        let twice = strip_bytes(&once, &StripOptions::default()).unwrap().bytes;
        assert_eq!(once, twice, "stripping {name} is not idempotent");
    }
}

#[test]
fn stripped_output_inspects_clean() {
    // Phase 1 exit criterion 5, applied to this format.
    for name in all_fixtures() {
        let stripped = strip(&name);
        let report = inspect_bytes(&stripped, &InspectOptions::names_only()).unwrap();
        assert!(
            report.findings.is_empty(),
            "{name} still reports findings after stripping: {:?}",
            report.findings
        );
    }
}

#[test]
fn every_package_stays_a_package_another_tool_can_open() {
    // Verified with Python's `zipfile`, not with strypt's reader — see `unzip`. It also asserts
    // that no entry name appears twice.
    for name in all_fixtures() {
        let entries = unzip(&strip(&name));
        assert!(
            entries.contains_key("[Content_Types].xml"),
            "{name} lost the part that makes it an OOXML package"
        );
        assert!(entries.contains_key("_rels/.rels"), "{name} lost its rels");
    }
}

#[test]
fn nothing_refers_to_a_part_that_is_no_longer_there() {
    // A document referencing parts that are not there is invalid, and Word offers to repair it.
    // For someone trying not to draw attention to a file, a repair prompt is a worse outcome
    // than a slightly larger one (ADR-0030).
    for name in all_fixtures() {
        let entries = unzip(&strip(&name));
        let content_types = String::from_utf8_lossy(&entries["[Content_Types].xml"]).into_owned();
        for declared in between_all(&content_types, "PartName=\"/", "\"") {
            assert!(
                entries.contains_key(&declared),
                "{name}: [Content_Types].xml declares {declared}, which is not in the package"
            );
        }
        let rels = String::from_utf8_lossy(&entries["_rels/.rels"]).into_owned();
        for target in between_all(&rels, "Target=\"", "\"") {
            if target.starts_with("http") || target.starts_with("file:") {
                continue;
            }
            let target = target.trim_start_matches('/').to_owned();
            assert!(
                entries.contains_key(&target),
                "{name}: _rels/.rels points at {target}, which is not in the package"
            );
        }
    }
}

/// Every substring of `text` between `open` and the next `close`.
fn between_all(text: &str, open: &str, close: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut rest = text;
    while let Some(start) = rest.find(open) {
        rest = &rest[start + open.len()..];
        let Some(end) = rest.find(close) else { break };
        out.push(rest[..end].to_owned());
        rest = &rest[end..];
    }
    out
}

// ---------------------------------------------------------------------------------------------
// What must be removed
// ---------------------------------------------------------------------------------------------

#[test]
fn the_properties_parts_are_removed_whole() {
    let entries = unzip(&strip("everything.docx"));
    for part in [
        "docProps/core.xml",
        "docProps/app.xml",
        "docProps/custom.xml",
    ] {
        assert!(!entries.contains_key(part), "{part} survived");
    }
}

#[test]
fn the_package_thumbnail_is_removed() {
    // It is a rendered preview of the first page, and it survives every kind of redaction
    // applied to the text — the same way an Exif thumbnail survives cropping.
    let entries = unzip(&strip("thumbnail.docx"));
    assert!(!entries.contains_key("docProps/thumbnail.jpeg"));

    let report = inspect_bytes(&fixture("thumbnail.docx"), &InspectOptions::names_only()).unwrap();
    assert!(
        report
            .findings
            .iter()
            .any(|f| f.kind == MetadataKind::Thumbnail),
        "the thumbnail must be reported as a thumbnail, not as an anonymous part"
    );
}

#[test]
fn revision_save_identifiers_go_and_the_documents_words_stay() {
    let stripped = strip("revision-identifiers.docx");
    let entries = unzip(&stripped);
    let document = String::from_utf8_lossy(&entries["word/document.xml"]).into_owned();
    for attribute in [
        "w:rsidR",
        "w:rsidRDefault",
        "w:rsidP",
        "w14:paraId",
        "w14:textId",
    ] {
        assert!(!document.contains(attribute), "{attribute} survived");
    }
    assert!(
        document.contains("PRESERVED-BODY-TEXT"),
        "the document's own words are its payload and must survive (PRD §8.1)"
    );

    let settings = String::from_utf8_lossy(&entries["word/settings.xml"]).into_owned();
    assert!(!settings.contains("w:rsids"), "the rsid table survived");
    assert!(
        settings.contains("w:zoom"),
        "removing the rsid table must not take the rest of settings.xml with it"
    );
}

#[test]
fn a_tracked_change_loses_its_author_and_keeps_its_words() {
    // The hardest call in ADR-0030. Removing a tracked insertion means deciding whether the
    // document accepts or rejects it, which changes what the document says — so the attribution
    // goes and the content stays.
    let entries = unzip(&strip("tracked-changes.docx"));
    let document = String::from_utf8_lossy(&entries["word/document.xml"]).into_owned();
    assert!(!document.contains("w:author"));
    assert!(!document.contains("SYNTHETIC-INSERTER-0013"));
    assert!(document.contains("PRESERVED-INSERTED-TEXT"));
    assert!(document.contains("PRESERVED-DELETED-TEXT"));
    assert!(
        document.contains("<w:ins "),
        "the revision itself stays; only its attribution goes"
    );
}

#[test]
fn a_comment_is_reported_as_content_strypt_did_not_remove() {
    // The user is told the comment is there and left to decide, which is the same position
    // strypt takes on text under a redaction rectangle (docs/THREAT_MODEL.md §4.3).
    let report = inspect_bytes(&fixture("comments.docx"), &InspectOptions::names_only()).unwrap();
    assert!(
        report
            .notes
            .iter()
            .any(|n| matches!(n, Note::OutOfScopeContent { .. })),
        "a document with comments in it must say so"
    );
    let entries = unzip(&strip("comments.docx"));
    let comments = String::from_utf8_lossy(&entries["word/comments.xml"]).into_owned();
    assert!(!comments.contains("SYNTHETIC-COMMENTER-0015"));
    assert!(comments.contains("PRESERVED-COMMENT-TEXT"));
}

#[test]
fn a_spreadsheet_author_list_is_emptied_rather_than_shortened() {
    // `authorId` is a positional index into this list. Deleting an entry would silently
    // reattribute every comment after it.
    let entries = unzip(&strip("workbook.xlsx"));
    let comments = String::from_utf8_lossy(&entries["xl/comments1.xml"]).into_owned();
    assert_eq!(
        comments.matches("<author>").count(),
        2,
        "both entries must remain so the indexes still point where they did"
    );
    assert!(!comments.contains("SYNTHETIC-XLAUTHOR"));
    assert!(comments.contains("PRESERVED-XL-COMMENT"));
}

#[test]
fn a_presentation_comment_author_keeps_its_id() {
    let entries = unzip(&strip("presentation.pptx"));
    let authors = String::from_utf8_lossy(&entries["ppt/commentAuthors.xml"]).into_owned();
    assert!(!authors.contains("SYNTHETIC-PPTAUTHOR-0019"));
    assert!(
        authors.contains("id=\"1\""),
        "the id is what comments refer to and must not move"
    );
}

#[test]
fn an_external_relationship_to_a_local_path_goes_at_both_ends() {
    // A `file:` target under someone's home directory names that person. Removing only the
    // relationship would leave the `r:id` that referred to it dangling.
    let entries = unzip(&strip("external-template.docx"));
    let rels = String::from_utf8_lossy(&entries["word/_rels/settings.xml.rels"]).into_owned();
    assert!(!rels.contains("SYNTHETIC-USER-0016"));

    let settings = String::from_utf8_lossy(&entries["word/settings.xml"]).into_owned();
    assert!(
        !settings.contains("w:attachedTemplate"),
        "the element that carried the reference must go with it"
    );
}

#[test]
fn entry_timestamps_are_normalised() {
    // Every entry header records when that part was last written. Across a document's parts
    // that is a record of an editing session's clock times, and no application shows it.
    let report = inspect_bytes(&fixture("clean.docx"), &InspectOptions::names_only()).unwrap();
    assert!(
        report
            .findings
            .iter()
            .any(|f| f.kind == MetadataKind::Timestamp && f.location == "ZIP entry headers"),
        "a package whose entries carry real modification times must say so"
    );
    // The fixture's entries are all stamped 2020-01-01; the output's must not be.
    let stripped = strip("clean.docx");
    assert!(!contains(&stripped, "\x21\x50"), "a DOS date survived");
}

// ---------------------------------------------------------------------------------------------
// The one-level descent (ADR-0029)
// ---------------------------------------------------------------------------------------------

#[test]
fn a_photograph_inside_a_document_is_stripped_by_the_image_handler() {
    // The failure this exists to prevent: a user strips a report, publishes it, and has
    // published every geotag in every picture inside it while holding a success message.
    let report = inspect_bytes(
        &fixture("embedded-image.docx"),
        &InspectOptions::names_only(),
    )
    .unwrap();
    assert!(
        report
            .findings
            .iter()
            .any(|f| f.kind == MetadataKind::Location),
        "GPS coordinates inside an embedded picture must be found"
    );
    assert!(
        report
            .findings
            .iter()
            .any(|f| f.location.starts_with("word/media/image1.jpg → ")),
        "a finding must be attributed to the picture, not to the document as a whole"
    );

    let entries = unzip(&strip("embedded-image.docx"));
    let image = &entries["word/media/image1.jpg"];
    assert_eq!(&image[0..2], &[0xFF, 0xD8], "the picture is still a JPEG");
    assert!(!contains(image, "SYNTHETIC-"));
}

#[test]
fn the_embedded_picture_is_stripped_to_the_same_bytes_as_a_loose_one() {
    // Proof that there is no second, weaker implementation for the embedded case, which is
    // exactly the divergence ADR-0003 exists to prevent.
    let loose =
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../corpus/jpeg/exif-gps.jpg");
    let loose = strip_bytes(&std::fs::read(loose).unwrap(), &StripOptions::default())
        .unwrap()
        .bytes;
    let entries = unzip(&strip("embedded-image.docx"));
    assert_eq!(
        entries["word/media/image1.jpg"], loose,
        "the same picture must strip to the same bytes inside a document as outside one"
    );
}

// ---------------------------------------------------------------------------------------------
// Fail-closed
// ---------------------------------------------------------------------------------------------

#[test]
fn every_malformed_fixture_is_refused() {
    // The most dangerous outcome this tool can produce is success on a file it did not really
    // process (docs/THREAT_MODEL.md §5.4). There is no Ok path for any of these.
    for path in malformed_fixtures() {
        let data = std::fs::read(&path).unwrap();
        let name = path.file_name().unwrap().to_string_lossy().into_owned();
        assert!(
            strip_bytes(&data, &StripOptions::default()).is_err(),
            "{name} was not refused"
        );
    }
}

#[test]
fn a_document_containing_another_container_is_refused_rather_than_partly_cleaned() {
    // ADR-0029 fixes the descent at one level. A nested archive carries its own metadata that
    // this pass cannot reach, so the document is refused and the user learns the file is there.
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../corpus/ooxml/malformed/nested-archive.docx");
    let data = std::fs::read(path).unwrap();
    assert!(matches!(
        strip_bytes(&data, &StripOptions::default()),
        Err(StryptError::Malformed { .. })
    ));
}

#[test]
fn an_encrypted_entry_is_refused_rather_than_reported_clean() {
    // strypt cannot inspect what it cannot read, and a document reported clean on the strength
    // of parts nobody examined is the failure this whole project exists to prevent.
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../corpus/ooxml/malformed/encrypted-entry.docx");
    let data = std::fs::read(path).unwrap();
    assert!(strip_bytes(&data, &StripOptions::default()).is_err());
}

#[test]
fn truncating_a_package_anywhere_never_panics() {
    let data = fixture("everything.docx");
    for n in (0..data.len()).step_by(7) {
        let prefix = &data[0..n];
        let _ = inspect_bytes(prefix, &InspectOptions::names_only());
        let _ = strip_bytes(prefix, &StripOptions::default());
    }
}

#[test]
fn flipping_any_single_byte_never_panics() {
    // Cheap structured fuzzing in the test suite: it catches the parse paths that only a
    // corrupted length field reaches, without waiting for a fuzz run.
    let data = fixture("clean.docx");
    for index in (0..data.len()).step_by(3) {
        let mut mutated = data.clone();
        mutated[index] ^= 0xFF;
        let _ = inspect_bytes(&mutated, &InspectOptions::names_only());
        let _ = strip_bytes(&mutated, &StripOptions::default());
    }
}

// ---------------------------------------------------------------------------------------------
// Reporting
// ---------------------------------------------------------------------------------------------

#[test]
fn a_clean_document_produces_no_findings_beyond_its_container() {
    // A tool that invents findings teaches users to ignore it. The entry timestamps are the one
    // legitimate finding here, and they are real.
    let report = inspect_bytes(&fixture("clean.docx"), &InspectOptions::names_only()).unwrap();
    assert!(
        report
            .findings
            .iter()
            .all(|f| f.location == "ZIP entry headers"),
        "unexpected findings in a clean document: {:?}",
        report.findings
    );
}

#[test]
fn values_are_withheld_unless_the_caller_asks() {
    // A report is easy to redirect into a file, which recreates the secret the user asked to
    // have destroyed (docs/THREAT_MODEL.md §5.5).
    let names_only = inspect_bytes(
        &fixture("core-properties.docx"),
        &InspectOptions::names_only(),
    )
    .unwrap();
    assert!(names_only.findings.iter().all(|f| f.value.is_none()));

    let with_values = inspect_bytes(
        &fixture("core-properties.docx"),
        &InspectOptions::with_values(),
    )
    .unwrap();
    assert!(
        with_values.findings.iter().any(|f| f.value.is_some()),
        "a caller that opted in must actually get values"
    );
}

#[test]
fn inspect_never_modifies_its_input() {
    let original = fixture("everything.docx");
    let mut copy = original.clone();
    let _ = inspect_bytes(&copy, &InspectOptions::with_values()).unwrap();
    assert_eq!(original, copy);
    copy.clear();
}
