//! End-to-end tests for the PDF handler, over the fixtures in `corpus/pdf`.
//!
//! Each fixture is generated by `corpus/tools/make_pdf_fixtures.py` and documented in
//! `corpus/MANIFEST.md`. The synthetic marker strings — `SYNTHETIC-…-000N` — exist so that a
//! test can assert on the *bytes of the output* rather than on strypt's own report. That
//! distinction is the point: a handler that forgot to remove something would still happily
//! report having removed it, and a test that only reads the report would pass.

// Test code is not reachable from untrusted bytes, which is the boundary the panic-freedom
// lints police (ADR-0006).
#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use strypt_core::error::MalformedDetail;
use strypt_core::formats::StripOptions;
use strypt_core::report::{InspectOptions, MetadataKind, Note};
use strypt_core::{Format, StryptError, detect, inspect_bytes, strip_bytes};

fn fixture(name: &str) -> Vec<u8> {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../corpus/pdf")
        .join(name);
    std::fs::read(&path).unwrap_or_else(|e| panic!("reading fixture {}: {e}", path.display()))
}

fn strip(name: &str) -> Vec<u8> {
    let input = fixture(name);
    strip_bytes(&input, &StripOptions::default())
        .unwrap_or_else(|e| panic!("stripping {name}: {e}"))
        .bytes
}

/// True when `haystack` contains `needle` anywhere in its bytes.
fn contains(haystack: &[u8], needle: &str) -> bool {
    haystack
        .windows(needle.len())
        .any(|w| w == needle.as_bytes())
}

const ALL_FIXTURES: &[&str] = &[
    "info-dictionary.pdf",
    "xmp-packet.pdf",
    "incremental-update.pdf",
    "annotation-author.pdf",
    "form-field.pdf",
    "piece-info.pdf",
    "embedded-file.pdf",
    "clean.pdf",
    "negative-zero-real.pdf",
    "embedded-jpeg.pdf",
    "unexamined-images.pdf",
];

#[test]
fn fixtures_survived_checkout_intact() {
    // Regression test for a corruption that happened *before* any strypt code ran. The
    // fixtures are mostly printable ASCII, so Git classified them as text and — on Windows,
    // where core.autocrlf defaults to true — rewrote every LF to CRLF on checkout. A PDF's
    // cross-reference table is a list of absolute byte offsets, so that shifted all of them
    // and every fixture stopped parsing. Fifteen tests failed on windows-latest and none
    // anywhere else, which is a confusing signal to receive if you assume the handler is at
    // fault.
    //
    // `.gitattributes` marks the fixtures `binary`, which is the actual fix. This test is
    // what notices if that ever stops being true — on any platform, without needing a Windows
    // runner to tell us. The generator emits bare LF and never CRLF, so a CR here means
    // something rewrote the file in transit.
    for name in ALL_FIXTURES {
        let bytes = fixture(name);
        assert!(
            !bytes.windows(2).any(|w| w == b"\r\n"),
            "{name} contains CRLF: it was converted on checkout, not committed that way. \
             Check .gitattributes."
        );
    }
}

#[test]
fn the_information_dictionary_is_reported_and_removed() {
    let input = fixture("info-dictionary.pdf");
    let report = inspect_bytes(&input, &InspectOptions::names_only()).unwrap();

    let fields: Vec<&str> = report
        .findings
        .iter()
        .filter_map(|f| f.field.as_deref())
        .collect();
    for expected in [
        "Author",
        "Creator",
        "Producer",
        "Title",
        "Subject",
        "Keywords",
        "CreationDate",
        "ModDate",
        // A key the PDF specification never defined. Applications invent these freely, and a
        // handler that only knows the standard nine would walk straight past it.
        "CustomVendorField",
    ] {
        assert!(
            fields.contains(&expected),
            "no finding for {expected}: {fields:?}"
        );
    }

    let out = strip("info-dictionary.pdf");
    assert!(!contains(&out, "SYNTHETIC-AUTHOR-0001"));
    assert!(!contains(&out, "SYNTHETIC-CUSTOM-0002"));
    assert!(!contains(&out, "Quarterly Fixture"));
    assert!(!contains(&out, "strypt fixture generator"));
}

#[test]
fn a_default_report_names_fields_but_not_their_values() {
    // A report is easy to redirect into a file or paste into an issue. The default must not
    // turn it into a durable copy of what the user just asked to have destroyed
    // (docs/THREAT_MODEL.md §5.5).
    let input = fixture("info-dictionary.pdf");
    let report = inspect_bytes(&input, &InspectOptions::names_only()).unwrap();
    assert!(report.has_findings());
    assert!(
        report.findings.iter().all(|f| f.value.is_none()),
        "values leaked into a names-only report"
    );

    let with_values = inspect_bytes(&input, &InspectOptions::with_values()).unwrap();
    assert!(
        with_values.findings.iter().any(|f| f.value.is_some()),
        "opting in produced no values at all"
    );
}

#[test]
fn a_superseded_revisions_author_does_not_survive() {
    // The fixture that justifies ADR-0020. This document was saved twice; the first save's
    // author is still physically in the file, referenced by nothing, readable in a hex
    // editor. Patching the current Info dictionary — the fast, faithful, obvious approach —
    // leaves it exactly where it is and reports the file clean.
    let input = fixture("incremental-update.pdf");
    assert!(
        contains(&input, "SYNTHETIC-ORPHANED-AUTHOR-0005"),
        "the fixture no longer contains the orphaned author; it is testing nothing"
    );

    let out = strip("incremental-update.pdf");
    assert!(
        !contains(&out, "SYNTHETIC-ORPHANED-AUTHOR-0005"),
        "an earlier revision's author survived the strip"
    );
    assert!(!contains(&out, "SYNTHETIC-SECOND-PASS-0006"));
}

#[test]
fn a_multi_revision_document_says_so() {
    // The user is entitled to know their file contained earlier drafts of itself, whether or
    // not strypt cleaned them up.
    let input = fixture("incremental-update.pdf");
    let report = inspect_bytes(&input, &InspectOptions::names_only()).unwrap();
    assert!(
        report
            .notes
            .iter()
            .any(|n| matches!(n, Note::IncrementalHistory { revisions } if *revisions >= 1)),
        "no incremental-history note: {:?}",
        report.notes
    );
}

#[test]
fn an_xmp_packet_is_broken_down_and_removed() {
    let input = fixture("xmp-packet.pdf");
    let report = inspect_bytes(&input, &InspectOptions::names_only()).unwrap();

    let kinds: Vec<MetadataKind> = report.findings.iter().map(|f| f.kind).collect();
    assert!(kinds.contains(&MetadataKind::PersonalIdentity), "{kinds:?}");
    assert!(
        kinds.contains(&MetadataKind::DocumentIdentifier),
        "{kinds:?}"
    );
    assert!(
        kinds.contains(&MetadataKind::SoftwareFingerprint),
        "{kinds:?}"
    );

    let out = strip("xmp-packet.pdf");
    assert!(!contains(&out, "SYNTHETIC-XMP-AUTHOR-0003"));
    assert!(!contains(&out, "xmpMM:DocumentID"));
    assert!(!contains(&out, "xpacket"));
}

#[test]
fn an_annotations_author_is_removed_but_its_comment_is_not() {
    // The comment is content. strypt removes metadata, not information
    // (docs/THREAT_MODEL.md §4.1) — silently deleting a reviewer's remarks would be a
    // different tool.
    let out = strip("annotation-author.pdf");
    assert!(
        !contains(&out, "SYNTHETIC-REVIEWER-0007"),
        "annotation author survived"
    );
    assert!(
        contains(&out, "a review comment"),
        "the annotation's content was destroyed along with its metadata"
    );
}

#[test]
fn a_form_fields_name_is_left_alone() {
    // /T means two different things depending on the annotation subtype: the author on a
    // markup annotation, the field name on a widget. Stripping the second breaks the form and
    // its saved data. Breaking a user's document to protect them is not a trade this tool
    // makes silently.
    let out = strip("form-field.pdf");
    assert!(
        contains(&out, "applicant_surname"),
        "a form field's name was removed, which breaks the form"
    );
}

#[test]
fn private_application_scratch_data_is_removed() {
    let out = strip("piece-info.pdf");
    assert!(!contains(&out, "SYNTHETIC-PIECEINFO-0008"));
    assert!(!contains(&out, "PieceInfo"));
    assert!(!contains(&out, "LastModified"));
}

#[test]
fn an_attachment_is_flagged_as_something_strypt_does_not_open() {
    // Over-trust is a threat this tool creates through its own confidence
    // (docs/THREAT_MODEL.md §5.6). An attachment carrying its own metadata inside a document
    // reported clean is exactly that, so the report says plainly that strypt did not look.
    let input = fixture("embedded-file.pdf");
    let report = inspect_bytes(&input, &InspectOptions::names_only()).unwrap();
    assert!(
        report
            .notes
            .iter()
            .any(|n| matches!(n, Note::OutOfScopeContent { .. })),
        "no out-of-scope note for an embedded file: {:?}",
        report.notes
    );

    let out = strip("embedded-file.pdf");
    assert!(
        contains(&out, "attached file contents"),
        "the attachment itself must be preserved"
    );
    assert!(
        !contains(&out, "D:20200105000000Z"),
        "attachment CreationDate survived"
    );
}

#[test]
fn a_photos_exif_inside_a_pdf_is_removed_from_the_page_and_its_thumbnail() {
    // Regression test (ADR-0056): 0.1.0 reported this file clean
    // while the placed photo and the page thumbnail both kept their GPS, serial and artist.
    let input = fixture("embedded-jpeg.pdf");
    let report = inspect_bytes(&input, &InspectOptions::names_only()).unwrap();
    let located = report
        .findings
        .iter()
        .filter(|f| f.kind == MetadataKind::Location)
        .count();
    assert_eq!(
        located, 8,
        "GPS not reported for both images: {:?}",
        report.findings
    );

    let out = strip("embedded-jpeg.pdf");
    for marker in [
        "SYNTHETIC-ARTIST-0004",
        "SYNTHETIC-BODY-SERIAL-0005",
        "Exif\0\0",
    ] {
        assert!(
            !contains(&out, marker),
            "{marker} survived inside an embedded JPEG"
        );
    }
}

#[test]
fn an_embedded_jpeg_is_stripped_by_the_same_handler_as_a_loose_one() {
    // ADR-0029's rule, which ADR-0056 carries into PDF: no second, weaker JPEG path.
    let path =
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../corpus/jpeg/exif-gps.jpg");
    let loose = strip_bytes(&std::fs::read(path).unwrap(), &StripOptions::default())
        .unwrap()
        .bytes;
    let out = strip("embedded-jpeg.pdf");
    assert!(
        out.windows(loose.len()).any(|w| w == loose.as_slice()),
        "the PDF's JPEG differs from the loose JPEG handler's output"
    );
}

#[test]
fn images_strypt_cannot_open_are_copied_with_a_note() {
    // JPEG 2000 needs a parser strypt does not have, and a Flate-wrapped JPEG needs inflating.
    // Neither is reported clean without saying so.
    let input = fixture("unexamined-images.pdf");
    let report = inspect_bytes(&input, &InspectOptions::names_only()).unwrap();
    let unparsed = report
        .notes
        .iter()
        .filter(|n| matches!(n, Note::UnparsedRegion { .. }))
        .count();
    assert_eq!(unparsed, 2, "{:?}", report.notes);
    assert!(contains(
        &strip("unexamined-images.pdf"),
        "SYNTHETIC-JPX-0013"
    ));
}

#[test]
fn a_clean_document_produces_no_findings() {
    // A tool that invents findings on a clean file teaches its users to ignore it.
    let input = fixture("clean.pdf");
    let report = inspect_bytes(&input, &InspectOptions::names_only()).unwrap();
    assert!(
        !report.has_findings(),
        "invented findings on a clean file: {:?}",
        report.findings
    );
}

#[test]
fn stripping_is_idempotent_for_every_fixture() {
    // Invariant 3 in docs/TESTING_STRATEGY.md §1. Byte-identical, not merely equivalent:
    // this is what makes differential testing and the Phase 5 GUI byte-identity check
    // possible at all.
    for name in ALL_FIXTURES {
        let once = strip(name);
        let twice = strip_bytes(&once, &StripOptions::default())
            .unwrap_or_else(|e| panic!("re-stripping {name}: {e}"))
            .bytes;
        assert_eq!(once, twice, "strip is not idempotent for {name}");
    }
}

#[test]
fn stripping_is_deterministic_for_every_fixture() {
    // Invariant 4. Two runs over the same input must agree byte for byte — no clock reads, no
    // random identifiers, no iteration-order dependence.
    for name in ALL_FIXTURES {
        assert_eq!(
            strip(name),
            strip(name),
            "strip is not deterministic for {name}"
        );
    }
}

#[test]
fn stripped_output_re_inspects_clean_for_every_fixture() {
    // Phase 1 exit criterion 5, and the property the pipeline's verification pass depends on.
    for name in ALL_FIXTURES {
        let out = strip(name);
        let report = inspect_bytes(&out, &InspectOptions::names_only()).unwrap();
        assert!(
            !report.has_findings(),
            "{name} still reports findings after stripping: {:?}",
            report.findings
        );
    }
}

#[test]
fn output_is_still_a_pdf_for_every_fixture() {
    for name in ALL_FIXTURES {
        let out = strip(name);
        assert_eq!(
            detect(&out).unwrap(),
            Format::Pdf,
            "{name} stopped being a PDF"
        );
    }
}

#[test]
fn the_document_identifier_is_removed() {
    // /ID is stable across saves of the same document, so it links every copy and every
    // revision of a leaked draft to each other.
    let out = strip("info-dictionary.pdf");
    assert!(!contains(&out, "0123456789ABCDEF"));
}

#[test]
fn truncating_a_fixture_at_any_offset_never_panics() {
    // Malformed input is expected input (ADR-0006). Truncation is the most common real-world
    // corruption and the cheapest exhaustive check available; the fuzz target covers the rest.
    for name in ALL_FIXTURES {
        let input = fixture(name);
        for cut in 0..input.len() {
            let partial = input.get(0..cut).unwrap();
            let _ = inspect_bytes(partial, &InspectOptions::names_only());
            let _ = strip_bytes(partial, &StripOptions::default());
        }
    }
}

#[test]
fn a_single_flipped_byte_never_panics() {
    // Cheap structural fuzzing, run on every `cargo test` so that a regression shows up
    // without waiting for a fuzz job.
    for name in ALL_FIXTURES {
        let input = fixture(name);
        for position in (0..input.len()).step_by(7) {
            let mut mutated = input.clone();
            if let Some(byte) = mutated.get_mut(position) {
                *byte ^= 0xFF;
            }
            let _ = inspect_bytes(&mutated, &InspectOptions::names_only());
            let _ = strip_bytes(&mutated, &StripOptions::default());
        }
    }
}

#[test]
fn a_file_that_is_not_a_pdf_is_refused_rather_than_copied() {
    // The failure that gets someone hurt is a success message about a file that was never
    // processed (docs/THREAT_MODEL.md §5.4).
    let err = strip_bytes(b"PK\x03\x04 not a pdf", &StripOptions::default()).unwrap_err();
    assert!(
        matches!(err, StryptError::UnsupportedFormat { .. }),
        "{err:?}"
    );

    let err = strip_bytes(b"nothing at all", &StripOptions::default()).unwrap_err();
    assert!(matches!(err, StryptError::UnrecognisedFormat), "{err:?}");
}

#[test]
fn a_stream_whose_length_disagrees_with_its_content_is_refused() {
    // Regression test. Found by the `pdf` fuzz target on 2026-08-20, as an idempotence
    // failure, which is what made the underlying bug visible at all.
    //
    // The fixture declares "/Length 45." — a malformed real where §7.3.8.2 requires an
    // integer. lopdf 0.44 parses the document, reports no error, keeps the bad value in the
    // dictionary, and stores *empty* stream content because it cannot find the stream's end.
    //
    // strypt used to accept that, rewrite it, and report "nothing to remove; wrote a clean
    // copy" — while emitting a PDF whose /Length claims 45 bytes over an empty stream, with
    // the page's content silently gone. qpdf called the output corrupt ("expected endstream",
    // "recovered stream length: 1"). A second strip produced different bytes again, which is
    // the non-idempotence the fuzzer tripped over.
    //
    // The verification pass did not catch it because it looks for residual metadata, and an
    // emptied stream has none. So this is pinned here instead.
    let input = fixture("malformed/stream-length-mismatch.pdf");

    let err = strip_bytes(&input, &StripOptions::default()).unwrap_err();
    assert!(
        matches!(
            err,
            StryptError::Malformed {
                format: Format::Pdf,
                detail: strypt_core::MalformedDetail::LengthOutOfRange,
                ..
            }
        ),
        "expected a length-mismatch refusal, got {err:?}"
    );
}

#[test]
fn a_19_byte_xref_entry_is_refused_as_typed_malformed_not_silently_passed() {
    // ISO 32000-1 §7.5.4 fixes each cross-reference entry at exactly 20 bytes, but real
    // producers emit 19 by dropping the padding space before the newline. `lopdf` 0.44
    // rejects the trailer when they do; qpdf --check accepts the same bytes and mat2 strips
    // them successfully. So this is a strypt capability gap against the tools it is compared
    // with, documented in docs/THREAT_MODEL.md §7.5.
    //
    // Found by the Phase 1 real-producer sweep, in a file whose upstream copy carries a real
    // person's name — hence a synthetic reproducer here rather than the file itself
    // (docs/TESTING_STRATEGY.md §3).
    //
    // What this test pins is the *safety* property, which holds regardless of the gap: the
    // refusal is a typed Malformed error, not a panic and — the failure that would actually
    // hurt someone — not a success report on an unprocessed file (CLAUDE.md §3.6).
    let input = fixture("malformed/xref-19-byte-entries.pdf");

    // It still sniffs as a PDF. Refusal happens at parse, not detection; a file rejected as
    // "not a PDF" would send the user looking in entirely the wrong place.
    assert_eq!(detect(&input).unwrap(), Format::Pdf);

    for err in [
        inspect_bytes(&input, &InspectOptions::names_only()).unwrap_err(),
        strip_bytes(&input, &StripOptions::default()).unwrap_err(),
    ] {
        assert!(
            matches!(
                err,
                StryptError::Malformed {
                    format: Format::Pdf,
                    ..
                }
            ),
            "expected a typed Malformed refusal, got {err:?}"
        );
    }
}

#[test]
fn a_negative_zero_real_survives_a_second_strip_unchanged() {
    // Regression test. Found by the pdf fuzz target at 6985s of a two-hour run, via the
    // byte-identical idempotence assertion in the harness — the same invariant that caught the
    // stream-length bug, and the second real PDF defect it has now found. Nothing in the
    // production code was checking this property, which is the argument for keeping invariants
    // in the fuzz targets that duplicate no production check.
    //
    // lopdf writes Real(-0.0) as "-0", dropping the decimal point that made it a real. Reading
    // "-0" back therefore yields Integer(0), which writes as "0" — so one strip and two strips
    // disagreed by a byte, and the type of the value silently changed as well.
    //
    // The fixture is a *valid* PDF: negative zero in a CropBox is entirely legal, so this was
    // reachable from files no user would consider unusual.
    let input = fixture("negative-zero-real.pdf");

    let once = strip_bytes(&input, &StripOptions::default()).unwrap().bytes;
    let twice = strip_bytes(&once, &StripOptions::default()).unwrap().bytes;
    assert_eq!(once, twice, "strip is not idempotent for a negative zero");

    // Pin the mechanism, not just the symptom: no negative zero may reach the output at all.
    // Asserting only idempotence would keep passing if some future change made both passes
    // wrong in the same way.
    let text = String::from_utf8_lossy(&once);
    assert!(
        !text.contains("-0"),
        "a negative zero reached the output: {text}"
    );

    // And the value is still there as zero — normalising must not delete the entry. ISO
    // 32000-1 §7.3.3 gives PDF numbers no signed zero, so this is the same number, not a
    // substituted one.
    assert!(
        text.contains("/CropBox"),
        "CropBox disappeared instead of being normalised: {text}"
    );
}

#[test]
fn a_panic_inside_the_pdf_parser_is_contained_and_reported_as_malformed() {
    // Regression test. Found by the pdf fuzz target at 20833s of an eight-hour run: an integer
    // overflow inside lopdf 0.44.0's cross-reference parser (`parser/mod.rs:516`, computing
    // `start + index` where `start` comes from the file). Because Cargo.toml deliberately
    // enables overflow-checks in release — an overflow parsing an attacker-controlled field
    // should abort rather than wrap into a nonsensical offset (ADR-0006) — the *shipped*
    // binary panicked with exit 101 on this input, not just the debug build.
    //
    // ADR-0006's no-panic rule cannot be extended into a dependency by wishing (ADR-0018), so
    // the panic is contained at the boundary instead and reported as what it means for the
    // user: the file was not processed. See `strypt_core::panic_guard` for the limits of that.
    //
    // This pins the *safety* property, which is what matters and holds regardless of when
    // lopdf fixes the overflow: a typed refusal, not a crash, and above all not a success
    // report on a file that was never processed (CLAUDE.md §3.6).
    let input = fixture("malformed/xref-start-overflow.pdf");

    // Still sniffs as a PDF: containment happens at parse, not detection.
    assert_eq!(detect(&input).unwrap(), Format::Pdf);

    for err in [
        inspect_bytes(&input, &InspectOptions::names_only()).unwrap_err(),
        strip_bytes(&input, &StripOptions::default()).unwrap_err(),
    ] {
        assert!(
            matches!(
                err,
                StryptError::Malformed {
                    format: Format::Pdf,
                    ..
                }
            ),
            "expected a typed Malformed refusal, got {err:?}"
        );
    }
}

#[test]
fn a_trailer_without_a_root_is_refused_rather_than_processed() {
    // Regression test. Found by the pdf fuzz target at 2832s, as an idempotence failure rather
    // than a crash: stripping the input once produced 609 bytes and stripping that produced 485.
    //
    // ISO 32000-1 §7.5.5 makes /Root a required trailer entry — it names the document catalogue,
    // the root every other object hangs off. Without it, the reachability walk that ADR-0020's
    // full rewrite depends on has no defined starting point, so which objects survive is not
    // stable between runs. The second pass dropped an annotation object that the page still
    // referenced through /Annots, and renumbering then moved the catalogue into that slot — so
    // the page's annotation array pointed at the document catalogue. strypt introduced that
    // corruption itself while returning success both times, which is the fail-open shape
    // CLAUDE.md §3.6 calls the most dangerous bug class here.
    //
    // The fix refuses instead. This pins the refusal as *typed*, so that a future change which
    // starts accepting these files has to be a deliberate one.
    let input = fixture("malformed/no-root-trailer.pdf");

    // Detection is unaffected: this is still recognisably a PDF, and refusing it as "unsupported
    // format" would tell the user something false about why it was rejected.
    assert_eq!(detect(&input).unwrap(), Format::Pdf);

    for err in [
        inspect_bytes(&input, &InspectOptions::names_only()).unwrap_err(),
        strip_bytes(&input, &StripOptions::default()).unwrap_err(),
    ] {
        assert!(
            matches!(
                err,
                StryptError::Malformed {
                    format: Format::Pdf,
                    detail: MalformedDetail::MissingMarker,
                    ..
                }
            ),
            "expected a MissingMarker refusal, got {err:?}"
        );
    }
}

#[test]
fn a_pdf_that_is_accepted_still_has_a_root_to_walk_from() {
    // The guard above is only as good as its reach: if some other path into the handler skipped
    // it, the instability would come back through that path. Every fixture strypt accepts must
    // therefore have a /Root, and the ones it refuses are refused for a stated reason rather
    // than by accident.
    for name in ALL_FIXTURES {
        let input = fixture(name);
        if strip_bytes(&input, &StripOptions::default()).is_ok() {
            assert!(
                input.windows(5).any(|w| w == b"/Root"),
                "{name} was accepted but has no /Root — the refusal was bypassed"
            );
        }
    }
}

#[test]
fn a_self_referential_page_tree_strips_to_the_same_bytes_twice() {
    // Regression test. Found by the pdf fuzz target at 5268s of a twelve-hour seven-target run
    // on 2026-08-23, through the byte-identical idempotence assertion in the harness — the third
    // real defect that one assertion has now caught, after the stream-length bug and negative
    // zero. Production code checked this property nowhere.
    //
    // The fixture's page tree refers to itself: object 2 is a /Page whose own /Kids array lists
    // object 2. Pruning and renumbering therefore changed both which objects page_iter yields
    // and the order it yields them in, and `lopdf::renumber_objects` reorders page objects when
    // page order does not match ascending ids. So the first strip left pages ordered [3, 2] and
    // the second swapped them: same length, same content, 145 differing bytes.
    //
    // It converged from the third strip onward, which is why this is stated as first-versus-
    // second and not as a loop. "Stable eventually" is not the invariant — a user who strips a
    // file twice must not get two different files.
    let input = fixture("malformed/self-referential-page-tree.pdf");

    let once = strip_bytes(&input, &StripOptions::default()).unwrap().bytes;
    let twice = strip_bytes(&once, &StripOptions::default()).unwrap().bytes;
    assert_eq!(
        once, twice,
        "strip is not idempotent for a self-referential page tree"
    );

    // Pin the mechanism rather than only the symptom. Asserting idempotence alone would keep
    // passing if a later change made the numbering stable at some state that still moved a page
    // between the input and the first output.
    let thrice = strip_bytes(&twice, &StripOptions::default()).unwrap().bytes;
    assert_eq!(twice, thrice, "strip stopped converging after two passes");
}

#[test]
fn output_that_does_not_read_back_as_written_is_refused_not_returned() {
    // Regression test. Found by the pdf fuzz target at 27998s of a twelve-hour seven-target run
    // on 2026-08-24, through the byte-identical idempotence assertion — the fourth real PDF
    // defect that one assertion has caught.
    //
    // The fixture's page object carries keys built from mangled bytes (`/Annotst 1 /[...`).
    // lopdf parses that leniently and then writes it back in a form it cannot itself read, so
    // the object is written and is gone when the file is next opened. strypt's output was
    // therefore a document whose /Pages node claimed /Count 1 with a /Kids array pointing at an
    // object that no longer existed — and strypt reported success. Stripping that output pruned
    // what had become unreachable and produced a 230-byte file with a dangling page reference,
    // reporting success a second time.
    //
    // What this pins is the fail-closed property (CLAUDE.md §3 rule 6). The refusal is a typed
    // error and *nothing is returned*, which is the part that matters: a user acts on a success
    // report by publishing, and the previous behaviour handed them a broken document while
    // telling them it was clean.
    let input = fixture("malformed/unfaithful-rewrite-page-lost.pdf");

    // It still sniffs as a PDF — the refusal happens at rewrite, not detection.
    assert_eq!(detect(&input).unwrap(), Format::Pdf);

    let err = strip_bytes(&input, &StripOptions::default()).unwrap_err();
    assert!(
        matches!(
            err,
            StryptError::Malformed {
                format: Format::Pdf,
                detail: MalformedDetail::NotRoundTrippable,
                ..
            }
        ),
        "expected a round-trip refusal, got {err:?}"
    );

    // The message a user sees must say nothing was written, since that is the fact they need
    // in order to know the original is still their only copy.
    let text = err.to_string();
    assert!(
        text.contains("nothing was written"),
        "refusal does not say the output was withheld: {text}"
    );
}

#[test]
fn an_unknown_offset_is_not_rendered_as_debug_syntax() {
    // The Malformed message used to format its Option offset with {:?}, so a refusal with no
    // known position read "malformed PDF at byte offset None". That is debug syntax shown to
    // someone deciding whether a document is safe to publish.
    let err = strip_bytes(
        &fixture("malformed/xref-start-overflow.pdf"),
        &StripOptions::default(),
    )
    .unwrap_err();
    let text = err.to_string();
    assert!(!text.contains("None"), "debug syntax leaked into: {text}");
    assert!(!text.contains("Some("), "debug syntax leaked into: {text}");
}
