//! End-to-end tests for the PDF handler, over the fixtures in `corpus/pdf`.
//!
//! Each fixture is generated by `corpus/tools/make_pdf_fixtures.py` and documented in
//! `corpus/MANIFEST.md`. The synthetic marker strings — `SYNTHETIC-…-000N` — exist so that a
//! test can assert on the *bytes of the output* rather than on strypt's own report. That
//! distinction is the point: a handler that forgot to remove something would still happily
//! report having removed it, and a test that only reads the report would pass.

// Test code is not reachable from untrusted bytes, which is the boundary the panic-freedom
// lints police (ADR-0006).
#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use strypt_core::formats::StripOptions;
use strypt_core::report::{InspectOptions, MetadataKind, Note};
use strypt_core::{Format, StryptError, detect, inspect_bytes, strip_bytes};

fn fixture(name: &str) -> Vec<u8> {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../corpus/pdf")
        .join(name);
    std::fs::read(&path).unwrap_or_else(|e| panic!("reading fixture {}: {e}", path.display()))
}

fn strip(name: &str) -> Vec<u8> {
    let input = fixture(name);
    strip_bytes(&input, &StripOptions::default())
        .unwrap_or_else(|e| panic!("stripping {name}: {e}"))
        .bytes
}

/// True when `haystack` contains `needle` anywhere in its bytes.
fn contains(haystack: &[u8], needle: &str) -> bool {
    haystack
        .windows(needle.len())
        .any(|w| w == needle.as_bytes())
}

const ALL_FIXTURES: &[&str] = &[
    "info-dictionary.pdf",
    "xmp-packet.pdf",
    "incremental-update.pdf",
    "annotation-author.pdf",
    "form-field.pdf",
    "piece-info.pdf",
    "embedded-file.pdf",
    "clean.pdf",
];

#[test]
fn fixtures_survived_checkout_intact() {
    // Regression test for a corruption that happened *before* any strypt code ran. The
    // fixtures are mostly printable ASCII, so Git classified them as text and — on Windows,
    // where core.autocrlf defaults to true — rewrote every LF to CRLF on checkout. A PDF's
    // cross-reference table is a list of absolute byte offsets, so that shifted all of them
    // and every fixture stopped parsing. Fifteen tests failed on windows-latest and none
    // anywhere else, which is a confusing signal to receive if you assume the handler is at
    // fault.
    //
    // `.gitattributes` marks the fixtures `binary`, which is the actual fix. This test is
    // what notices if that ever stops being true — on any platform, without needing a Windows
    // runner to tell us. The generator emits bare LF and never CRLF, so a CR here means
    // something rewrote the file in transit.
    for name in ALL_FIXTURES {
        let bytes = fixture(name);
        assert!(
            !bytes.windows(2).any(|w| w == b"\r\n"),
            "{name} contains CRLF: it was converted on checkout, not committed that way. \
             Check .gitattributes."
        );
    }
}

#[test]
fn the_information_dictionary_is_reported_and_removed() {
    let input = fixture("info-dictionary.pdf");
    let report = inspect_bytes(&input, &InspectOptions::names_only()).unwrap();

    let fields: Vec<&str> = report
        .findings
        .iter()
        .filter_map(|f| f.field.as_deref())
        .collect();
    for expected in [
        "Author",
        "Creator",
        "Producer",
        "Title",
        "Subject",
        "Keywords",
        "CreationDate",
        "ModDate",
        // A key the PDF specification never defined. Applications invent these freely, and a
        // handler that only knows the standard nine would walk straight past it.
        "CustomVendorField",
    ] {
        assert!(
            fields.contains(&expected),
            "no finding for {expected}: {fields:?}"
        );
    }

    let out = strip("info-dictionary.pdf");
    assert!(!contains(&out, "SYNTHETIC-AUTHOR-0001"));
    assert!(!contains(&out, "SYNTHETIC-CUSTOM-0002"));
    assert!(!contains(&out, "Quarterly Fixture"));
    assert!(!contains(&out, "strypt fixture generator"));
}

#[test]
fn a_default_report_names_fields_but_not_their_values() {
    // A report is easy to redirect into a file or paste into an issue. The default must not
    // turn it into a durable copy of what the user just asked to have destroyed
    // (docs/THREAT_MODEL.md §5.5).
    let input = fixture("info-dictionary.pdf");
    let report = inspect_bytes(&input, &InspectOptions::names_only()).unwrap();
    assert!(report.has_findings());
    assert!(
        report.findings.iter().all(|f| f.value.is_none()),
        "values leaked into a names-only report"
    );

    let with_values = inspect_bytes(&input, &InspectOptions::with_values()).unwrap();
    assert!(
        with_values.findings.iter().any(|f| f.value.is_some()),
        "opting in produced no values at all"
    );
}

#[test]
fn a_superseded_revisions_author_does_not_survive() {
    // The fixture that justifies ADR-0020. This document was saved twice; the first save's
    // author is still physically in the file, referenced by nothing, readable in a hex
    // editor. Patching the current Info dictionary — the fast, faithful, obvious approach —
    // leaves it exactly where it is and reports the file clean.
    let input = fixture("incremental-update.pdf");
    assert!(
        contains(&input, "SYNTHETIC-ORPHANED-AUTHOR-0005"),
        "the fixture no longer contains the orphaned author; it is testing nothing"
    );

    let out = strip("incremental-update.pdf");
    assert!(
        !contains(&out, "SYNTHETIC-ORPHANED-AUTHOR-0005"),
        "an earlier revision's author survived the strip"
    );
    assert!(!contains(&out, "SYNTHETIC-SECOND-PASS-0006"));
}

#[test]
fn a_multi_revision_document_says_so() {
    // The user is entitled to know their file contained earlier drafts of itself, whether or
    // not strypt cleaned them up.
    let input = fixture("incremental-update.pdf");
    let report = inspect_bytes(&input, &InspectOptions::names_only()).unwrap();
    assert!(
        report
            .notes
            .iter()
            .any(|n| matches!(n, Note::IncrementalHistory { revisions } if *revisions >= 1)),
        "no incremental-history note: {:?}",
        report.notes
    );
}

#[test]
fn an_xmp_packet_is_broken_down_and_removed() {
    let input = fixture("xmp-packet.pdf");
    let report = inspect_bytes(&input, &InspectOptions::names_only()).unwrap();

    let kinds: Vec<MetadataKind> = report.findings.iter().map(|f| f.kind).collect();
    assert!(kinds.contains(&MetadataKind::PersonalIdentity), "{kinds:?}");
    assert!(
        kinds.contains(&MetadataKind::DocumentIdentifier),
        "{kinds:?}"
    );
    assert!(
        kinds.contains(&MetadataKind::SoftwareFingerprint),
        "{kinds:?}"
    );

    let out = strip("xmp-packet.pdf");
    assert!(!contains(&out, "SYNTHETIC-XMP-AUTHOR-0003"));
    assert!(!contains(&out, "xmpMM:DocumentID"));
    assert!(!contains(&out, "xpacket"));
}

#[test]
fn an_annotations_author_is_removed_but_its_comment_is_not() {
    // The comment is content. strypt removes metadata, not information
    // (docs/THREAT_MODEL.md §4.1) — silently deleting a reviewer's remarks would be a
    // different tool.
    let out = strip("annotation-author.pdf");
    assert!(
        !contains(&out, "SYNTHETIC-REVIEWER-0007"),
        "annotation author survived"
    );
    assert!(
        contains(&out, "a review comment"),
        "the annotation's content was destroyed along with its metadata"
    );
}

#[test]
fn a_form_fields_name_is_left_alone() {
    // /T means two different things depending on the annotation subtype: the author on a
    // markup annotation, the field name on a widget. Stripping the second breaks the form and
    // its saved data. Breaking a user's document to protect them is not a trade this tool
    // makes silently.
    let out = strip("form-field.pdf");
    assert!(
        contains(&out, "applicant_surname"),
        "a form field's name was removed, which breaks the form"
    );
}

#[test]
fn private_application_scratch_data_is_removed() {
    let out = strip("piece-info.pdf");
    assert!(!contains(&out, "SYNTHETIC-PIECEINFO-0008"));
    assert!(!contains(&out, "PieceInfo"));
    assert!(!contains(&out, "LastModified"));
}

#[test]
fn an_attachment_is_flagged_as_something_strypt_does_not_open() {
    // Over-trust is a threat this tool creates through its own confidence
    // (docs/THREAT_MODEL.md §5.6). An attachment carrying its own metadata inside a document
    // reported clean is exactly that, so the report says plainly that strypt did not look.
    let input = fixture("embedded-file.pdf");
    let report = inspect_bytes(&input, &InspectOptions::names_only()).unwrap();
    assert!(
        report
            .notes
            .iter()
            .any(|n| matches!(n, Note::OutOfScopeContent { .. })),
        "no out-of-scope note for an embedded file: {:?}",
        report.notes
    );

    let out = strip("embedded-file.pdf");
    assert!(
        contains(&out, "attached file contents"),
        "the attachment itself must be preserved"
    );
    assert!(
        !contains(&out, "D:20200105000000Z"),
        "attachment CreationDate survived"
    );
}

#[test]
fn a_clean_document_produces_no_findings() {
    // A tool that invents findings on a clean file teaches its users to ignore it.
    let input = fixture("clean.pdf");
    let report = inspect_bytes(&input, &InspectOptions::names_only()).unwrap();
    assert!(
        !report.has_findings(),
        "invented findings on a clean file: {:?}",
        report.findings
    );
}

#[test]
fn stripping_is_idempotent_for_every_fixture() {
    // Invariant 3 in docs/TESTING_STRATEGY.md §1. Byte-identical, not merely equivalent:
    // this is what makes differential testing and the Phase 5 GUI byte-identity check
    // possible at all.
    for name in ALL_FIXTURES {
        let once = strip(name);
        let twice = strip_bytes(&once, &StripOptions::default())
            .unwrap_or_else(|e| panic!("re-stripping {name}: {e}"))
            .bytes;
        assert_eq!(once, twice, "strip is not idempotent for {name}");
    }
}

#[test]
fn stripping_is_deterministic_for_every_fixture() {
    // Invariant 4. Two runs over the same input must agree byte for byte — no clock reads, no
    // random identifiers, no iteration-order dependence.
    for name in ALL_FIXTURES {
        assert_eq!(
            strip(name),
            strip(name),
            "strip is not deterministic for {name}"
        );
    }
}

#[test]
fn stripped_output_re_inspects_clean_for_every_fixture() {
    // Phase 1 exit criterion 5, and the property the pipeline's verification pass depends on.
    for name in ALL_FIXTURES {
        let out = strip(name);
        let report = inspect_bytes(&out, &InspectOptions::names_only()).unwrap();
        assert!(
            !report.has_findings(),
            "{name} still reports findings after stripping: {:?}",
            report.findings
        );
    }
}

#[test]
fn output_is_still_a_pdf_for_every_fixture() {
    for name in ALL_FIXTURES {
        let out = strip(name);
        assert_eq!(
            detect(&out).unwrap(),
            Format::Pdf,
            "{name} stopped being a PDF"
        );
    }
}

#[test]
fn the_document_identifier_is_removed() {
    // /ID is stable across saves of the same document, so it links every copy and every
    // revision of a leaked draft to each other.
    let out = strip("info-dictionary.pdf");
    assert!(!contains(&out, "0123456789ABCDEF"));
}

#[test]
fn truncating_a_fixture_at_any_offset_never_panics() {
    // Malformed input is expected input (ADR-0006). Truncation is the most common real-world
    // corruption and the cheapest exhaustive check available; the fuzz target covers the rest.
    for name in ALL_FIXTURES {
        let input = fixture(name);
        for cut in 0..input.len() {
            let partial = input.get(0..cut).unwrap();
            let _ = inspect_bytes(partial, &InspectOptions::names_only());
            let _ = strip_bytes(partial, &StripOptions::default());
        }
    }
}

#[test]
fn a_single_flipped_byte_never_panics() {
    // Cheap structural fuzzing, run on every `cargo test` so that a regression shows up
    // without waiting for a fuzz job.
    for name in ALL_FIXTURES {
        let input = fixture(name);
        for position in (0..input.len()).step_by(7) {
            let mut mutated = input.clone();
            if let Some(byte) = mutated.get_mut(position) {
                *byte ^= 0xFF;
            }
            let _ = inspect_bytes(&mutated, &InspectOptions::names_only());
            let _ = strip_bytes(&mutated, &StripOptions::default());
        }
    }
}

#[test]
fn a_file_that_is_not_a_pdf_is_refused_rather_than_copied() {
    // The failure that gets someone hurt is a success message about a file that was never
    // processed (docs/THREAT_MODEL.md §5.4).
    let err = strip_bytes(b"PK\x03\x04 not a pdf", &StripOptions::default()).unwrap_err();
    assert!(
        matches!(err, StryptError::UnsupportedFormat { .. }),
        "{err:?}"
    );

    let err = strip_bytes(b"nothing at all", &StripOptions::default()).unwrap_err();
    assert!(matches!(err, StryptError::UnrecognisedFormat), "{err:?}");
}
