//! End-to-end tests for the PNG handler, over the fixtures in `corpus/png`.
//!
//! Each fixture is generated by `corpus/tools/make_png_fixtures.py` and documented in
//! `corpus/MANIFEST.md`. Every one is a real, decodable PNG built from the same 16×16 base
//! image, which is what makes the image-identity test below possible: if two fixtures' `IDAT`
//! bytes differ after stripping, something re-encoded a picture.
//!
//! The synthetic marker strings — `SYNTHETIC-PNG-…-000N` — exist so that a test can assert on
//! the *bytes of the output* rather than on strypt's own report. That distinction is the
//! point: a handler that forgot to remove something would still happily report having removed
//! it. The fixtures' compressed chunks use stored deflate blocks precisely so that this holds
//! for them too — a `zTXt` payload is legal, compressed as far as the format is concerned, and
//! still greppable.

// Test code is not reachable from untrusted bytes, which is the boundary the panic-freedom
// lints police (ADR-0006).
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing,
    clippy::arithmetic_side_effects
)]

use strypt_core::formats::StripOptions;
use strypt_core::report::{InspectOptions, MetadataKind, Note, RetentionReason};
use strypt_core::{Format, detect, inspect_bytes, strip_bytes};

fn fixture(name: &str) -> Vec<u8> {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../corpus/png")
        .join(name);
    std::fs::read(&path).unwrap_or_else(|e| panic!("reading fixture {}: {e}", path.display()))
}

fn strip(name: &str) -> Vec<u8> {
    let input = fixture(name);
    strip_bytes(&input, &StripOptions::default())
        .unwrap_or_else(|e| panic!("stripping {name}: {e}"))
        .bytes
}

/// True when `haystack` contains `needle` anywhere in its bytes.
fn contains(haystack: &[u8], needle: &str) -> bool {
    haystack
        .windows(needle.len())
        .any(|w| w == needle.as_bytes())
}

/// Every `IDAT` payload in the file, concatenated. This is the picture; nothing strypt does
/// may change a byte of it.
///
/// Walks the chunk list rather than searching for a byte pattern, because `IDAT` is compressed
/// data that can contain anything, including the bytes of another chunk header.
fn image_data(data: &[u8]) -> Vec<u8> {
    let mut out = Vec::new();
    let mut at = 8;
    while let (Some(length), Some(kind)) = (
        data.get(at..at + 4).and_then(|b| b.try_into().ok()),
        data.get(at + 4..at + 8),
    ) {
        let length = u32::from_be_bytes(length) as usize;
        if kind == b"IDAT" {
            out.extend_from_slice(data.get(at + 8..at + 8 + length).expect("truncated IDAT"));
        }
        if kind == b"IEND" {
            break;
        }
        at += length + 12;
    }
    assert!(!out.is_empty(), "no image data found");
    out
}

const ALL_FIXTURES: &[&str] = &[
    "text-chunks.png",
    "thumbnail-uri.png",
    "compressed-text.png",
    "xmp-packet.png",
    "xmp-compressed.png",
    "exif-gps.png",
    "icc-profile.png",
    "timestamp.png",
    "raw-profile.png",
    "unknown-chunks.png",
    "rendering-chunks.png",
    "trailing-data.png",
    "clean.png",
];

/// Every synthetic marker any fixture carries. None may appear in any output.
///
/// `PRESERVED-PNG-CRITICAL-0014` is deliberately absent: it lives in an unknown critical
/// chunk, which strypt keeps on purpose, and it has its own test below.
const ALL_MARKERS: &[&str] = &[
    "SYNTHETIC-PNG-AUTHOR-0001",
    "SYNTHETIC-PNG-SOFTWARE-0002",
    "SYNTHETIC-PNG-COMMENT-0003",
    "SYNTHETIC-PNG-USER-0004",
    "SYNTHETIC-PNG-ZTXT-0005",
    "SYNTHETIC-PNG-XMP-CREATOR-0006",
    "SYNTHETIC-PNG-XMP-TOOL-0007",
    "SYNTHETIC-PNG-DOCUMENT-ID-0008",
    "SYNTHETIC-PNG-CAMERA-MAKE-0009",
    "SYNTHETIC-PNG-CAMERA-MODEL-0010",
    "SYNTHETIC-PNG-ICC-PROFILE-BODY-0011",
    "SYNTHETIC-PNG-ICC-VENDOR-0012",
    "SYNTHETIC-PNG-PREVIEW-0013",
    "SYNTHETIC-PNG-SECOND-IMAGE-0016",
];

/// Deliberately broken files. Each is a shape a real parser bug would hide behind.
const MALFORMED_FIXTURES: &[&str] = &[
    "malformed/length-past-end.png",
    "malformed/length-high-bit.png",
    "malformed/no-iend.png",
    "malformed/bad-chunk-type.png",
    "malformed/no-ihdr.png",
    "malformed/text-without-separator.png",
];

#[test]
fn every_fixture_is_recognised_as_a_png_by_its_content() {
    for name in ALL_FIXTURES {
        assert_eq!(detect(&fixture(name)).unwrap(), Format::Png, "{name}");
    }
}

#[test]
fn no_synthetic_marker_survives_any_strip() {
    // The assertion that matters, and the one that does not trust strypt's own report: the
    // bytes are simply not there afterwards.
    for name in ALL_FIXTURES {
        let output = strip(name);
        for marker in ALL_MARKERS {
            assert!(
                !contains(&output, marker),
                "{marker} survived stripping {name}"
            );
        }
    }
}

#[test]
fn the_picture_is_never_re_encoded() {
    // Every fixture is the same base image with different metadata around it, so after
    // stripping, every one must have byte-identical image data. PNG is a lossless format: a
    // user who chose it chose exactness, and a re-encode would betray that even if it happened
    // to decode to the same pixels.
    let reference = image_data(&strip("clean.png"));
    for name in ALL_FIXTURES {
        assert_eq!(
            image_data(&strip(name)),
            reference,
            "{name} re-encoded the image"
        );
    }
}

#[test]
fn a_clean_file_comes_back_byte_identical() {
    // Stronger than "no findings were reported": kept chunks are copied as raw bytes, so a
    // file with nothing to remove is not re-serialised and cannot be quietly altered.
    let input = fixture("clean.png");
    assert_eq!(strip("clean.png"), input);
}

#[test]
fn stripped_output_inspects_clean() {
    for name in ALL_FIXTURES {
        let output = strip(name);
        let report = inspect_bytes(&output, &InspectOptions::names_only()).unwrap();
        assert!(
            report.findings.is_empty(),
            "{name} still reports {:?} after stripping",
            report.findings
        );
    }
}

#[test]
fn stripping_is_idempotent_byte_for_byte() {
    for name in ALL_FIXTURES {
        let once = strip(name);
        let twice = strip_bytes(&once, &StripOptions::default()).unwrap().bytes;
        assert_eq!(once, twice, "{name} is not idempotent");
    }
}

#[test]
fn a_malformed_file_is_refused_or_cleaned_but_never_mishandled() {
    // Malformed input is expected input (ADR-0006). The requirement is not that every one of
    // these is refused — a text chunk missing its separator should still strip — but that
    // nothing panics, and that anything reported as a success really is clean.
    for name in MALFORMED_FIXTURES {
        let input = fixture(name);
        let _ = inspect_bytes(&input, &InspectOptions::names_only());
        if let Ok(stripped) = strip_bytes(&input, &StripOptions::default()) {
            let report = inspect_bytes(&stripped.bytes, &InspectOptions::names_only())
                .unwrap_or_else(|e| panic!("{name} stripped to something unparseable: {e}"));
            assert!(
                report.findings.is_empty(),
                "{name} was reported clean but is not"
            );
            let again = strip_bytes(&stripped.bytes, &StripOptions::default()).unwrap();
            assert_eq!(stripped.bytes, again.bytes, "{name} is not idempotent");
        }
    }
}

#[test]
fn an_exif_chunk_reports_its_location_and_device_by_name() {
    // "an eXIf chunk was removed" is not useful to someone deciding whether a file they
    // already published is a problem. The field names are.
    let report = inspect_bytes(&fixture("exif-gps.png"), &InspectOptions::names_only()).unwrap();
    let fields: Vec<&str> = report
        .findings
        .iter()
        .filter_map(|f| f.field.as_deref())
        .collect();
    for expected in ["GPSLatitude", "GPSLongitude", "Make", "Model"] {
        assert!(
            fields.contains(&expected),
            "{expected} was not named: {fields:?}"
        );
    }
}

#[test]
fn an_uncompressed_xmp_packet_is_itemised_and_a_compressed_one_is_not() {
    // The documented cost of carrying no decompressor (ADR-0022): both packets are removed,
    // and only the readable one can be broken down by property.
    let itemised = inspect_bytes(&fixture("xmp-packet.png"), &InspectOptions::names_only())
        .unwrap()
        .findings;
    let fields: Vec<&str> = itemised.iter().filter_map(|f| f.field.as_deref()).collect();
    assert!(fields.contains(&"dc:creator"), "{fields:?}");
    assert!(fields.contains(&"xmpMM:DocumentID"), "{fields:?}");

    let lumped = inspect_bytes(
        &fixture("xmp-compressed.png"),
        &InspectOptions::names_only(),
    )
    .unwrap()
    .findings;
    assert_eq!(lumped.len(), 1);
    assert_eq!(lumped[0].field.as_deref(), Some("Metadata (compressed)"));
}

#[test]
fn a_compressed_text_chunk_is_named_by_its_keyword_and_its_payload_goes() {
    let report = inspect_bytes(
        &fixture("compressed-text.png"),
        &InspectOptions::names_only(),
    )
    .unwrap();
    assert_eq!(report.findings[0].field.as_deref(), Some("Comment"));
    assert_eq!(
        report.findings[0].value, None,
        "the text is behind the compression and is not read"
    );
    assert!(!contains(
        &strip("compressed-text.png"),
        "SYNTHETIC-PNG-ZTXT-0005"
    ));
}

#[test]
fn a_thumbnailers_record_of_the_original_path_is_ranked_as_identifying() {
    // `Thumb::URI` holds the path of the file the thumbnail was made from, so it names a home
    // directory. Filing it under "other text" would bury it below a software name.
    let report =
        inspect_bytes(&fixture("thumbnail-uri.png"), &InspectOptions::names_only()).unwrap();
    assert_eq!(report.findings[0].kind, MetadataKind::PersonalIdentity);
}

#[test]
fn the_rendering_chunks_survive_and_the_physical_size_is_declared_as_kept() {
    // A handler that dropped every ancillary chunk would change how the image looks and prints
    // while claiming only to have removed metadata.
    let input = fixture("rendering-chunks.png");
    let stripped = strip_bytes(&input, &StripOptions::default()).unwrap();
    for kind in ["gAMA", "sRGB", "pHYs", "bKGD"] {
        assert!(contains(&stripped.bytes, kind), "{kind} was dropped");
    }
    let retained = stripped
        .report
        .retained
        .iter()
        .find(|r| r.location == "pHYs")
        .expect("pHYs was kept but not declared in the report");
    assert_eq!(retained.reason, RetentionReason::RemovalWouldAlterPayload);
}

#[test]
fn an_unknown_critical_chunk_is_kept_and_the_report_says_it_was_not_examined() {
    // strypt cannot know what a critical chunk holds or what depends on it, so it copies the
    // bytes through. Keeping it silently would be the wrong half of the trade: the user is
    // told that bytes went by unexamined, so they can judge that for themselves.
    let stripped = strip_bytes(&fixture("unknown-chunks.png"), &StripOptions::default()).unwrap();
    assert!(
        contains(&stripped.bytes, "PRESERVED-PNG-CRITICAL-0014"),
        "an unknown critical chunk was dropped, which breaks the file"
    );
    assert!(
        stripped
            .report
            .notes
            .iter()
            .any(|n| matches!(n, Note::UnparsedRegion { location, .. } if location == "VeND")),
        "the retained critical chunk was not reported: {:?}",
        stripped.report.notes
    );
}

#[test]
fn data_hidden_after_the_end_chunk_is_removed_and_reported() {
    // A whole second image past `IEND`. Nothing reads it, few users know it can be there, and
    // it is where a cropped picture's uncropped original fits comfortably.
    let stripped = strip_bytes(&fixture("trailing-data.png"), &StripOptions::default()).unwrap();
    assert!(!contains(
        &stripped.bytes,
        "SYNTHETIC-PNG-SECOND-IMAGE-0016"
    ));
    assert_eq!(stripped.report.removed[0].kind, MetadataKind::Thumbnail);
    assert_eq!(
        stripped.report.removed[0].location,
        "trailing data after IEND"
    );
}
