//! End-to-end tests for the SVG handler, over the fixtures in `corpus/svg`.
//!
//! Each fixture is generated by `corpus/tools/make_svg_fixtures.py` and documented in
//! `corpus/MANIFEST.md`. Identifying values are `SYNTHETIC-…-000N` markers so a test can assert on
//! the *bytes of the output* rather than on strypt's own report — a handler that forgot to remove
//! something would still happily report having removed it.
//!
//! A marker spelled `-KEPT-` is one this handler deliberately does not remove: the accessibility
//! text of ADR-0035 §5 and the external path of §3. The sweep excludes them on that spelling, so
//! keeping one stays a decision recorded in the fixture rather than a hole in the sweep.
//!
//! # Why this file carries its own XML walker
//!
//! The claim that matters is that no name outside the prefix allow-list reached the output, and
//! checking it with `strypt_core`'s own scanner would assert only that the scanner agrees with
//! itself. [`names`] walks the output independently, the way `tests/gif.rs` walks a GIF.

// Test code is not reachable from untrusted bytes, which is the boundary the panic-freedom
// lints police (ADR-0006).
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing,
    clippy::arithmetic_side_effects
)]

use strypt_core::error::{StryptError, UnsupportedKind};
use strypt_core::formats::StripOptions;
use strypt_core::report::{InspectOptions, MetadataKind, Note};
use strypt_core::{Format, detect, inspect_bytes, strip_bytes};

fn fixture(name: &str) -> Vec<u8> {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../corpus/svg")
        .join(name);
    std::fs::read(&path).unwrap_or_else(|e| panic!("reading fixture {}: {e}", path.display()))
}

fn strip(name: &str) -> Vec<u8> {
    let input = fixture(name);
    strip_bytes(&input, &StripOptions::default())
        .unwrap_or_else(|e| panic!("stripping {name}: {e}"))
        .bytes
}

fn text(name: &str) -> String {
    String::from_utf8(strip(name)).expect("output is UTF-8")
}

/// Every fixture that is a well-formed SVG the handler is expected to accept.
const FIXTURES: &[&str] = &[
    "clean.svg",
    "metadata-rdf.svg",
    "inkscape.svg",
    "illustrator.svg",
    "xmp-packet.svg",
    "unknown-namespace.svg",
    "embedded-image.svg",
    "embedded-image-xlink.svg",
    "accessibility-text.svg",
    "external-references.svg",
    "stylesheet.svg",
    "doctype.svg",
    "comments.svg",
    "kitchen-sink.svg",
];

const MALFORMED: &[&str] = &[
    "malformed/script-element.svg",
    "malformed/event-handler.svg",
    "malformed/event-handler-nested.svg",
    "malformed/foreign-object.svg",
    "malformed/javascript-href.svg",
    "malformed/entity-subset.svg",
    "malformed/data-uri-pdf.svg",
    "malformed/data-uri-svg.svg",
    "malformed/utf16.svg",
];

/// Every element name and attribute name in a document, found by an independent walk.
///
/// Deliberately written here rather than borrowed from `strypt_core`: see this file's header.
fn names(src: &str) -> Vec<String> {
    let bytes = src.as_bytes();
    let mut out = Vec::new();
    let mut at = 0usize;

    while at < bytes.len() {
        let Some(open) = src[at..].find('<').map(|n| at + n) else {
            break;
        };
        let rest = &src[open..];
        // Step over the constructs whose contents are not markup.
        for (prefix, terminator) in [
            ("<!--", "-->"),
            ("<![CDATA[", "]]>"),
            ("<?", "?>"),
            ("<!", ">"),
        ] {
            if let Some(after) = rest.strip_prefix(prefix) {
                at = after
                    .find(terminator)
                    .map_or(src.len(), |n| open + prefix.len() + n + terminator.len());
                break;
            }
        }
        if at > open {
            continue;
        }

        // The tag's own end, ignoring any `>` inside a quoted value.
        let mut quote = None;
        let mut end = open + 1;
        while end < bytes.len() {
            match (quote, bytes[end]) {
                (Some(q), b) if b == q => quote = None,
                (None, b @ (b'"' | b'\'')) => quote = Some(b),
                (None, b'>') => break,
                _ => {}
            }
            end += 1;
        }
        if end >= bytes.len() {
            break;
        }

        let inner = src[open + 1..end]
            .trim_start_matches('/')
            .trim_end_matches('/');
        let mut words = inner.split(|c: char| c.is_whitespace());
        if let Some(name) = words.next().filter(|n| !n.is_empty()) {
            out.push(name.to_string());
        }
        for word in words {
            if let Some((name, _)) = word.split_once('=')
                && !name.is_empty()
            {
                out.push(name.to_string());
            }
        }
        at = end + 1;
    }
    out
}

/// The `<rect id="PRESERVED-SHAPE" …/>` every fixture carries, as it was written.
fn preserved_shape(src: &str) -> Option<&str> {
    let start = src.find("<rect id=\"PRESERVED-SHAPE\"")?;
    let end = src[start..].find("/>")? + start + 2;
    Some(&src[start..end])
}

#[test]
fn every_fixture_is_detected_as_svg() {
    for name in FIXTURES {
        assert_eq!(
            detect(&fixture(name)).unwrap(),
            Format::Svg,
            "{name} was not detected as SVG"
        );
    }
}

#[test]
fn no_synthetic_marker_survives_unless_it_is_one_the_handler_keeps() {
    // The sweep. Every identifying value in the corpus is a `SYNTHETIC-` marker, so one
    // assertion covers every fixture's comments, packets, and editor attributes at once.
    for name in FIXTURES {
        for tail in text(name).split("SYNTHETIC").skip(1) {
            let marker: String = tail
                .chars()
                .take_while(|c| c.is_ascii_uppercase() || c.is_ascii_digit() || *c == '-')
                .collect();
            assert!(
                marker.contains("-KEPT-"),
                "a synthetic marker survived stripping {name}: SYNTHETIC{marker}"
            );
        }
    }
}

#[test]
fn the_drawing_itself_crosses_untouched() {
    // What separates this handler from mat2's, which re-renders an SVG through Rsvg onto a blank
    // Cairo surface: the shape's own bytes — its id, its ordering, its attribute quoting —
    // appear in the output exactly as the author wrote them.
    for name in FIXTURES {
        let input = String::from_utf8(fixture(name)).unwrap();
        let shape = preserved_shape(&input).unwrap_or_else(|| panic!("{name} has no shape"));
        assert!(
            text(name).contains(shape),
            "{name}: the drawing did not cross the strip intact"
        );
    }
}

#[test]
fn a_clean_file_strips_to_a_byte_identical_copy() {
    // Editing by deletion, so a document with nothing to remove is not rewritten at all. Only
    // GIF makes the same promise here; TIFF and HEIF are rebuilt and cannot (ADR-0033, ADR-0034).
    let input = fixture("clean.svg");
    let stripped = strip_bytes(&input, &StripOptions::default()).unwrap();
    assert!(stripped.report.removed.is_empty());
    assert_eq!(stripped.bytes, input);
}

#[test]
fn no_name_outside_the_prefix_allow_list_reaches_the_output() {
    // ADR-0035 §6, checked by an independent walk. A deny-list would have let
    // `unknown-namespace.svg` through precisely because nothing recognises it.
    for name in FIXTURES {
        for found in names(&text(name)) {
            let offending = match found.strip_prefix("xmlns:") {
                // The declaration binding a prefix goes with the names that used it.
                Some(bound) => !matches!(bound, "xlink" | "xml"),
                None => found
                    .split_once(':')
                    .is_some_and(|(prefix, _)| !matches!(prefix, "xlink" | "xml")),
            };
            assert!(!offending, "{name}: `{found}` survived the allow-list");
        }
    }
}

#[test]
fn the_output_of_every_fixture_re_inspects_clean() {
    // What the pipeline's verification pass does, asserted directly over the corpus.
    for name in FIXTURES {
        let output = strip(name);
        let report = inspect_bytes(&output, &InspectOptions::names_only())
            .unwrap_or_else(|e| panic!("stripped {name} no longer inspects: {e}"));
        assert!(
            report.findings.is_empty(),
            "metadata survived stripping {name}: {:?}",
            report.findings
        );
    }
}

#[test]
fn stripping_is_idempotent_over_the_whole_corpus() {
    for name in FIXTURES {
        let once = strip(name);
        let twice = strip_bytes(&once, &StripOptions::default())
            .unwrap_or_else(|e| panic!("re-stripping {name}: {e}"))
            .bytes;
        assert_eq!(once, twice, "stripping {name} is not idempotent");
    }
}

#[test]
fn a_name_nested_under_an_rdf_agent_is_ranked_as_naming_a_person() {
    // Inkscape writes a creator as `<dc:creator><cc:Agent><dc:title>`, where the leaf is called
    // `title`. Ranking that as a comment would understate it, and sensitivity is what a
    // front-end orders a report by.
    let report =
        inspect_bytes(&fixture("metadata-rdf.svg"), &InspectOptions::names_only()).unwrap();
    assert!(
        report
            .findings
            .iter()
            .any(|f| f.kind == MetadataKind::PersonalIdentity),
        "{:?}",
        report.findings
    );
    assert!(
        report
            .findings
            .iter()
            .any(|f| f.kind == MetadataKind::Timestamp),
        "`dc:date` is a timestamp"
    );
}

#[test]
fn xmp_carried_in_attributes_is_itemised_field_by_field() {
    let report = inspect_bytes(&fixture("xmp-packet.svg"), &InspectOptions::names_only()).unwrap();
    let named: Vec<&str> = report
        .findings
        .iter()
        .filter_map(|f| f.field.as_deref())
        .collect();
    for expected in ["xmp:CreatorTool", "xmp:CreateDate", "xmp:DocumentID"] {
        assert!(
            named.iter().any(|f| f.ends_with(expected)),
            "{expected} was not reported; got {named:?}"
        );
    }
    // The packet's `<?xpacket?>` wrapper is a processing instruction, which the scanner used to
    // step over entirely.
    assert!(!text("xmp-packet.svg").contains("xpacket"));
}

#[test]
fn an_unknown_editors_namespace_does_not_survive_by_being_unknown() {
    // The fixture that justifies the allow-list running in the direction it does.
    let output = text("unknown-namespace.svg");
    assert!(!output.contains("notatoolweveheardof"));
    assert!(output.contains("PRESERVED-SHAPE"));
}

#[test]
fn accessibility_text_is_kept_and_declared_rather_than_quietly_left() {
    // ADR-0035 §5. mat2 removes these; strypt keeps them because they are what a screen reader
    // announces, and says so rather than letting the user assume they went.
    let stripped =
        strip_bytes(&fixture("accessibility-text.svg"), &StripOptions::default()).unwrap();
    let output = String::from_utf8(stripped.bytes).unwrap();
    assert!(output.contains("SYNTHETIC-TITLE-KEPT-0013"));
    assert!(output.contains("SYNTHETIC-DESC-KEPT-0014"));
    for element in ["<title>", "<desc>"] {
        assert!(
            stripped
                .report
                .retained
                .iter()
                .any(|r| r.location == element),
            "{element} was kept without being declared: {:?}",
            stripped.report.retained
        );
    }
}

#[test]
fn an_external_reference_is_kept_and_its_target_never_named_in_the_report() {
    // ADR-0035 §3. Removing it would turn a file that draws a linked logo into one that draws
    // nothing — and the path itself is the leak, so the report must not repeat it.
    let stripped = strip_bytes(
        &fixture("external-references.svg"),
        &StripOptions::default(),
    )
    .unwrap();
    let output = String::from_utf8(stripped.bytes.clone()).unwrap();
    assert!(output.contains("SYNTHETIC-LOCAL-PATH-KEPT-0015"));
    assert!(output.contains("beacon.invalid"));
    assert!(
        output.contains("url(#internal)"),
        "a fragment is not a leak"
    );

    // A `Finding` here would make the verification pass reject strypt's own output.
    assert!(stripped.report.removed.is_empty(), "{stripped:?}");
    assert_eq!(stripped.report.retained.len(), 2);
    let rendered = format!("{:?}{:?}", stripped.report.retained, stripped.report.notes);
    assert!(
        !rendered.contains("SYNTHETIC-LOCAL-PATH-KEPT-0015"),
        "{rendered}"
    );
    assert!(!rendered.contains("beacon.invalid"), "{rendered}");
    assert!(
        stripped
            .report
            .notes
            .iter()
            .any(|n| matches!(n, Note::OutOfScopeContent { .. }))
    );
}

#[test]
fn an_embedded_photograph_is_stripped_and_still_a_picture() {
    // ADR-0029's descent, unchanged, applied to a `data:` URI. Both spellings of the attribute
    // reach it — SVG 2's `href` and SVG 1.1's `xlink:href`.
    for name in ["embedded-image.svg", "embedded-image-xlink.svg"] {
        let output = text(name);
        assert!(!output.contains("SYNTHETIC-EMBEDDED-AUTHOR-0011"));
        let payload = output
            .split("base64,")
            .nth(1)
            .and_then(|rest| rest.split('"').next())
            .unwrap_or_else(|| panic!("{name}: the picture itself was removed"));
        let decoded = base64(payload);
        assert_eq!(
            detect(&decoded).unwrap(),
            Format::Png,
            "{name}: what came back is not a PNG"
        );
        assert!(!decoded.windows(4).any(|w| w == b"tEXt"));
    }
}

#[test]
fn a_stylesheet_loses_its_comments_and_keeps_its_rules() {
    let output = text("stylesheet.svg");
    assert!(!output.contains("SYNTHETIC-CSS-TOOL-0016"));
    // `/*` inside a string is not a comment, and cutting there would corrupt the rule around it.
    assert!(output.contains("SYNTHETIC-NOT-A-COMMENT-KEPT-0017"));
    assert!(output.contains(".shape { fill: #3366cc; }"));
}

#[test]
fn a_doctype_survives_and_the_comments_around_it_do_not() {
    let output = text("doctype.svg");
    assert!(output.starts_with("<?xml version=\"1.0\""), "{output}");
    assert!(output.contains("<!DOCTYPE svg PUBLIC"));
    assert!(!output.contains("SYNTHETIC-DOCTYPE-COMMENT-0018"));
}

#[test]
fn a_comment_is_removed_wherever_in_the_document_it_sits() {
    let output = text("comments.svg");
    assert!(!output.contains("<!--"), "{output}");
    assert!(output.contains("PRESERVED-SHAPE"));
}

#[test]
fn every_document_that_can_execute_code_is_refused_by_name() {
    // ADR-0035 §2, and fail closed (`CLAUDE.md` §3, constraint 6). A partly-cleaned scripted SVG
    // is the outcome that must not exist: the script survives to read whatever is left.
    for name in [
        "malformed/script-element.svg",
        "malformed/event-handler.svg",
        "malformed/event-handler-nested.svg",
        "malformed/foreign-object.svg",
        "malformed/javascript-href.svg",
    ] {
        let error = strip_bytes(&fixture(name), &StripOptions::default())
            .expect_err("a document that can execute code must be refused");
        assert!(
            matches!(
                error,
                StryptError::UnsupportedFormat {
                    format: UnsupportedKind::ScriptedSvg
                }
            ),
            "{name}: {error:?}"
        );
    }
}

#[test]
fn every_malformed_fixture_is_refused_rather_than_half_processed() {
    for name in MALFORMED {
        assert!(
            strip_bytes(&fixture(name), &StripOptions::default()).is_err(),
            "{name} produced output instead of a refusal"
        );
    }
}

#[test]
fn an_svgz_is_refused_rather_than_read_as_the_gzip_stream_it_is() {
    // ADR-0035 §10. Decompressing here would mean writing a re-compressed file whose bytes are
    // an artefact of strypt's compressor rather than of the document.
    let gzipped = [0x1F, 0x8B, 0x08, 0x00, 0, 0, 0, 0, 0, 0x03, b'x', b'y'];
    assert!(matches!(
        strip_bytes(&gzipped, &StripOptions::default()),
        Err(StryptError::UnsupportedFormat {
            format: UnsupportedKind::Gzip
        })
    ));
}

#[test]
fn truncating_any_fixture_anywhere_never_panics() {
    // Malformed input is expected input (ADR-0006). Every prefix of every fixture is a file
    // somebody's damaged upload could be.
    for name in FIXTURES {
        let input = fixture(name);
        for cut in 0..input.len() {
            let _ = inspect_bytes(&input[..cut], &InspectOptions::names_only());
            let _ = strip_bytes(&input[..cut], &StripOptions::default());
        }
    }
}

#[test]
fn flipping_any_single_byte_never_panics() {
    // A cheap fuzz-shaped sweep that runs in CI on every push, where the real fuzz runs do not.
    for name in FIXTURES {
        let input = fixture(name);
        for at in 0..input.len() {
            let mut damaged = input.clone();
            damaged[at] ^= 0xFF;
            let _ = inspect_bytes(&damaged, &InspectOptions::names_only());
            let _ = strip_bytes(&damaged, &StripOptions::default());
        }
    }
}

/// Decode a base64 payload. The test's own, so it is not asserting the handler's codec against
/// itself.
fn base64(payload: &str) -> Vec<u8> {
    const ALPHABET: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut out = Vec::new();
    let (mut accumulator, mut bits) = (0u32, 0u32);
    for byte in payload.bytes().filter(|b| !b.is_ascii_whitespace()) {
        if byte == b'=' {
            break;
        }
        let value = ALPHABET
            .iter()
            .position(|c| *c == byte)
            .unwrap_or_else(|| panic!("`{}` is not a base64 symbol", char::from(byte)));
        accumulator = (accumulator << 6) | u32::try_from(value).unwrap();
        bits += 6;
        if bits >= 8 {
            bits -= 8;
            out.push(u8::try_from((accumulator >> bits) & 0xFF).unwrap());
        }
    }
    out
}
