//! End-to-end tests for the TIFF handler, over the fixtures in `corpus/tiff`.
//!
//! Each fixture is generated by `corpus/tools/make_tiff_fixtures.py` and documented in
//! `corpus/MANIFEST.md`. The synthetic marker strings — `SYNTHETIC-…-000N` — exist so that a
//! test can assert on the *bytes of the output* rather than on strypt's own report. That
//! distinction is the point: a handler that forgot to remove something would still happily
//! report having removed it.
//!
//! Values that must **survive** are prefixed `PRESERVED-`, so the sweep for surviving
//! `SYNTHETIC` markers does not have to be told about them one at a time.
//!
//! # What these tests are really checking
//!
//! TIFF is the one format where strypt does not edit the input but **writes a new file**
//! (ADR-0033). Two consequences shape the tests below. The output is never byte-identical to
//! the input, even for a clean file — so there is no "a clean file strips to a byte-identical
//! copy" test here as there is for PNG, and its place is taken by idempotence, which *is*
//! byte-identical. And the writer computes every offset itself, so the assertion that matters
//! most is not "the metadata is gone" but "the file still parses and still holds the same
//! picture" — a rebuild that got an offset wrong would produce a file that reads clean and
//! shows nothing.

// Test code is not reachable from untrusted bytes, which is the boundary the panic-freedom
// lints police (ADR-0006).
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing,
    clippy::arithmetic_side_effects
)]

use strypt_core::formats::StripOptions;
use strypt_core::report::{InspectOptions, MetadataKind};
use strypt_core::{Format, detect, inspect_bytes, strip_bytes};

fn fixture(name: &str) -> Vec<u8> {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../corpus/tiff")
        .join(name);
    std::fs::read(&path).unwrap_or_else(|e| panic!("reading fixture {}: {e}", path.display()))
}

fn strip(name: &str) -> Vec<u8> {
    let input = fixture(name);
    strip_bytes(&input, &StripOptions::default())
        .unwrap_or_else(|e| panic!("stripping {name}: {e}"))
        .bytes
}

fn contains(haystack: &[u8], needle: &str) -> bool {
    haystack
        .windows(needle.len())
        .any(|w| w == needle.as_bytes())
}

/// Every fixture that is a well-formed TIFF the handler is expected to accept.
const FIXTURES: &[&str] = &[
    "clean.tiff",
    "identifying-tags.tiff",
    "unknown-vendor-tag.tiff",
    "exif-and-gps.tiff",
    "packets.tiff",
    "reduced-resolution-thumbnail.tiff",
    "multi-page.tiff",
    "multi-strip.tiff",
    "palette.tiff",
    "big-endian.tiff",
];

const MALFORMED: &[&str] = &[
    "malformed/bigtiff.tiff",
    "malformed/directory-cycle.tiff",
    "malformed/strip-out-of-range.tiff",
    "malformed/truncated-directory.tiff",
    "malformed/entry-count-lies.tiff",
    "malformed/no-dimensions.tiff",
];

#[test]
fn every_fixture_is_detected_as_tiff() {
    for name in FIXTURES {
        assert_eq!(
            detect(&fixture(name)).unwrap(),
            Format::Tiff,
            "{name} was not detected as TIFF"
        );
    }
}

#[test]
fn no_synthetic_marker_survives_any_fixture() {
    // The sweep. Every identifying value in the corpus is a `SYNTHETIC-` marker, so one
    // assertion covers every tag, every packet, and every sub-directory at once — including
    // the ones no test below names individually.
    for name in FIXTURES {
        let output = strip(name);
        assert!(
            !contains(&output, "SYNTHETIC"),
            "a synthetic marker survived stripping {name}"
        );
    }
}

#[test]
fn the_picture_crosses_the_rebuild_byte_for_byte() {
    // The claim that separates strypt's approach from mat2's default, which re-renders the
    // image through GdkPixbuf (ADR-0033). If this fails, the pixels were touched.
    for name in FIXTURES {
        if *name == "multi-page.tiff" || *name == "multi-strip.tiff" {
            continue; // Their payloads are per-page and per-strip; checked separately below.
        }
        let output = strip(name);
        assert!(
            contains(&output, "PRESERVED-TIFF-PIXELS"),
            "the image data did not survive {name}"
        );
    }
}

#[test]
fn every_page_of_a_multi_page_scan_survives() {
    // The scanned-dossier case. Losing a page would be losing the document.
    let output = strip("multi-page.tiff");
    for page in 1..=3 {
        assert!(
            contains(&output, &format!("PRESERVED-TIFF-PIXELS-PAGE-{page}")),
            "page {page} was lost"
        );
    }
}

#[test]
fn every_strip_of_a_multi_strip_image_survives_in_order() {
    let output = strip("multi-strip.tiff");
    let mut at = 0;
    for strip_marker in [
        "PRESERVED-STRIP-ONE-01",
        "PRESERVED-STRIP-TWO-02",
        "PRESERVED-STRIP-3",
    ] {
        let found = output
            .windows(strip_marker.len())
            .position(|w| w == strip_marker.as_bytes())
            .unwrap_or_else(|| panic!("{strip_marker} missing from the output"));
        assert!(found >= at, "strips were reordered by the rebuild");
        at = found;
    }
}

#[test]
fn the_output_of_every_fixture_re_inspects_clean() {
    // What the pipeline's verification pass does. For a rewriting handler it is also the
    // check that the rebuilt offsets are right: a file whose directory pointed at the wrong
    // bytes would not parse back into the same tags.
    for name in FIXTURES {
        let output = strip(name);
        let report = inspect_bytes(&output, &InspectOptions::names_only())
            .unwrap_or_else(|e| panic!("stripped {name} no longer inspects: {e}"));
        assert!(
            report.findings.is_empty(),
            "metadata survived stripping {name}: {:?}",
            report.findings
        );
    }
}

#[test]
fn stripping_is_idempotent_over_the_whole_corpus() {
    // Byte-identical, which for a handler that rebuilds is the proof that its output is a
    // fixed point of its own reader. This is the invariant that replaces "a clean file is
    // unchanged", which a rebuild cannot offer.
    for name in FIXTURES {
        let once = strip(name);
        let twice = strip_bytes(&once, &StripOptions::default())
            .unwrap_or_else(|e| panic!("re-stripping {name}: {e}"))
            .bytes;
        assert_eq!(once, twice, "stripping {name} is not idempotent");
    }
}

#[test]
fn a_clean_file_is_reported_as_carrying_nothing() {
    let report = inspect_bytes(&fixture("clean.tiff"), &InspectOptions::names_only()).unwrap();
    assert!(
        report.findings.is_empty(),
        "the clean fixture reported findings: {:?}",
        report.findings
    );
    // It is still rebuilt, and the rebuild must still be a valid TIFF.
    let output = strip("clean.tiff");
    assert_eq!(detect(&output).unwrap(), Format::Tiff);
}

#[test]
fn the_ordinary_camera_tags_are_reported_by_name() {
    let report = inspect_bytes(
        &fixture("identifying-tags.tiff"),
        &InspectOptions::names_only(),
    )
    .unwrap();
    let named: Vec<&str> = report
        .findings
        .iter()
        .filter_map(|f| f.field.as_deref())
        .collect();
    for expected in [
        "Make",
        "Model",
        "Software",
        "Artist",
        "DateTime",
        "HostComputer",
        "Copyright",
        "ImageDescription",
    ] {
        assert!(
            named.contains(&expected),
            "{expected} was not reported; got {named:?}"
        );
    }
}

#[test]
fn an_unknown_vendor_tag_is_reported_and_removed() {
    // The fixture that justifies the allow-list running in the direction it does: under a
    // deny-list, a private tag survives precisely because nothing recognises it (ADR-0033).
    let report = inspect_bytes(
        &fixture("unknown-vendor-tag.tiff"),
        &InspectOptions::names_only(),
    )
    .unwrap();
    assert!(
        report.findings.len() >= 2,
        "the private tags were not reported: {:?}",
        report.findings
    );
    let output = strip("unknown-vendor-tag.tiff");
    assert!(!contains(&output, "SYNTHETIC-VENDOR-SERIAL-0009"));
    assert!(!contains(&output, "SYNTHETIC-PRIVATE-0010"));
}

#[test]
fn location_inside_a_gps_sub_directory_is_found_and_removed() {
    let report =
        inspect_bytes(&fixture("exif-and-gps.tiff"), &InspectOptions::names_only()).unwrap();
    assert!(
        report
            .findings
            .iter()
            .any(|f| f.kind == MetadataKind::Location),
        "no location finding from a file with a GPS IFD: {:?}",
        report.findings
    );
    assert!(
        report
            .findings
            .iter()
            .any(|f| f.field.as_deref() == Some("BodySerialNumber")),
        "the body serial number inside the Exif IFD was not reported"
    );
}

#[test]
fn a_reduced_resolution_thumbnail_does_not_reach_the_output() {
    // A thumbnail is a complete second image that survives any crop or redaction applied to
    // the first (`docs/THREAT_MODEL.md` §3).
    let output = strip("reduced-resolution-thumbnail.tiff");
    assert!(contains(&output, "PRESERVED-TIFF-PIXELS"));
    assert!(
        !contains(&output, "SYNTHETIC-THUMBNAIL-PIXELS-0018"),
        "the reduced-resolution image survived"
    );

    let report = inspect_bytes(
        &fixture("reduced-resolution-thumbnail.tiff"),
        &InspectOptions::names_only(),
    )
    .unwrap();
    assert!(
        report
            .findings
            .iter()
            .any(|f| f.kind == MetadataKind::Thumbnail),
        "the thumbnail was removed without being reported"
    );
}

#[test]
fn a_palette_survives_because_the_image_is_unreadable_without_it() {
    // The other direction of the allow-list's risk: a structural value wrongly dropped breaks
    // the picture. ColorMap is large enough to be stored out of line, so this also exercises
    // the writer's out-of-line path for a *kept* tag.
    let output = strip("palette.tiff");
    let report = inspect_bytes(&output, &InspectOptions::names_only()).unwrap();
    assert!(report.findings.is_empty());
    // 0x0140, SHORT, 48 entries: present in the rebuilt directory.
    let entry = [0x40u8, 0x01, 0x03, 0x00, 0x30, 0x00, 0x00, 0x00];
    assert!(
        output.windows(entry.len()).any(|w| w == entry),
        "the palette did not survive the rebuild"
    );
}

#[test]
fn a_big_endian_file_is_rebuilt_big_endian() {
    let output = strip("big-endian.tiff");
    assert_eq!(&output[0..4], b"MM\x00\x2A", "the byte order changed");
    assert!(contains(&output, "PRESERVED-TIFF-PIXELS"));
    assert!(!contains(&output, "SYNTHETIC-BE-ARTIST-0021"));
}

#[test]
fn every_malformed_fixture_is_refused_rather_than_half_processed() {
    // Fail closed (`CLAUDE.md` §3, constraint 6). None of these may produce output, and none
    // may panic.
    for name in MALFORMED {
        let input = fixture(name);
        assert!(
            strip_bytes(&input, &StripOptions::default()).is_err(),
            "{name} produced output instead of a refusal"
        );
    }
}

#[test]
fn truncating_any_fixture_anywhere_never_panics() {
    // Malformed input is expected input (ADR-0006). Every prefix of every fixture is a file
    // somebody's damaged upload could be.
    for name in FIXTURES {
        let input = fixture(name);
        for cut in 0..input.len() {
            let _ = inspect_bytes(&input[..cut], &InspectOptions::names_only());
            let _ = strip_bytes(&input[..cut], &StripOptions::default());
        }
    }
}

#[test]
fn flipping_any_single_byte_never_panics() {
    // A cheap fuzz-shaped sweep that runs in CI on every push, where the real fuzz runs do
    // not. It has caught offset arithmetic before it reached a fuzzer.
    for name in FIXTURES {
        let input = fixture(name);
        for at in 0..input.len() {
            let mut damaged = input.clone();
            damaged[at] ^= 0xFF;
            let _ = inspect_bytes(&damaged, &InspectOptions::names_only());
            let _ = strip_bytes(&damaged, &StripOptions::default());
        }
    }
}
