//! End-to-end tests for the WAV handler, over the fixtures in `corpus/wav`.
//!
//! Each fixture is generated by `corpus/tools/make_wav_fixtures.py` and documented in
//! `corpus/MANIFEST.md`. The synthetic marker strings — `SYNTHETIC-…-000N` — exist so a test can
//! assert on the *bytes of the output* rather than on strypt's own report: a handler that forgot
//! to remove something would still report having removed it.
//!
//! # Why this file carries its own chunk walker
//!
//! The claims that matter — that the audio crossed byte for byte, and that exactly the chunks
//! ADR-0039 names reached the output — are claims about structure, and checking them with the
//! handler's own walker would assert only that the parser agrees with itself. [`chunks`] walks the
//! file independently, as `tests/flac.rs` walks a block list.

// Test code is not reachable from untrusted bytes, which is the boundary the panic-freedom
// lints police (ADR-0006).
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing,
    clippy::arithmetic_side_effects
)]

use strypt_core::error::UnsupportedKind;
use strypt_core::formats::StripOptions;
use strypt_core::report::{InspectOptions, Note, RetentionReason};
use strypt_core::{Format, StryptError, detect, inspect_bytes, strip_bytes};

fn fixture(name: &str) -> Vec<u8> {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../corpus/wav")
        .join(name);
    std::fs::read(&path).unwrap_or_else(|e| panic!("reading fixture {}: {e}", path.display()))
}

fn strip(name: &str) -> Vec<u8> {
    let input = fixture(name);
    strip_bytes(&input, &StripOptions::default())
        .unwrap_or_else(|e| panic!("stripping {name}: {e}"))
        .bytes
}

fn contains(haystack: &[u8], needle: &str) -> bool {
    haystack
        .windows(needle.len())
        .any(|w| w == needle.as_bytes())
}

const FIXTURES: &[&str] = &[
    "clean.wav",
    "info-list.wav",
    "adtl-list.wav",
    "broadcast-extension.wav",
    "cart.wav",
    "ixml.wav",
    "xmp.wav",
    "id3.wav",
    "sampler.wav",
    "padding.wav",
    "cue-points.wav",
    "unknown-chunk.wav",
    "trailing.wav",
    "kitchen-sink.wav",
];

const MALFORMED: &[&str] = &[
    "truncated.wav",
    "riff-size-past-end.wav",
    "chunk-past-extent.wav",
    "non-ascii-code.wav",
    "no-data.wav",
    "no-fmt.wav",
    "short-fmt.wav",
    "wave-list.wav",
    "rf64.wav",
    "avi.wav",
];

/// The chunks of a RIFF file, as `(four-character code, payload)`. Written here rather than
/// borrowed from the handler: a check that used the code under test to read its own output would
/// prove nothing.
fn chunks(data: &[u8]) -> Vec<(String, Vec<u8>)> {
    assert_eq!(&data[0..4], b"RIFF", "not a RIFF file");
    let declared = u32::from_le_bytes(data[4..8].try_into().unwrap()) as usize;
    let end = 8 + declared;
    assert!(end <= data.len(), "the RIFF size runs past the file");
    assert_eq!(&data[8..12], b"WAVE", "not a WAVE file");

    let mut out = Vec::new();
    let mut at = 12;
    while at + 8 <= end {
        let kind = String::from_utf8_lossy(&data[at..at + 4]).to_string();
        let len = u32::from_le_bytes(data[at + 4..at + 8].try_into().unwrap()) as usize;
        assert!(
            at + 8 + len <= end,
            "chunk {kind} runs past the RIFF extent"
        );
        out.push((kind, data[at + 8..at + 8 + len].to_vec()));
        at += 8 + len + (len & 1);
    }
    assert_eq!(at, end, "the chunks did not tile the RIFF extent exactly");
    out
}

fn payload_of(data: &[u8], kind: &str) -> Option<Vec<u8>> {
    chunks(data)
        .into_iter()
        .find(|(k, _)| k == kind)
        .map(|(_, v)| v)
}

#[test]
fn every_fixture_is_detected_as_wav() {
    for name in FIXTURES {
        assert_eq!(detect(&fixture(name)).unwrap(), Format::Wav, "{name}");
    }
}

#[test]
fn no_synthetic_marker_survives_any_fixture() {
    // The absolute check, independent of what the report claims: every identifying value in the
    // corpus is a marker, so this reads the output bytes rather than strypt's account of them.
    for name in FIXTURES {
        let output = strip(name);
        assert!(
            !contains(&output, "SYNTHETIC-"),
            "a synthetic marker survived {name}"
        );
        // Except the audio, which is deliberately copied and carries no marker of its own.
        assert!(
            payload_of(&output, "data").is_some(),
            "{name} lost its audio"
        );
    }
}

#[test]
fn a_clean_file_comes_back_byte_identical() {
    // Chunk surgery, not re-encoding: nothing to remove means nothing to rewrite (ADR-0039).
    for name in ["clean.wav", "cue-points.wav"] {
        assert_eq!(strip(name), fixture(name), "{name} was rewritten");
    }
}

#[test]
fn the_audio_crosses_byte_for_byte() {
    // The property the whole design rests on: the recording that came in is the one that goes out.
    for name in FIXTURES {
        let before = payload_of(&fixture(name), "data").unwrap();
        let after = payload_of(&strip(name), "data").unwrap();
        assert_eq!(before, after, "the audio in {name} did not survive intact");
    }
}

#[test]
fn only_allow_listed_chunks_reach_the_output() {
    // ADR-0039: `fmt `, `data`, `fact`, `cue ` are copied; `JUNK`, `PAD `, `FLLR` are kept at
    // their length and zeroed; everything else goes, named or not.
    const ALLOWED: &[&str] = &["fmt ", "data", "fact", "cue ", "JUNK", "PAD ", "FLLR"];
    for name in FIXTURES {
        for (kind, _) in chunks(&strip(name)) {
            assert!(
                ALLOWED.contains(&kind.as_str()),
                "{kind} survived {name} and is not on the allow-list"
            );
        }
    }
}

#[test]
fn padding_is_zeroed_at_its_length_rather_than_dropped() {
    let before = payload_of(&fixture("padding.wav"), "JUNK").unwrap();
    let after = payload_of(&strip("padding.wav"), "JUNK").unwrap();
    assert_eq!(after.len(), before.len(), "the padding changed length");
    assert!(
        after.iter().all(|b| *b == 0),
        "the padding was not scrubbed"
    );

    let report = strip_bytes(&fixture("padding.wav"), &StripOptions::default())
        .unwrap()
        .report;
    assert!(
        report
            .retained
            .iter()
            .any(|r| r.reason == RetentionReason::StructurallyRequired),
        "padding was kept without being declared"
    );
}

#[test]
fn a_sampler_chunk_says_what_the_file_can_no_longer_do() {
    let report = strip_bytes(&fixture("sampler.wav"), &StripOptions::default())
        .unwrap()
        .report;
    assert!(
        report
            .notes
            .iter()
            .any(|n| matches!(n, Note::CapabilityRemoved { location, .. } if location == "smpl")),
        "the loop points went without being declared"
    );
}

#[test]
fn the_uninspected_audio_is_declared_on_every_fixture() {
    // Never overclaim: the samples are copied without being decoded, so anything hidden in them
    // is still there, and the report has to say so (CLAUDE.md §3 constraint 7).
    for name in FIXTURES {
        let report = strip_bytes(&fixture(name), &StripOptions::default())
            .unwrap()
            .report;
        assert!(
            report.notes.iter().any(
                |n| matches!(n, Note::OutOfScopeContent { location } if location.starts_with("audio samples"))
            ),
            "{name} did not declare its uninspected audio"
        );
    }
}

#[test]
fn every_malformed_fixture_is_refused() {
    // Fail closed: a file strypt cannot fully account for is refused, never partly cleaned.
    for name in MALFORMED {
        let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../corpus/wav/malformed")
            .join(name);
        let data = std::fs::read(&path).unwrap();
        assert!(
            strip_bytes(&data, &StripOptions::default()).is_err(),
            "{name} was accepted"
        );
    }
}

#[test]
fn the_shapes_that_are_refused_are_refused_by_name() {
    // "Unrecognised" would be untrue and unhelpful for a file most users would call a WAV.
    for (name, kind) in [
        ("wave-list.wav", UnsupportedKind::WaveList),
        ("rf64.wav", UnsupportedKind::Rf64),
        ("avi.wav", UnsupportedKind::OtherRiff),
    ] {
        let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../corpus/wav/malformed")
            .join(name);
        let data = std::fs::read(&path).unwrap();
        match strip_bytes(&data, &StripOptions::default()) {
            Err(StryptError::UnsupportedFormat { format }) => assert_eq!(format, kind, "{name}"),
            other => panic!("{name} was not named: {other:?}"),
        }
    }
}

#[test]
fn output_re_inspects_clean() {
    // The verification pass's own claim, asserted directly: nothing `strip` removed is something
    // `inspect` can still find.
    for name in FIXTURES {
        let report = inspect_bytes(&strip(name), &InspectOptions::names_only()).unwrap();
        assert!(
            report.findings.is_empty(),
            "metadata survived {name}: {:?}",
            report.findings
        );
    }
}

#[test]
fn stripping_is_idempotent_over_the_corpus() {
    for name in FIXTURES {
        let once = strip(name);
        let twice = strip_bytes(&once, &StripOptions::default()).unwrap().bytes;
        assert_eq!(once, twice, "strip is not idempotent for {name}");
    }
}

#[test]
fn inspect_and_strip_agree_on_what_is_there() {
    for name in FIXTURES {
        let input = fixture(name);
        let seen = inspect_bytes(&input, &InspectOptions::names_only())
            .unwrap()
            .findings;
        let removed = strip_bytes(&input, &StripOptions::default())
            .unwrap()
            .report
            .removed;
        assert_eq!(
            seen.len(),
            removed.len(),
            "{name}: show and strip disagree about what is in the file"
        );
    }
}

#[test]
fn stripping_never_grows_a_fixture() {
    // Chunk surgery: output larger than input would mean bytes were synthesised.
    for name in FIXTURES {
        let input = fixture(name);
        assert!(strip(name).len() <= input.len(), "{name} grew");
    }
}

#[test]
fn truncating_any_fixture_anywhere_never_panics() {
    for name in FIXTURES {
        let input = fixture(name);
        for n in 0..=input.len() {
            let prefix = &input[0..n];
            let _ = inspect_bytes(prefix, &InspectOptions::names_only());
            let _ = strip_bytes(prefix, &StripOptions::default());
        }
    }
}

#[test]
fn flipping_any_single_byte_never_panics() {
    // Cheap structural mutation, over the whole corpus. The fuzz target explores much further;
    // this keeps the property under `cargo test` where it cannot be forgotten.
    for name in FIXTURES {
        let input = fixture(name);
        for at in 0..input.len() {
            let mut mutated = input.clone();
            mutated[at] ^= 0xFF;
            let _ = inspect_bytes(&mutated, &InspectOptions::names_only());
            let _ = strip_bytes(&mutated, &StripOptions::default());
        }
    }
}
