//! End-to-end tests for the WebP handler, over the fixtures in `corpus/webp`.
//!
//! Each fixture is generated by `corpus/tools/make_webp_fixtures.py` and documented in
//! `corpus/MANIFEST.md`. Every one is a real, decodable WebP built from the same 16×16 base
//! image, which is what makes the bitstream-identity test below possible: if two fixtures'
//! `VP8L` payloads differ after stripping, something re-encoded a picture.
//!
//! The synthetic marker strings — `SYNTHETIC-WEBP-…-000N` — exist so that a test can assert on
//! the *bytes of the output* rather than on strypt's own report. That distinction is the
//! point: a handler that forgot to remove something would still happily report having removed
//! it.

// Test code is not reachable from untrusted bytes, which is the boundary the panic-freedom
// lints police (ADR-0006).
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing,
    clippy::arithmetic_side_effects
)]

use strypt_core::formats::StripOptions;
use strypt_core::report::{InspectOptions, MetadataKind, Note};
use strypt_core::{Format, detect, inspect_bytes, strip_bytes};

fn fixture(name: &str) -> Vec<u8> {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../corpus/webp")
        .join(name);
    std::fs::read(&path).unwrap_or_else(|e| panic!("reading fixture {}: {e}", path.display()))
}

fn strip(name: &str) -> Vec<u8> {
    let input = fixture(name);
    strip_bytes(&input, &StripOptions::default())
        .unwrap_or_else(|e| panic!("stripping {name}: {e}"))
        .bytes
}

/// True when `haystack` contains `needle` anywhere in its bytes.
fn contains(haystack: &[u8], needle: &str) -> bool {
    haystack
        .windows(needle.len())
        .any(|w| w == needle.as_bytes())
}

/// Every top-level chunk in the file, as (four-character code, payload).
///
/// Walks the chunk list rather than searching for a byte pattern, because a compressed
/// bitstream can contain anything, including the bytes of another chunk header.
fn chunks(data: &[u8]) -> Vec<(String, Vec<u8>)> {
    assert_eq!(&data[0..4], b"RIFF", "not a RIFF file");
    assert_eq!(&data[8..12], b"WEBP", "not a WebP file");
    let end = 8 + u32::from_le_bytes(data[4..8].try_into().unwrap()) as usize;
    assert!(end <= data.len(), "the RIFF size runs past the end");

    let mut out = Vec::new();
    let mut at = 12;
    while at + 8 <= end {
        let kind = String::from_utf8_lossy(&data[at..at + 4]).into_owned();
        let length = u32::from_le_bytes(data[at + 4..at + 8].try_into().unwrap()) as usize;
        out.push((kind, data[at + 8..at + 8 + length].to_vec()));
        at += 8 + length + (length % 2);
    }
    out
}

/// The bitstream payload of a still image. This is the picture; nothing strypt does may change
/// a byte of it.
fn bitstream(data: &[u8]) -> Vec<u8> {
    chunks(data)
        .into_iter()
        .find(|(kind, _)| kind == "VP8L" || kind == "VP8 ")
        .map(|(_, payload)| payload)
        .expect("no bitstream chunk found")
}

/// The `VP8X` flags byte, or [`None`] for a simple-format file that has no such chunk.
fn flags(data: &[u8]) -> Option<u8> {
    chunks(data)
        .into_iter()
        .find(|(kind, _)| kind == "VP8X")
        .map(|(_, payload)| payload[0])
}

const ALL_FIXTURES: &[&str] = &[
    "exif-gps.webp",
    "xmp-packet.webp",
    "icc-profile.webp",
    "all-metadata.webp",
    "unknown-chunk.webp",
    "animated.webp",
    "animation-frame-chunk.webp",
    "unparsable-frame.webp",
    "trailing-data.webp",
    "stale-flags.webp",
    "exif-introducer.webp",
    "clean-lossless.webp",
    "clean-lossy.webp",
    "clean-extended.webp",
];

/// The still images, all of which are the same base picture with different chunks around it.
const STILL_FIXTURES: &[&str] = &[
    "exif-gps.webp",
    "xmp-packet.webp",
    "icc-profile.webp",
    "all-metadata.webp",
    "unknown-chunk.webp",
    "trailing-data.webp",
    "stale-flags.webp",
    "exif-introducer.webp",
    "clean-lossless.webp",
    "clean-extended.webp",
];

/// Files that must come back byte-identical.
///
/// The two simple-format ones are the stronger claim: a WebP with no `VP8X` header cannot carry
/// an ICC profile, Exif, or XMP at all (RFC 9649 §2.7), so this is not "nothing happened to be
/// found" but a guaranteed pass-through.
const PASS_THROUGH_FIXTURES: &[&str] = &[
    "clean-lossless.webp",
    "clean-lossy.webp",
    "clean-extended.webp",
];

/// Every synthetic marker any fixture carries. None may appear in any output.
///
/// `PRESERVED-WEBP-IN-BROKEN-FRAME-0009` is deliberately absent: it lives in an animation frame
/// strypt cannot parse and therefore keeps on purpose, and it has its own test below.
const ALL_MARKERS: &[&str] = &[
    "SYNTHETIC-WEBP-CAMERA-MAKE-0001",
    "SYNTHETIC-WEBP-CAMERA-MODEL-0002",
    "SYNTHETIC-WEBP-XMP-CREATOR-0003",
    "SYNTHETIC-WEBP-XMP-TOOL-0004",
    "SYNTHETIC-WEBP-DOCUMENT-ID-0005",
    "SYNTHETIC-WEBP-ICC-PROFILE-0006",
    "SYNTHETIC-WEBP-PREVIEW-0007",
    "SYNTHETIC-WEBP-IN-FRAME-0008",
];

/// Deliberately broken files. Each is a shape a real parser bug would hide behind.
const MALFORMED_FIXTURES: &[&str] = &[
    "malformed/riff-size-past-end.webp",
    "malformed/chunk-size-past-end.webp",
    "malformed/no-picture-chunk.webp",
    "malformed/bad-fourcc.webp",
    "malformed/truncated.webp",
    "malformed/vp8x-wrong-length.webp",
    "malformed/first-chunk-is-metadata.webp",
];

#[test]
fn every_fixture_is_recognised_as_a_webp_by_its_content() {
    for name in ALL_FIXTURES {
        assert_eq!(detect(&fixture(name)).unwrap(), Format::Webp, "{name}");
    }
}

#[test]
fn no_synthetic_marker_survives_any_strip() {
    // The assertion that matters, and the one that does not trust strypt's own report: the
    // bytes are simply not there afterwards.
    for name in ALL_FIXTURES {
        let output = strip(name);
        for marker in ALL_MARKERS {
            assert!(
                !contains(&output, marker),
                "{marker} survived stripping {name}"
            );
        }
    }
}

#[test]
fn the_picture_is_never_re_encoded() {
    // Every still fixture is the same base image with different chunks around it, so after
    // stripping, every one must have a byte-identical bitstream. A re-encode would betray a
    // user who chose lossless, and would silently degrade one who chose lossy a second time.
    let reference = bitstream(&strip("clean-lossless.webp"));
    for name in STILL_FIXTURES {
        assert_eq!(bitstream(&strip(name)), reference, "{name} was re-encoded");
    }
}

#[test]
fn a_file_with_nothing_to_remove_comes_back_byte_identical() {
    for name in PASS_THROUGH_FIXTURES {
        let input = fixture(name);
        let stripped = strip_bytes(&input, &StripOptions::default()).unwrap();
        assert!(stripped.report.removed.is_empty(), "{name}");
        assert_eq!(stripped.bytes, input, "{name} was not passed through");
    }
}

#[test]
fn stripped_output_inspects_clean() {
    for name in ALL_FIXTURES {
        let output = strip(name);
        let report = inspect_bytes(&output, &InspectOptions::names_only()).unwrap();
        assert!(
            report.findings.is_empty(),
            "{name} still reports {:?} after stripping",
            report.findings
        );
    }
}

#[test]
fn stripping_is_idempotent_byte_for_byte() {
    for name in ALL_FIXTURES {
        let once = strip(name);
        let twice = strip_bytes(&once, &StripOptions::default()).unwrap().bytes;
        assert_eq!(once, twice, "{name} is not idempotent");
    }
}

#[test]
fn a_malformed_file_is_refused_or_cleaned_but_never_mishandled() {
    // Malformed input is expected input (ADR-0006). The requirement is not that every one of
    // these is refused, but that nothing panics, and that anything reported as a success
    // really is clean.
    for name in MALFORMED_FIXTURES {
        let input = fixture(name);
        let _ = inspect_bytes(&input, &InspectOptions::names_only());
        if let Ok(stripped) = strip_bytes(&input, &StripOptions::default()) {
            let report = inspect_bytes(&stripped.bytes, &InspectOptions::names_only())
                .unwrap_or_else(|e| panic!("{name} stripped to something unparseable: {e}"));
            assert!(
                report.findings.is_empty(),
                "{name} was reported clean but is not"
            );
            let again = strip_bytes(&stripped.bytes, &StripOptions::default()).unwrap();
            assert_eq!(stripped.bytes, again.bytes, "{name} is not idempotent");
        }
    }
}

#[test]
fn an_exif_chunk_reports_its_location_and_device_by_name() {
    // "an EXIF chunk was removed" is not useful to someone deciding whether a file they already
    // published is a problem. The field names are.
    let report = inspect_bytes(&fixture("exif-gps.webp"), &InspectOptions::names_only()).unwrap();
    let fields: Vec<&str> = report
        .findings
        .iter()
        .filter_map(|f| f.field.as_deref())
        .collect();
    for expected in ["GPSLatitude", "GPSLongitude", "Make", "Model"] {
        assert!(
            fields.contains(&expected),
            "{expected} was not named: {fields:?}"
        );
    }
}

#[test]
fn an_exif_chunk_carrying_a_jpeg_introducer_is_read_rather_than_misparsed() {
    // The container specification puts no introducer in this chunk, but a producer copying a
    // JPEG `APP1` payload across brings one. Those six bytes shift every offset inside the TIFF
    // block, so a reader that does not notice produces a confident parse of the wrong bytes.
    let with_introducer = inspect_bytes(
        &fixture("exif-introducer.webp"),
        &InspectOptions::names_only(),
    )
    .unwrap();
    let without = inspect_bytes(&fixture("exif-gps.webp"), &InspectOptions::names_only()).unwrap();
    let names = |report: &strypt_core::report::MetadataReport| -> Vec<String> {
        report
            .findings
            .iter()
            .filter_map(|f| f.field.clone())
            .collect()
    };
    assert_eq!(names(&with_introducer), names(&without));
    assert!(names(&with_introducer).contains(&"GPSLatitude".to_owned()));
}

#[test]
fn an_xmp_packet_is_itemised_by_property() {
    let report = inspect_bytes(&fixture("xmp-packet.webp"), &InspectOptions::names_only()).unwrap();
    let fields: Vec<&str> = report
        .findings
        .iter()
        .filter_map(|f| f.field.as_deref())
        .collect();
    assert!(fields.contains(&"dc:creator"), "{fields:?}");
    assert!(fields.contains(&"xmp:CreatorTool"), "{fields:?}");
    assert!(fields.contains(&"xmpMM:DocumentID"), "{fields:?}");
}

#[test]
fn the_header_flags_stop_claiming_metadata_the_file_no_longer_has() {
    // Leave the bits set and the file lies about itself: some decoders warn, some refuse
    // (ADR-0023). The alpha bit describes the picture, not the metadata, and must survive.
    let input = fixture("all-metadata.webp");
    assert_eq!(flags(&input), Some(0b0011_1100));
    assert_eq!(
        flags(&strip("all-metadata.webp")),
        Some(0b0001_0000),
        "the VP8X flags still claim metadata that is gone"
    );
}

#[test]
fn flags_that_were_already_lying_are_corrected_with_nothing_to_remove() {
    // A header claiming an ICC profile, Exif, and XMP that the file does not have. There is
    // nothing removable, so `show` reports nothing — and `strip` still returns a truthful file.
    let input = fixture("stale-flags.webp");
    let stripped = strip_bytes(&input, &StripOptions::default()).unwrap();
    assert!(stripped.report.removed.is_empty());
    assert_eq!(flags(&stripped.bytes), Some(0));
    assert_ne!(stripped.bytes, input);
}

#[test]
fn an_unknown_chunk_is_removed_rather_than_preserved() {
    // RFC 9649 §2.7.1.6 asks writers to preserve unknown chunks. strypt is not a general WebP
    // writer, and an unknown chunk is exactly where something goes that its producer would
    // rather a metadata tool did not look at. The same section makes unknown chunks ignorable
    // to readers, so dropping one cannot break a decoder.
    let stripped = strip_bytes(&fixture("unknown-chunk.webp"), &StripOptions::default()).unwrap();
    assert!(!contains(&stripped.bytes, "SYNTHETIC-WEBP-PREVIEW-0007"));
    assert_eq!(stripped.report.removed[0].location, "PRVW");
}

#[test]
fn an_animation_keeps_its_frames_and_loses_its_metadata() {
    let stripped = strip_bytes(&fixture("animated.webp"), &StripOptions::default()).unwrap();
    let kinds: Vec<String> = chunks(&stripped.bytes)
        .into_iter()
        .map(|(kind, _)| kind)
        .collect();
    assert_eq!(
        kinds.iter().filter(|k| *k == "ANMF").count(),
        2,
        "an animation lost a frame: {kinds:?}"
    );
    assert!(kinds.contains(&"ANIM".to_owned()));
    assert!(!kinds.contains(&"EXIF".to_owned()));
    assert_eq!(flags(&stripped.bytes), Some(0b0000_0010), "{kinds:?}");
}

#[test]
fn a_chunk_hidden_inside_an_animation_frame_is_removed() {
    // §2.7.1.1 explicitly allows unknown chunks inside a frame, which makes the inside of one a
    // hiding place with the specification's blessing. A handler that filtered only the top
    // level would walk straight past this.
    let stripped = strip_bytes(
        &fixture("animation-frame-chunk.webp"),
        &StripOptions::default(),
    )
    .unwrap();
    assert!(!contains(&stripped.bytes, "SYNTHETIC-WEBP-IN-FRAME-0008"));
    assert_eq!(stripped.report.removed[0].location, "ANMF JUNK");
    assert!(
        chunks(&stripped.bytes)
            .iter()
            .any(|(kind, _)| kind == "ANMF"),
        "the frame itself was dropped"
    );
}

#[test]
fn a_frame_that_does_not_parse_is_kept_and_the_report_says_it_was_not_examined() {
    // Refusing the whole file would be the wrong call for a frame strypt only partly
    // understands, and keeping it silently would let the user believe it had been scrubbed.
    let stripped =
        strip_bytes(&fixture("unparsable-frame.webp"), &StripOptions::default()).unwrap();
    assert!(
        contains(&stripped.bytes, "PRESERVED-WEBP-IN-BROKEN-FRAME-0009"),
        "an unparsable frame was rewritten rather than left alone"
    );
    assert!(
        stripped
            .report
            .notes
            .iter()
            .any(|n| matches!(n, Note::UnparsedRegion { location, .. } if location == "ANMF")),
        "the kept frame was not reported: {:?}",
        stripped.report.notes
    );
}

#[test]
fn data_after_the_riff_chunk_is_removed_and_reported() {
    // A whole second WebP past the declared RIFF size. Nothing reads it, few users know it can
    // be there, and it is a comfortable fit for an uncropped copy of a cropped picture.
    let stripped = strip_bytes(&fixture("trailing-data.webp"), &StripOptions::default()).unwrap();
    assert!(!contains(
        &stripped.bytes,
        "SYNTHETIC-WEBP-XMP-CREATOR-0003"
    ));
    let trailing = stripped
        .report
        .removed
        .iter()
        .find(|f| f.location == "trailing data after the RIFF chunk")
        .expect("trailing data was not reported");
    assert_eq!(trailing.kind, MetadataKind::Thumbnail);
}

#[test]
fn an_icc_profile_is_removed_and_ranked_as_a_colour_profile() {
    let report =
        inspect_bytes(&fixture("icc-profile.webp"), &InspectOptions::names_only()).unwrap();
    assert_eq!(report.findings[0].kind, MetadataKind::ColourProfile);
    assert_eq!(report.findings[0].location, "ICCP");
    assert!(!contains(
        &strip("icc-profile.webp"),
        "SYNTHETIC-WEBP-ICC-PROFILE-0006"
    ));
}

#[test]
fn a_file_with_no_picture_chunk_is_refused_rather_than_emptied() {
    // Otherwise this strips to a valid-looking container with no image in it, and the user is
    // told it succeeded — which is the failure mode in `docs/THREAT_MODEL.md` §5.4.
    let input = fixture("malformed/no-picture-chunk.webp");
    assert!(strip_bytes(&input, &StripOptions::default()).is_err());
}
